### PR TITLE
Generic-Reduction follow-up

### PR DESCRIPTION
**Pull request by fronteer**
Generic-Reduction follow up after #727

### CODE REVIEW

**Comment by atamazov** [comment]
#727 is merged & closed. Now we have the follow-up #757 that needs resolving.

Does this PR resolve something from #757? If yes, please update the topmost comment (PR description) with relevant info. Thanks.

**Comment by atamazov** [comment]
@fronteer 
> fix issue with indiced reductions of reduced size bigger than BlockSize

Important questions:
1. Which operations affected by the issue?
2. Is it a new issue, appeared after adding new ops?
3. Does the latest version of reduction unit test detect the issue?

Thanks.
/cc @dagamayank @JehandadKhan

**Comment by fronteer** [comment]
> @fronteer
> 
> > fix issue with indiced reductions of reduced size bigger than BlockSize
> 
> Important questions:
> 
>     1. Which operations affected by the issue?
> 
>     2. Is it a new issue, appeared after adding new ops?
> 
>     3. Does the latest version of reduction unit test detect the issue?
> 
> 
> Thanks.
> /cc @dagamayank @JehandadKhan

Issues occurred with the three Reduction operations MIN/MAX/AMAX that could also have the indices of reduced values outputted, and it occurs when reduced size is bigger than 256.  The issue could not be exposed when tested using `test_reduce_test`, but can be exposed using `MIOpenDriver reduce`  due to the difference in their initialized data(very strange).  For example: 

`#> bin/MIOpenDriver reduce -D 64,3,280,81 -R 2  -O 2 -N 0 -I 1

Can this fix be still absorbed into 4.2 ?

**Comment by fronteer** [comment]
The above commits have been tested on gfx900, gfx906, gfx908, gfx1030 with ROCM 4.0.1

**Comment by atamazov** [comment]
> Can this fix be still absorbed into 4.2 ?

No. But hopefully this can wait because only AVG is absolutely required there.

**Comment by atamazov** [comment]
@fronteer 
> Issues occurred with the three Reduction operations MIN/MAX/AMAX that could also have the indices of reduced values outputted, and it occurs when reduced size is bigger than 256.  The issue could not be exposed when tested using `test_reduce_test`

Could you accept this into work and improve reduce_test? I think this is important.

/cc @JehandadKhan @dagamayank

**Comment by atamazov** [comment]
Is it ready for review? Please assign reviewers if so, or make it draft otherwise. Thanks.

**Comment by fronteer** [comment]
> @fronteer
> 
> > Issues occurred with the three Reduction operations MIN/MAX/AMAX that could also have the indices of reduced values outputted, and it occurs when reduced size is bigger than 256.  The issue could not be exposed when tested using `test_reduce_test`
> 
> Could you accept this into work and improve reduce_test? I think this is important.
> 
> /cc @JehandadKhan @dagamayank

Yes, you are right.   Currently, all the codes under test/ does not use "RAN_GEN" for initializing data, instead tensor_elem_gen_integer() is used, because this is much faster.   I will use a "RAN_GEN" similar method to initializing data for reduce_test with operations MIN/MAX/AMAX.    The MIN/MAX/AMAX is easier to fail when indices are outputted since it is required to keep the indices completely consistent to the sequentially reduced results by the CPU side.

**Comment by atamazov** [comment]
Please fix formatting issues.

**Comment by fronteer** [comment]
> Please fix formatting issues.
```c++
/data/my-tests/miopen/MIOpen-zqf/src/kernels/composable_kernel/include/kernel_algorithm/reduction_functions.hpp:47:55: warning: Parameter 'accuVal' can be declared with const [constParameter]
    __device__ static inline void calculate(compType& accuVal, compType currVal)
                                                      ^
/data/my-tests/miopen/MIOpen-zqf/src/kernels/composable_kernel/include/kernel_algorithm/reduction_functions.hpp:54:25: warning: Parameter 'accuVal' can be declared with const [constParameter]
    calculate(compType& accuVal, compType currVal, int& accuIndex, int currIndex)
                        ^
```
Do you mean this one?   If adding "const",  I have to convert it back to non-const by 
`opReduce{}(const_cast<compType&>(accuVal), currVal);`

Or else, the compiler will fail when compiling the kernels.  What is the best way to solve this issue ?

**Comment by JehandadKhan** [comment]
@fronteer Please prioritize numerical accuracy above all else, catching these errors in higher level frameworks is challenging and consumes valuable engineering effort. If change to the tests is required, please go ahead and do it.

**Comment by atamazov** [comment]
@fronteer 
> Do you mean this one?

No, you can see those at our CI. Do you have access to it? If not, please open a mail thread.

**Comment by atamazov** [comment]
@JehandadKhan This is the answer by @fronteer :

> Yes.   So far, after commit [d59c317](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/774/commits/d59c317ec7da621c3e315457ec6bdb4a3705bf5b), I found no failure with all MIN/MAX/AMAX testings using `MOpenDriver reduce`.   I will improve the input initialization for reduce_test

**Comment by atamazov** [comment]
>> Please fix formatting issues.

> ...
> Do you mean this one? ... Or else... 

No. Look here: https://github.com/ROCmSoftwarePlatform/MIOpen/wiki/How-to-format-code

**Comment by fronteer** [comment]
> > > Please fix formatting issues.
> 
> > ...
> > Do you mean this one? ... Or else...
> 
> No. Look here: https://github.com/ROCmSoftwarePlatform/MIOpen/wiki/How-to-format-code

I usually use clang-format-3.8 manually after the modification of single file, sometimes, some file might be leaked by me

**Comment by fronteer** [comment]
> > > > Please fix formatting issues.
> > 
> > 
> > > ...
> > > Do you mean this one? ... Or else...
> > 
> > 
> > No. Look here: https://github.com/ROCmSoftwarePlatform/MIOpen/wiki/How-to-format-code
> 
> I usually use clang-format-3.8 manually after the modification of single file, sometimes, some file might be leaked

**Comment by fronteer** [comment]
> > > > > Please fix formatting issues.
> > > 
> > > 
> > > > ...
> > > > Do you mean this one? ... Or else...
> > > 
> > > 
> > > No. Look here: https://github.com/ROCmSoftwarePlatform/MIOpen/wiki/How-to-format-code
> > 
> > 
> > I usually use clang-format-3.8 manually after the modification of single file, sometimes, some file might be leak

I run the clang-format-3.8 again on those files involved by Reduction,  but found no issues.   Actually,  I have a local docker for running "make analyze",   the only issue I found with "make analyze" is  the following
```C++
/data/my-tests/miopen/MIOpen-zqf/src/kernels/composable_kernel/include/kernel_algorithm/reduction_functions.hpp:47:55: warning: Parameter 'accuVal' can be declared with const [constParameter]
    __device__ static inline void calculate(compType& accuVal, compType currVal)
                                                      ^
/data/my-tests/miopen/MIOpen-zqf/src/kernels/composable_kernel/include/kernel_algorithm/reduction_functions.hpp:54:25: warning: Parameter 'accuVal' can be declared with const [constParameter]
    calculate(compType& accuVal, compType currVal, int& accuIndex, int currIndex)
                        ^
CMake Error at build-ci/cppcheck.cmake:30 (message):
  Cppcheck failed
```

**Comment by atamazov** [comment]
@fronteer Please follow the cppcheck's recommendations. In this specific case it recommends declaring accuVal as const reference.

**Comment by atamazov** [comment]
@fronteer 
> I usually use clang-format-3.8 manually after the modification of single file, sometimes, some file might be leaked by me

Run the script provided at wiki page. The script reformats necessary source files. Please do not forget to commit reformatted source files after that, otherwise the formatting check at CI will continue to complain.

**Comment by fronteer** [comment]
> @fronteer Please follow the cppcheck's recommendations. In this specific case it recommends declaring accuVal as const reference.

Ok.  But very strange!

**Comment by atamazov** [comment]
This is good. cppcheck sees that the function does not modify a variable passed by reference. It recommends declaring it const. You do that. The C++ compiler now can do more optimizations.

The rule of thumb: add const everywhere, then remove only if absolutely necessary ;)

**Comment by atamazov** [comment]
Please merge recent develop into this branch (see mail).

**Comment by atamazov** [comment]
@fronteer Does it resolve the following:

> NORM1 should be "sum of absolute values".  The results I get appears to be = sum(abs(values)) / N.
> NORM2 should be "square root of the sum of squares".  The result I get appears to be = sqrt( sum(values * values) / N ).

**Comment by atamazov** [comment]
@fronteer `test_reduce_test` is constantly failing at the "Fp16 Hip Install All Vega20" stage:
```
[2021-03-31T16:10:38.137Z] 62/67 Test #39: test_reduce_test .................***Failed  317.14 sec
[2021-03-31T16:10:38.137Z] Memory access fault by GPU node-4 (Agent handle: 0x2222f70) on address 0x7fb574600000. Reason: Unknown.
[2021-03-31T16:10:38.137Z] 
[2021-03-31T16:10:38.137Z] warning: core file may not match specified executable file.
[2021-03-31T16:10:38.137Z] [New LWP 9888]
[2021-03-31T16:10:38.137Z] [New LWP 9890]
[2021-03-31T16:10:38.137Z] [New LWP 9758]
[2021-03-31T16:10:38.137Z] [Thread debugging using libthread_db enabled]
[2021-03-31T16:10:38.137Z] Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[2021-03-31T16:10:38.137Z] Core was generated by `/var/jenkins/workspace/MLLibs_MIOpen_reduction-follow/build/bin/test_reduce_tes'.
[2021-03-31T16:10:38.137Z] Program terminated with signal SIGABRT, Aborted.
[2021-03-31T16:10:38.137Z] #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
[2021-03-31T16:10:38.137Z] 51	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
[2021-03-31T16:10:38.137Z] [Current thread is 1 (Thread 0x7fb676bf1700 (LWP 9888))]
[2021-03-31T16:10:38.137Z] #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
[2021-03-31T16:10:38.137Z] #1  0x00007fb677ad7921 in __GI_abort () at abort.c:79
[2021-03-31T16:10:38.137Z] #2  0x00007fb67709b27f in rocr::core::Runtime::VMFaultHandler(long, void*) () from /opt/rocm-3.7.0/hip/lib/../../lib/libhsa-runtime64.so.1
[2021-03-31T16:10:38.137Z] #3  0x00007fb67709d38b in rocr::core::Runtime::AsyncEventsLoop(void*) () from /opt/rocm-3.7.0/hip/lib/../../lib/libhsa-runtime64.so.1
[2021-03-31T16:10:38.137Z] #4  0x00007fb67704b367 in rocr::os::ThreadTrampoline(void*) () from /opt/rocm-3.7.0/hip/lib/../../lib/libhsa-runtime64.so.1
[2021-03-31T16:10:38.137Z] #5  0x00007fb6826286db in start_thread (arg=0x7fb676bf1700) at pthread_create.c:463
[2021-03-31T16:10:38.137Z] #6  0x00007fb677bb871f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
[2021-03-31T16:10:38.137Z] CMake Error at test_test_reduce_test.cmake:7 (message):
[2021-03-31T16:10:38.137Z]   Test failed
```

**Comment by atamazov** [comment]
This is ROCm 3.7 specific issue. I will provide workaround for the test.

**Review by atamazov — APPROVED** [review]
LGTM

**Comment by fronteer** [comment]
> @fronteer Does it resolve the following:
> 
> > NORM1 should be "sum of absolute values".  The results I get appears to be = sum(abs(values)) / N.
> > NORM2 should be "square root of the sum of squares".  The result I get appears to be = sqrt( sum(values * values) / N ).

Yes.  This is corrected.

**Comment by fronteer** [comment]
> > @fronteer Does it resolve the following:
> > > NORM1 should be "sum of absolute values".  The results I get appears to be = sum(abs(values)) / N.
> > > NORM2 should be "square root of the sum of squares".  The result I get appears to be = sqrt( sum(values * values) / N ).
> 
> Yes. This is corrected by   _https://github.com/ROCmSoftwarePlatform/MIOpen/pull/774/commits/deaa23e9cc38997310e7adf082da4fd6a741f7b4_

**Pull request merged**
