### PR TITLE
[FP16] Winograd f3x2 fp16 support

### PR DESCRIPTION
**Pull request by Slimakanzer**
This PR adds support for fp16 _Winograd f3x2_ solver.

## Performance testing
* gfx906, ROCm 4.0
* gfx1030, ROCm  4.2

## Performance improvements
`speedup = (avg time without f3x2 fp16) / (avg time with f3x2 fp16)`. Only configs that reveal some gain are shown (out of total 500 configs for each direction).

<details><summary>gfx9 speedup details</summary>
<p>

W | H | C | N | K | x | y | p | q | Direction | Speedup
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
7 | 7 | 832 | 16 | 128 | 3 | 3 | 1 | 1 | wrw | 2.32
27 | 27 | 64 | 128 | 192 | 1 | 1 | 0 | 0 | bwd | 2.90
27 | 27 | 96 | 50 | 256 | 1 | 1 | 0 | 0 | bwd | 2.05
27 | 27 | 96 | 64 | 256 | 1 | 1 | 0 | 0 | bwd | 2.69
27 | 27 | 96 | 256 | 256 | 1 | 1 | 0 | 0 | bwd | 3.30
256 | 128 | 128 | 1 | 192 | 1 | 1 | 0 | 0 | bwd | 2.01
512 | 256 | 64 | 1 | 192 | 1 | 1 | 0 | 0 | bwd | 1.78
27 | 27 | 96 | 50 | 256 | 1 | 1 | 0 | 0 | fwd | 1.71
27 | 27 | 64 | 128 | 192 | 1 | 1 | 0 | 0 | fwd | 2.47
56 | 56 | 64 | 32 | 192 | 1 | 1 | 0 | 0 | bwd | 1.82
112 | 112 | 64 | 16 | 128 | 1 | 1 | 0 | 0 | bwd | 1.77
13 | 13 | 192 | 128 | 384 | 1 | 1 | 0 | 0 | bwd | 2.15
13 | 13 | 256 | 64 | 384 | 1 | 1 | 0 | 0 | bwd | 2.14
13 | 13 | 384 | 64 | 384 | 1 | 1 | 0 | 0 | bwd | 1.73
13 | 13 | 192 | 64 | 384 | 1 | 1 | 0 | 0 | bwd | 2.08
112 | 112 | 64 | 8 | 128 | 1 | 1 | 0 | 0 | bwd | 1.69
13 | 13 | 384 | 256 | 256 | 3 | 3 | 1 | 1 | wrw | 1.86
112 | 112 | 64 | 64 | 128 | 1 | 1 | 0 | 0 | bwd | 2.41
13 | 13 | 384 | 128 | 384 | 3 | 3 | 1 | 1 | wrw | 2.04
13 | 13 | 256 | 256 | 384 | 3 | 3 | 1 | 1 | wrw | 1.88
512 | 256 | 64 | 1 | 192 | 1 | 1 | 0 | 0 | fwd | 1.46
256 | 128 | 96 | 1 | 128 | 1 | 1 | 0 | 0 | fwd | 1.65
13 | 13 | 384 | 64 | 256 | 1 | 1 | 0 | 0 | bwd | 2.25
13 | 13 | 384 | 128 | 256 | 3 | 3 | 1 | 1 | wrw | 1.87
13 | 13 | 256 | 64 | 256 | 1 | 1 | 0 | 0 | bwd | 1.72
256 | 128 | 128 | 1 | 192 | 1 | 1 | 0 | 0 | fwd | 1.75
256 | 128 | 96 | 1 | 128 | 1 | 1 | 0 | 0 | bwd | 1.56
13 | 13 | 256 | 128 | 384 | 3 | 3 | 1 | 1 | wrw | 1.91
112 | 112 | 64 | 32 | 128 | 1 | 1 | 0 | 0 | bwd | 2.26
13 | 13 | 384 | 256 | 384 | 3 | 3 | 1 | 1 | wrw | 1.77
13 | 13 | 384 | 50 | 256 | 1 | 1 | 0 | 0 | bwd | 1.72
13 | 13 | 192 | 50 | 384 | 1 | 1 | 0 | 0 | bwd | 1.74
13 | 13 | 384 | 50 | 256 | 3 | 3 | 1 | 1 | wrw | 1.87
13 | 13 | 256 | 50 | 384 | 3 | 3 | 1 | 1 | wrw | 1.90
7 | 7 | 832 | 1 | 128 | 3 | 3 | 1 | 1 | wrw | 1.73
13 | 13 | 256 | 50 | 384 | 1 | 1 | 0 | 0 | bwd | 1.75
13 | 13 | 256 | 128 | 256 | 1 | 1 | 0 | 0 | bwd | 2.03
13 | 13 | 256 | 50 | 384 | 1 | 1 | 0 | 0 | fwd | 1.62
112 | 112 | 64 | 8 | 128 | 1 | 1 | 0 | 0 | fwd | 1.19
13 | 13 | 384 | 64 | 256 | 3 | 3 | 1 | 1 | wrw | 1.75
13 | 13 | 256 | 64 | 384 | 3 | 3 | 1 | 1 | wrw | 1.88
13 | 13 | 384 | 50 | 256 | 1 | 1 | 0 | 0 | fwd | 1.58
13 | 13 | 256 | 256 | 384 | 1 | 1 | 0 | 0 | bwd | 2.25
13 | 13 | 384 | 64 | 384 | 3 | 3 | 1 | 1 | wrw | 2.49
13 | 13 | 192 | 256 | 384 | 1 | 1 | 0 | 0 | bwd | 2.24
13 | 13 | 256 | 50 | 256 | 1 | 1 | 0 | 0 | bwd | 1.57
13 | 13 | 384 | 256 | 256 | 1 | 1 | 0 | 0 | bwd | 1.46
13 | 13 | 384 | 128 | 384 | 1 | 1 | 0 | 0 | bwd | 2.23
13 | 13 | 192 | 50 | 384 | 1 | 1 | 0 | 0 | fwd | 1.55
56 | 56 | 64 | 32 | 192 | 1 | 1 | 0 | 0 | fwd | 2.19
13 | 13 | 256 | 50 | 256 | 1 | 1 | 0 | 0 | fwd | 1.66
14 | 14 | 512 | 16 | 48 | 3 | 3 | 1 | 1 | wrw | 1.67
13 | 13 | 384 | 50 | 384 | 3 | 3 | 1 | 1 | wrw | 1.75
112 | 112 | 64 | 1 | 128 | 1 | 1 | 0 | 0 | bwd | 1.54
112 | 112 | 64 | 2 | 128 | 1 | 1 | 0 | 0 | fwd | 1.47
13 | 13 | 256 | 256 | 256 | 3 | 3 | 1 | 1 | wrw | 1.56
28 | 28 | 32 | 32 | 96 | 1 | 1 | 0 | 0 | bwd | 1.48
13 | 13 | 256 | 50 | 256 | 3 | 3 | 1 | 1 | wrw | 1.35
13 | 13 | 192 | 50 | 384 | 3 | 3 | 1 | 1 | wrw | 1.37
13 | 13 | 256 | 128 | 256 | 3 | 3 | 1 | 1 | wrw | 1.52
13 | 13 | 256 | 64 | 256 | 3 | 3 | 1 | 1 | wrw | 1.45
112 | 112 | 64 | 2 | 128 | 1 | 1 | 0 | 0 | bwd | 1.45
13 | 13 | 192 | 64 | 384 | 3 | 3 | 1 | 1 | wrw | 1.40
13 | 13 | 192 | 128 | 384 | 3 | 3 | 1 | 1 | wrw | 1.41
13 | 13 | 192 | 256 | 384 | 3 | 3 | 1 | 1 | wrw | 1.39
112 | 112 | 64 | 1 | 128 | 1 | 1 | 0 | 0 | fwd | 1.30

</p>
</details>

<details><summary>gfx10 speedup details</summary>
<p>

W | H | C | N | K | x | y | p | q | Direction | Speedup
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
7 | 7 | 832 | 16 | 128 | 3 | 3 | 1 | 1 | wrw | 1.96
27 | 27 | 64 | 128 | 192 | 1 | 1 | 0 | 0 | bwd | 1.84
27 | 27 | 96 | 50 | 256 | 1 | 1 | 0 | 0 | bwd | 2.13
27 | 27 | 96 | 64 | 256 | 1 | 1 | 0 | 0 | bwd | 1.95
27 | 27 | 96 | 256 | 256 | 1 | 1 | 0 | 0 | bwd | 2.21
27 | 27 | 96 | 64 | 256 | 1 | 1 | 0 | 0 | fwd | 1.57
256 | 128 | 128 | 1 | 192 | 1 | 1 | 0 | 0 | bwd | 1.86
512 | 256 | 64 | 1 | 192 | 1 | 1 | 0 | 0 | bwd | 1.95
27 | 27 | 96 | 50 | 256 | 1 | 1 | 0 | 0 | fwd | 1.94
27 | 27 | 64 | 128 | 192 | 1 | 1 | 0 | 0 | fwd | 1.76
56 | 56 | 64 | 32 | 192 | 1 | 1 | 0 | 0 | bwd | 1.71
112 | 112 | 64 | 16 | 128 | 1 | 1 | 0 | 0 | bwd | 1.71
13 | 13 | 192 | 128 | 384 | 1 | 1 | 0 | 0 | bwd | 1.70
13 | 13 | 256 | 64 | 384 | 1 | 1 | 0 | 0 | bwd | 1.89
27 | 27 | 96 | 256 | 256 | 1 | 1 | 0 | 0 | fwd | 1.72
13 | 13 | 384 | 64 | 384 | 1 | 1 | 0 | 0 | bwd | 1.73
13 | 13 | 192 | 64 | 384 | 1 | 1 | 0 | 0 | bwd | 1.78
112 | 112 | 64 | 8 | 128 | 1 | 1 | 0 | 0 | bwd | 1.61
13 | 13 | 384 | 256 | 256 | 3 | 3 | 1 | 1 | wrw | 1.34
224 | 224 | 3 | 16 | 64 | 1 | 1 | 0 | 0 | bwd | 1.75
13 | 13 | 384 | 50 | 384 | 1 | 1 | 0 | 0 | bwd | 1.83
13 | 13 | 384 | 128 | 384 | 3 | 3 | 1 | 1 | wrw | 1.26
512 | 256 | 64 | 1 | 192 | 1 | 1 | 0 | 0 | fwd | 1.71
256 | 128 | 96 | 1 | 128 | 1 | 1 | 0 | 0 | fwd | 1.53
13 | 13 | 384 | 64 | 256 | 1 | 1 | 0 | 0 | fwd | 1.43
13 | 13 | 384 | 64 | 256 | 1 | 1 | 0 | 0 | bwd | 1.73
13 | 13 | 384 | 128 | 256 | 3 | 3 | 1 | 1 | wrw | 1.39
13 | 13 | 256 | 64 | 256 | 1 | 1 | 0 | 0 | bwd | 1.81
256 | 128 | 128 | 1 | 192 | 1 | 1 | 0 | 0 | fwd | 1.95
224 | 224 | 3 | 8 | 64 | 1 | 1 | 0 | 0 | bwd | 1.75
13 | 13 | 384 | 50 | 384 | 1 | 1 | 0 | 0 | fwd | 1.83
256 | 128 | 96 | 1 | 128 | 1 | 1 | 0 | 0 | bwd | 1.46
13 | 13 | 256 | 128 | 384 | 3 | 3 | 1 | 1 | wrw | 1.31
13 | 13 | 384 | 50 | 256 | 1 | 1 | 0 | 0 | bwd | 1.82
13 | 13 | 192 | 50 | 384 | 1 | 1 | 0 | 0 | bwd | 1.73
13 | 13 | 384 | 256 | 384 | 1 | 1 | 0 | 0 | bwd | 1.88
13 | 13 | 256 | 64 | 256 | 1 | 1 | 0 | 0 | fwd | 1.60
13 | 13 | 256 | 64 | 384 | 1 | 1 | 0 | 0 | fwd | 1.35
112 | 112 | 64 | 16 | 128 | 1 | 1 | 0 | 0 | fwd | 1.65
224 | 224 | 3 | 2 | 64 | 1 | 1 | 0 | 0 | bwd | 1.44
13 | 13 | 384 | 50 | 256 | 3 | 3 | 1 | 1 | wrw | 1.38
13 | 13 | 256 | 50 | 384 | 3 | 3 | 1 | 1 | wrw | 1.37
7 | 7 | 832 | 1 | 128 | 3 | 3 | 1 | 1 | wrw | 1.47
13 | 13 | 256 | 50 | 384 | 1 | 1 | 0 | 0 | bwd | 1.86
13 | 13 | 256 | 128 | 256 | 1 | 1 | 0 | 0 | bwd | 1.86
13 | 13 | 256 | 50 | 384 | 1 | 1 | 0 | 0 | fwd | 1.82
112 | 112 | 64 | 8 | 128 | 1 | 1 | 0 | 0 | fwd | 1.60
13 | 13 | 384 | 128 | 256 | 1 | 1 | 0 | 0 | bwd | 1.87
13 | 13 | 384 | 64 | 256 | 3 | 3 | 1 | 1 | wrw | 1.36
7 | 7 | 832 | 2 | 128 | 3 | 3 | 1 | 1 | wrw | 1.47
13 | 13 | 256 | 64 | 384 | 3 | 3 | 1 | 1 | wrw | 1.35
13 | 13 | 384 | 50 | 256 | 1 | 1 | 0 | 0 | fwd | 1.90
13 | 13 | 256 | 128 | 256 | 1 | 1 | 0 | 0 | fwd | 1.29
13 | 13 | 256 | 256 | 384 | 1 | 1 | 0 | 0 | bwd | 1.96
13 | 13 | 384 | 64 | 384 | 3 | 3 | 1 | 1 | wrw | 1.60
13 | 13 | 256 | 128 | 384 | 1 | 1 | 0 | 0 | bwd | 1.93
13 | 13 | 192 | 256 | 384 | 1 | 1 | 0 | 0 | bwd | 1.83
13 | 13 | 256 | 50 | 256 | 1 | 1 | 0 | 0 | bwd | 1.77
13 | 13 | 384 | 256 | 256 | 1 | 1 | 0 | 0 | bwd | 1.88
13 | 13 | 384 | 128 | 384 | 1 | 1 | 0 | 0 | bwd | 1.85
13 | 13 | 192 | 50 | 384 | 1 | 1 | 0 | 0 | fwd | 1.68
56 | 56 | 64 | 32 | 192 | 1 | 1 | 0 | 0 | fwd | 1.52
56 | 56 | 64 | 64 | 64 | 1 | 1 | 0 | 0 | bwd | 1.64
56 | 56 | 64 | 64 | 64 | 1 | 1 | 0 | 0 | fwd | 1.65
13 | 13 | 256 | 50 | 256 | 1 | 1 | 0 | 0 | fwd | 1.78
14 | 14 | 512 | 16 | 48 | 3 | 3 | 1 | 1 | wrw | 1.08
224 | 224 | 3 | 1 | 64 | 1 | 1 | 0 | 0 | bwd | 1.19
13 | 13 | 256 | 256 | 256 | 1 | 1 | 0 | 0 | bwd | 1.90
13 | 13 | 384 | 128 | 256 | 1 | 1 | 0 | 0 | fwd | 1.26
13 | 13 | 384 | 50 | 384 | 3 | 3 | 1 | 1 | wrw | 1.72
112 | 112 | 64 | 1 | 128 | 1 | 1 | 0 | 0 | bwd | 1.20
28 | 28 | 192 | 16 | 32 | 1 | 1 | 0 | 0 | fwd | 1.46
56 | 56 | 64 | 32 | 64 | 1 | 1 | 0 | 0 | fwd | 1.52
56 | 56 | 64 | 32 | 64 | 1 | 1 | 0 | 0 | bwd | 1.52
112 | 112 | 64 | 2 | 128 | 1 | 1 | 0 | 0 | fwd | 1.25
56 | 56 | 64 | 16 | 64 | 1 | 1 | 0 | 0 | bwd | 1.44
56 | 56 | 64 | 16 | 64 | 1 | 1 | 0 | 0 | fwd | 1.43
13 | 13 | 256 | 256 | 256 | 3 | 3 | 1 | 1 | wrw | 2.06
13 | 13 | 256 | 50 | 256 | 3 | 3 | 1 | 1 | wrw | 2.14
13 | 13 | 192 | 50 | 384 | 3 | 3 | 1 | 1 | wrw | 2.13
13 | 13 | 256 | 128 | 256 | 3 | 3 | 1 | 1 | wrw | 2.15
13 | 13 | 256 | 64 | 256 | 3 | 3 | 1 | 1 | wrw | 2.15
112 | 112 | 64 | 2 | 128 | 1 | 1 | 0 | 0 | bwd | 1.24
13 | 13 | 192 | 64 | 384 | 3 | 3 | 1 | 1 | wrw | 2.17
13 | 13 | 192 | 128 | 384 | 3 | 3 | 1 | 1 | wrw | 2.16
480 | 48 | 1 | 16 | 16 | 1 | 1 | 0 | 0 | bwd | 1.37
13 | 13 | 192 | 256 | 384 | 3 | 3 | 1 | 1 | wrw | 2.14
112 | 112 | 64 | 1 | 128 | 1 | 1 | 0 | 0 | fwd | 1.19
56 | 56 | 64 | 8 | 64 | 1 | 1 | 0 | 0 | bwd | 1.17
28 | 28 | 192 | 16 | 32 | 1 | 1 | 0 | 0 | bwd | 1.14
7 | 7 | 832 | 16 | 128 | 1 | 1 | 0 | 0 | bwd | 1.04
224 | 224 | 3 | 16 | 64 | 1 | 1 | 0 | 0 | fwd | 1.10
224 | 224 | 3 | 8 | 64 | 1 | 1 | 0 | 0 | fwd | 1.08
480 | 48 | 1 | 16 | 16 | 1 | 1 | 0 | 0 | fwd | 1.04

</p>
</details>

## Metrics
Average gain = (sum speedup) / (num cases). num_cases = 500.
Total time gain = sum(time without f3x2) / sum(time with f3x2)

  | Average gain | Total time gain
-- | -- | --
  | gfx906 | Navi21 | gfx906 | Navi21
Fwd | 1.12 | 1.13 | 1.26 | 1.09
Bwd | 1.24 | 1.24 | 1.31 | 1.23
Wrw | 1.14 | 1.18 | 1.21 | 1.08

### CODE REVIEW

**Comment by atamazov** [comment]
@Slimakanzer Which MIOPEN_FIND_MODE was used for performance testing?

Does this FP16 kernel uses FP32 math internally for computations?

**Comment by Slimakanzer** [comment]
@atamazov For performance tests i used:
* MIOPEN_FIND_MODE=NORMAL
* f4e283d (`winograd-f3x2-fp16`) vs baseline f525e8453 (`develop`)


FP16 kernels use FP16 for _input_, _filter_, _bias_ and _output_ data. Packed FP16 math instructions are used for computations.
However Winograd **output transform** occurs in FP32.

**Comment by Slimakanzer** [comment]
@atamazov added metrics to better understand performance improvements

**Comment by atamazov** [comment]
@Slimakanzer 
> This kernel uses FP32 accumulators and dot2 instructions, so yes, internally FP32 math is used for the computations.

Well, AFAIK the kernel uses FP32 internally everywhere except input transform, **_which employs FP16_**. But this should not lead to precision issues (like network convergency problems). Okay.

**Comment by atamazov** [comment]
"Metrics" updated in the PR description. 

Numbers look impressive!!!

**Review by atamazov — APPROVED** [review]
LGTM!

**Pull request merged**
