### PR TITLE
Add MIOPEN_REDUCE_TENSOR_MUL to generic-reduction testing

### PR DESCRIPTION
**Pull request by fronteer**
Add MIOPEN_REDUCE_TENSOR_MUL to generic-reduction testing

Solved the issue that it is easy to produce "all-zero" result or large error while testing MIOPEN_REDUCE_TENSOR_MUL by having the input data for "MUL" specially constructed.

### CODE REVIEW

**Comment by atamazov** [comment]
Please open new branch. Do not re-use existing one.

**Comment by atamazov** [comment]
@fronteer I can help you with moving changes from here to another branch, if necessary.

**Comment by fronteer** [comment]
> Please open new branch. Do not re-use existing one.
I will open new branch

**Comment by atamazov** [comment]
@fronteer  Thank you!

**Pull request closed without merging**
