### PR TITLE
Default config from GetPerfCfgParams

### PR DESCRIPTION
**Pull request by cderb**
Return default parameters when no db entry from GetPerfCfgParams.

### CODE REVIEW

**Comment by junliume** [comment]
@cderb could you recommend the urgency level?

**Review by junliume — APPROVED** [review]

**Comment by cderb** [comment]
@junliume any blockers on this one? This solves a bug with our tuning db record-keeping.

**Review by atamazov — DISMISSED** [review]
[Notice] Again, this functionality duplicates the logic implemented in other place. And it is used only in fin. Thus, this PR increases the technical debt. The fin related stuff need deep refactoring.

No objections.

**Review by atamazov — APPROVED** [review]
No objections for this PR

**Comment by cderb** [comment]
@junliume reminder that this exists.

**Review by junliume — APPROVED** [review]

**Pull request merged**
