### PR TITLE
[CI][Tests] Workaround #1516 by disable legacy CK kernel test

### PR DESCRIPTION
**Pull request by junliume**
test passed on local Navi21 with ROCm 5.1.0 installed as both base and docker

### CODE REVIEW

**Review by atamazov — CHANGES_REQUESTED** [review]
I recommend re-implementing this so the test is automatically enabled with 5.1. In addition, I recommend disabling iGemm V6R1 until 5.1 as well. Detailed suggestions will follow soon.

**Comment by atamazov** [comment]
> I recommend re-implementing this so the test is automatically enabled with 5.1.

In test/cmakelists.txt, near line 177:
```C++
set_var_to_condition(WORKAROUND_ISSUE_1516_DEFAULT ${MIOPEN_TEST_GFX1030} AND (${MIOPEN_hip_VERSION_FLAT} GREATER 500100000))
option( WORKAROUND_ISSUE_1516 "" ${WORKAROUND_ISSUE_1516_DEFAULT})
```
In add_custom_test():
```C++
    if(WORKAROUND_ISSUE_1516
        AND (${NAME} MATCHES "test_conv_ck_igemm_fwd_v6r1_dlops_nchw" ))
        set_tests_properties(${NAME} PROPERTIES DISABLED On)
    endif()
```

**Comment by atamazov** [comment]
>  I recommend disabling iGemm V6R1 until 5.1 as well

In conv_ck_igemm_fwd_v6r1_dlops_nchw.cpp:
```C++
#include <config.h>
.
.
#define WORKAROUND_ISSUE_1516 (HIP_PACKAGE_VERSION_FLAT < 5001000000)
.
.
bool ConvCkIgemmFwdV6r1DlopsNchw::IsApplicable(const ConvolutionContext& ctx) const
{
#if WORKAROUND_ISSUE_1516
    if(!miopen::IsEnabled(MIOPEN_DEBUG_CONV_CK_IGEMM_FWD_V6R1_DLOPS_NCHW{}))
        return false;
#endif
    if(miopen::IsDisabled(MIOPEN_DEBUG_CONV_CK_IGEMM_FWD_V6R1_DLOPS_NCHW{}))
        return false;
.
.
```

**Comment by atamazov** [comment]
@junliume BTW do we know what is the faulty component? For example, is issue reproducible with 5.0 base driver and ROCm 5.1?

**Comment by junliume** [comment]
> @junliume BTW do we know what is the faulty component? For example, is issue reproducible with 5.0 base driver and ROCm 5.1?

@atamazov  thanks for the suggestions! The current issue is that `test_conv_ck_igemm_fwd_v6r1_dlops_nchw` fails randomly in CI (CI nodes have ROCm 5.0.2 installed as base OS and ROCm 5.1 in dockerfile); while I cannot reproduce it with another standalone dev machine (ROCM 5.1.0 installed as both base OS and docker). 

#1516 shows that we plan to "fix" it by CK integration which will happen with #1524. I think maybe I should put this PR on HOLD until CK tells us whether this test should be kept active. Thanks!

**Comment by aska-0096** [comment]
Hi @junliume , has encountered this problem twice during the PR1572 CI.
http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/issue_1569__driver_support_int8conv/3/pipeline

**Pull request closed without merging**
