### PR TITLE
Revert "[Windows] use find_package() for Eigen and frugally-deep (#2574)"

### PR DESCRIPTION
**Pull request by junliume**
This reverts commit 4150134faaf9ad095a4d5d1aadb3a61cf29bb7b0.

Issue described at https://github.com/ROCm/MIOpen/issues/2607

We can work on #2574 later but now I need to unblock local dev

### CODE REVIEW

**Comment by apwojcik** [comment]
The issue is not caused by the ROCm 5.7.0 but by the CMake version installed in the docker. The command `find_package(... GLOBAL)` requires CMake version >= 3.24

**Review by apwojcik — CHANGES_REQUESTED** [review]
Can we test #2610 before reverting #2574 with this PR

**Comment by apwojcik** [comment]
The issue is not caused by the ROCm 5.7.0 but by the CMake version installed in the docker. The command `find_package(... GLOBAL)` requires CMake version >= 3.24

**Comment by atamazov** [comment]
@apwojcik I will test #2610

**Comment by junliume** [comment]
Unnecessary with #2610

**Pull request closed without merging**
