### PR TITLE
[NFC] Batchnorm second forward solver

### PR DESCRIPTION
**Pull request by DrizztDoUrden**
The first forward solver for batchnorm.
Perf/correctness tests complete. No non-marginal perf difference was found on my bench, as well as no difference in OCL build parameters.

### CODE REVIEW

**Comment by DrizztDoUrden** [comment]
@muralinr Would you like me to run the same bench you have suggested for the previous PR?

**Comment by muralinr** [comment]
> @muralinr Would you like me to run the same bench you have suggested for the previous PR?

yes, Can you please run same benchmark 

> @muralinr Would you like me to run the same bench you have suggested for the previous PR?

yes, Can you please run same beanchmark tests?

**Comment by DrizztDoUrden** [comment]
sure

**Comment by junliume** [comment]
CI is still blocked by some tidy issues, maybe the following?

> [2021-08-21T15:27:15.025Z] /home/jenkins/workspace/bs_MIOpen_ddu_bnorm-fwd-solver-1/src/ocl/batchnormocl.cpp:207:21: warning: The scope of the variable 'xlocalsize' can be reduced. [variableScope]
[2021-08-21T15:27:15.025Z]         std::size_t xlocalsize = 1;

**Review by muralinr — COMMENTED** [review]
Changes look good to me.  Can you please run benchmark tests for configs provided earlier by me and comment on test results?

**Comment by DrizztDoUrden** [comment]
@muralinr No non-marginal perf difference in your bench too.

**Review by muralinr — DISMISSED** [review]
I approve this PR as benchmark tests are good.

**Pull request merged**
