### PR TITLE
[TESTS] Encapsulate Jenkins runDockerJob

### PR DESCRIPTION
**Pull request by ce1adon**
This PR is a pre-requisite of miopen-tensile opencl backend project.
This project requests check in of new test stages, while Jenkinsfile is at the edge of legal upper limit. This PR puts repeatedly used steps into methods outside of the pipeline to reduce the size of the file. This PR will save some space for adding opencl tests for tensile.

### CODE REVIEW

**Comment by ce1adon** [comment]
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/develop/Jenkinsfile#L236-L245
All the three stages in "Static checks" haven't included the reboot cmd. Do we want to expand code with the reboot function as other stages, or just leave them here? @atamazov @pfultz2

**Comment by atamazov** [comment]
> All the three stages in "Static checks" haven't included the reboot cmd. Do we want to expand code with the reboot function as other stages, or just leave them here? @atamazov @pfultz2

Reboot is not required for stages running on "nogpu" nodes.

**Comment by atamazov** [comment]
@shurale-nkn Could you please review this?

**Comment by shurale-nkn** [comment]
> @shurale-nkn Could you please review this?

This was already done in #147. It is waiting for the blocker issues to be resolved.

**Comment by ce1adon** [comment]
> > @shurale-nkn Could you please review this?
> 
> This was already done in #147. It is waiting for the blocker issues to be resolved.

The purpose of jenkinsfile modification in PR #147 is quite different from this PR, and it introduces major modifications to jenkinsfile, which I'm not sure is still applicable to current develop branch.

**Comment by shurale-nkn** [comment]
> The purpose of jenkinsfile modification in PR #147 is quite different from this PR, and it introduces major modifications to jenkinsfile, which I'm not sure is still applicable to current develop branch.

Which modifications??

**Comment by shurale-nkn** [comment]
> Jenkins file is at the edge of legal upper limit. This PR encapsulates repeatedly used lines to reduce the size of the file. This PR will save some space for adding opencl tests for tensile.

What is the "legal upper limit" ?

**Comment by ce1adon** [comment]
> > The purpose of jenkinsfile modification in PR #147 is quite different from this PR, and it introduces major modifications to jenkinsfile, which I'm not sure is still applicable to current develop branch.
> 
> Which modifications??

1105 lines of changes were present in #147 's Jenkinsfile

**Comment by ce1adon** [comment]
> > Jenkins file is at the edge of legal upper limit. This PR encapsulates repeatedly used lines to reduce the size of the file. This PR will save some space for adding opencl tests for tensile.
> 
> What is the "legal upper limit" ?

"General error during class generation: Method code too large!"

Details can be check here:
http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/tensile-ocl/1/pipeline

**Comment by ce1adon** [comment]
> > > Jenkins file is at the edge of legal upper limit. This PR encapsulates repeatedly used lines to reduce the size of the file. This PR will save some space for adding opencl tests for tensile.
> > 
> > 
> > What is the "legal upper limit" ?
> 
> "General error during class generation: Method code too large!"
> 
> Details can be check here:
> http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/tensile-ocl/1/pipeline

I encountered the same issue when check in #556 . That was the reason I defined tensileStage().

**Comment by junliume** [comment]
> > Jenkins file is at the edge of legal upper limit. This PR encapsulates repeatedly used lines to reduce the size of the file. This PR will save some space for adding opencl tests for tensile.
> 
> What is the "legal upper limit" ?

Found some info online: https://support.cloudbees.com/hc/en-us/articles/360039361371-Method-Code-Too-Large-Error

> 
> The limit for Jenkins pipeline objects is 64kiByte.
https://docs.oracle.com/javase/specs/jvms/se7/html/jvms-4.html#jvms-4.9.1

> See also for the problem and for solution details:
https://code-held.com/2019/05/02/jenkins-pipeline-method-too-large/

**Comment by shurale-nkn** [comment]
> > > The purpose of jenkinsfile modification in PR #147 is quite different from this PR, and it introduces major modifications to jenkinsfile, which I'm not sure is still applicable to current develop branch.
> > 
> > 
> > Which modifications??
> 
> 1105 lines of changes were present in #147 's Jenkinsfile

And? What is a point?
As i see in 'tensile-ocl' was increased size of~43 lines but changes in this lines was not necessary, because not used. 

Current pr contains 400 changed line at this moment.  This will create a bunch of merge conflicts.

**Comment by shurale-nkn** [comment]
Please do your required changes in 'tensile-ocl' branch to pass tests  and create ticket with feature request for this problem.
And i will solve it without merge conflicts.

**Comment by ce1adon** [comment]
> And? What is a point?

The point is the Jenkinsfile needs modification to include test for miopen-tensile opencl backend.

> As i see in 'tensile-ocl' was increased size of~43 lines but changes in this lines was not necessary, because not used.

What do you mean "changes in this lines was not necessary, because not used"? As I mentioned the purpose of this PR is to encapsulate partial jenkins code to reduce redundancy for jenkinsfile. All the changes here are necessary.

> Current pr contains 400 changed line at this moment. This will create a bunch of merge conflicts.

What merge conflicts? If you are talking about PR #147 , I don't think it will be merged since Daniel mentioned that PR is used as an extra test for configs not included in regular CI tests.

**Comment by ce1adon** [comment]
> Please do your required changes in 'tensile-ocl' branch to pass tests and create ticket with feature request for this problem.
> And i will solve it without merge conflicts.

This PR is the pre-requisite of following changes, NOT vice-versa. Let's focus on judge the logic correctness of this PR.

**Comment by shurale-nkn** [comment]
> > And? What is a point?
> 
> The point is the Jenkinsfile needs modification to include test for miopen-tensile opencl backend.
> 
What is a point for this fact?
>1105 lines of changes were present in #147 's Jenkinsfile

How count of changed lines correlated with "changes applicability to current develop branch"


> > As i see in 'tensile-ocl' was increased size of~43 lines but changes in this lines was not necessary, because not used.
> 
> What do you mean "changes in this lines was not necessary, because not used"? As I mentioned the purpose of this PR is to encapsulate partial jenkins code to reduce redundancy for jenkinsfile. All the changes here are necessary.
> 

Changes in 'tensile-ocl' branch.
It contains 
`tensileStage('/opt/rocm/llvm/bin/clang++', cmd: cmd, gpu_arch: "gfx906:xnack-", miotensile_version: "latest", target_id: "ON")`
instead of this
`tensileStage(cmd, "gfx908:xnack-", "latest", "ON")`
At first was increased the size of the function, and now trying to get it smaller.....

> > Current pr contains 400 changed line at this moment. This will create a bunch of merge conflicts.
> 
> What merge conflicts? If you are talking about PR #147 , I don't think it will be merged since Daniel mentioned that PR is used as an extra test for configs not included in regular CI tests.

Thank you, we have a different opinion.. It will be merged.

**Comment by ce1adon** [comment]
> What is a point for this fact?

Please review the PR info for the purpose of this PR. Let's not keep repeating the same info as our Jenkinsfile does :)

> How count of changed lines correlated with "changes applicability to current develop branch"

I just want to let you know #147 made a major modification to Jenkinsfile, while most of the changes are made within function rather than encapsulating it. I don't think #147 will help with the implementation of miopen-tensile ocl backend.

> Changes in 'tensile-ocl' branch.
> It contains
> `tensileStage('/opt/rocm/llvm/bin/clang++', cmd: cmd, gpu_arch: "gfx906:xnack-", miotensile_version: "latest", target_id: "ON")`
> instead of this
> `tensileStage(cmd, "gfx908:xnack-", "latest", "ON")`
> At first was increased the size of the function, and now trying to get it smaller.....

tensileStage() was the encapsulating function I built last time, as I mentioned in previous comments. It's not enough for current implementation any more, and that's the reason I created this PR.

> Thank you, we have a different opinion.. It will be merged.

I'm sure you can achieve it. Good luck!
But meanwhile we have a time pressure to implement miopen-tensile ocl here. Please review the functionality of this PR as a pre-requisite of miopen-tensile ocl program.

**Comment by atamazov** [comment]
@ce1adon @shurale-nkn @junliume Interesting discussion :face_with_head_bandage: 

Let me try to summarize the current situation (please correct me if I am wrong):

- (A) Jing hit the https://issues.jenkins.io/browse/JENKINS-37984 issue in the `tensile-ocl` branch and needs to resolve it ASAP in order to continue very important work.
- (B) Kamil is worrying about upcoming merge conflicts with this long-awaited PR #147 intended for improving the quality of testing.
- (C) From my point of view, there is another problem. If we have PR that changes `Jenkinsfile` then CI testing can't prove that the PR is valid. Therefore both coding and reviewing of `Jenkinsfile` require a lot of attention and caution. For this PR we need to prove that this change is truly NFC, i.e. does not change the testing process. But that would take time, and this conflicts with (A).

In order to resolve the above problems I propose the following:
- (1) Jing removes some stages from `tensile-ocl` to save space in the groovy method (e.g. packaging, mlir, full tests) in a separate commit. Then she continue development/testing without any problem. This partially resolves (A). And now we have time for (C).
- (2) Kamil extracts the changes that is functionally identical to this PR from his #147, and makes a new PR out of that changes ASAP. This resolves (B).
- (3) Kamil or I will provide testing of the new PR to guarantee it is NFC. This resolves (C).
- (4) After merging of the new PR, Kamil or I will provide Jing with a `tensile-ocl-jenkinsfile` branch. The branch will be based on `tensile-ocl` and intended for merging into it. Merging it into `tensile-ocl` will correctly resolve any merge conflicts of `Jenkinsfile` in `tensile-ocl` and `develop`. This would finally resolve (A).

This should satisfy everyone. Thoughts?

**Comment by ce1adon** [comment]
Thanks for summarizing Artem!

> * (A) Jing hit the https://issues.jenkins.io/browse/JENKINS-37984 issue in the `tensile-ocl` branch and needs to resolve it ASAP in order to continue very important work.

Yes.
And by the way, this exact issue, as I mentioned above, was already occurred when check in #556 . And I create tensileStage() to solve it then. The only different between this time and last time is that I extract the changes into a separated PR for better CI experience since it needs to change Jenkinsfile.

> * (B) Kamil is worrying about upcoming merge conflicts with this long-awaited PR #147 intended for improving the quality of testing.

I didn't know there is a plan to merge #147 . But all merging introduce some conflicts. That's why we coordinate, and that's why I separate this PR instead of secretly shipping it through tensile-ocl branch. 

> * (C) From my point of view, there is another problem. If we have PR that changes `Jenkinsfile` then CI testing can't prove that the PR is valid. Therefore both coding and reviewing of `Jenkinsfile` require a lot of attention and caution. For this PR we need to prove that this change is truly NFC, i.e. does not change the testing process. But that would take time, and this conflicts with (A).

Yes, I understand the risk to change Jenkinsfile, so I take cautious and invited you folks to review.

> * (1) Jing removes some stages from `tensile-ocl` to save space in the groovy method (e.g. packaging, mlir, full tests) in a separate commit. Then she continue development/testing without any problem. This partially resolves (A). And now we have time for (C).

Unfortunately the check-in in tensile-ocl is the minimum checkout, two stages only, if you have a chance to review it. Removing stages basically means no tests adding for tensile ocl.

> * (2) Kamil extracts the changes that is functionally identical to this PR from his #147, and makes a new PR out of that changes ASAP. This resolves (B).

I merged this PR into tensile-ocl and it's building fine right now. I don't see the need to extract changes for a new PR.

> * (3) Kamil or I will provide testing of the new PR to guarantee it is NFC. This resolves (C).

Ditto. I don't see why testing and reviewing cannot be performed on this PR, while the changes are quite straightforward.

> * (4) After merging of the new PR, Kamil or I will provide Jing with a `tensile-ocl-jenkinsfile` branch. The branch will be based on `tensile-ocl` and intended for merging into it. Merging it into `tensile-ocl` will correctly resolve any merge conflicts of `Jenkinsfile` in `tensile-ocl` and `develop`. This would finally resolve (A).

Ditto. If you take a look of this PR, the changes are quite straightforward.

**Comment by atamazov** [comment]
@ce1adon 
>  mentioned above, was already occurred when check in #556

Yep, I am aware of that problem, I've even seen that myself.

> But all merging introduce some conflicts. 

Often, yes, but not always. BTW my proposal contains a bonus: we'll resolve all merge conflicts in Jenkinsfile for you ;)

> Unfortunately the check-in in tensile-ocl is the minimum checkout, two stages only, if you have a chance to review it. Removing stages basically means no tests adding for tensile ocl.

Well, that idea is that you ___keep all the new stages___ (the ones you need for tensile-ocl) but _remove some other stages irrelevant_ for tensile-ocl, e.g. Full Tests, Packaging, MLIR Smoke tests.

> I merged this PR into tensile-ocl and it's building fine right now. I don't see the need to extract changes for a new PR.
> ... I don't see why testing and reviewing cannot be performed on this PR, while the changes are quite straightforward.
> ... If you take a look of this PR, the changes are quite straightforward.

I am foreseeing that moving this way will take more time for all of us, but no problem, the decision is yours. Just confirm that you would like to continue with this PR, and I will begin the process of reviewing.

**Comment by ce1adon** [comment]
> > Unfortunately the check-in in tensile-ocl is the minimum checkout, two stages only, if you have a chance to review it. Removing stages basically means no tests adding for tensile ocl.
> 
> Well, that idea is that you _**keep all the new stages**_ (the ones you need for tensile-ocl) but _remove some other stages irrelevant_ for tensile-ocl, e.g. Full Tests, Packaging, MLIR Smoke tests.

Looks like this is the root of the misunderstanding.
The branch tensile-ocl is not going to be used as a temporary test branch for tensile as I mentioned two months ago. It is a new feature, miopen-tensile with opencl backend. It is expected to be check in permanently, with the new CI tests. No existing stage will have to be removed due to this new feature.

**Comment by atamazov** [comment]
@ce1adon 
> Looks like this is the root of the misunderstanding.
> The branch tensile-ocl is not going to be used as a temporary test branch for tensile as I mentioned two months ago. It is a new feature, miopen-tensile with opencl backend. It is expected to be check in permanently, with the new CI tests. No existing stage will have to be removed due to this new feature.

Of course, I know that. The bullet (4) in my proposal is intended to return the `tenslie-ocl` branch back to the mergeable state. We will return back stages removed at step (1) and resolve other merge conflicts.

**Comment by ce1adon** [comment]
> Of course, I know that. The bullet (4) in my proposal is intended to return the `tenslie-ocl` branch back to the mergeable state. We will return back stages removed at step (1) and resolve other merge conflicts.

Looks like we are on the same page about the background of this PR. I appreciate all the fantastic idea about modify Jenkinsfile and I'm sure we will achieve them in future. 
Now let's review this PR with the focus on its functionality: Does the encapsulating provide the same functionality as previous code, and meanwhile reducing redundancy in some degree?

**Comment by atamazov** [comment]
As you wish.

**Comment by atamazov** [comment]
@ce1adon Please share with me the results of testing of this PR, if you have any. Otherwise I'll need to test this myself. No problem, but that would take some time.

**Comment by ce1adon** [comment]
> @ce1adon Please share with me the results of testing of this PR, if you have any. Otherwise I'll need to test this myself. No problem, but that would take some time.

Please find it here:
http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/jenkins-run-encapsulate/6/pipeline

**Comment by atamazov** [comment]
@ce1adon Thanks, but even if all CI tests are passed, this does not mean that Jenkinsfile changes are correct.

**Comment by atamazov** [comment]
Complexity of testing is high.

**Comment by ce1adon** [comment]
> @ce1adon Thanks, but even if all CI tests are passed, this does not mean that Jenkinsfile changes are correct.

I didn’t know there are bonus tests when Jenkinsfile gets changed. Can you show me more details? Can you also document these tests so everyone can make use of them?

**Comment by ce1adon** [comment]
> Complexity of testing is high.

Please explain how encapsulate a few repeating lines of code is complex.

**Comment by atamazov** [comment]
@ce1adon 
> > Complexity of testing is high.
> 
> Please explain how encapsulate a few repeating lines of code is complex.

"Encapsulating multiple duplicate lines" is easy to do, but it's not a testing but implemening. It is also easy to look at "Encapsulating multiple repeating lines" with your eyes, but this is also not testing but reviewing.

But please do not worry, I will test as soon I have time. I do not know exactly how, but I will invent something.

**Review by atamazov — APPROVED** [review]
Looks good, tested manually.

**Comment by atamazov** [comment]
> > Complexity of testing is high.
> 
> Please explain how encapsulate a few repeating lines of code is complex.

No consensus on complexity & urgency.

**Review by junliume — APPROVED** [review]

**Pull request merged**
