### PR TITLE
[NFC] Use conv::ProblemDescription for SQLitePerfDb

### PR DESCRIPTION
**Pull request by averinevg**
* Replace `ProblemDescriptionCompatTemporary` with `conv::ProblemDescription` for `SQLitePerfDb`
* Remove unused code

### CODE REVIEW

**Comment by averinevg** [comment]
@atamazov Please review

**Comment by atamazov** [comment]
@averinevg Any doubts from your side? Would you like me to do performance testing of this PR?

**Comment by averinevg** [comment]
> @averinevg Any doubts from your side? Would you like me to do performance testing of this PR?

@atamazov No, I don't think it is necessary to run performance tests.

**Review by DrizztDoUrden — APPROVED** [review]
LGTM

**Review by junliume — APPROVED** [review]

**Pull request merged**
