### PR TITLE
Use git status wrapper for jenkins

### PR DESCRIPTION
**Pull request by pfultz2**
This gives us more control on how git commit statuses are updated.

### CODE REVIEW

**Comment by atamazov** [comment]
Wow. Does it use https://github.com/jenkinsci/pipeline-gitstatuswrapper-plugin?

**Comment by pfultz2** [comment]
> Wow. Does it use https://github.com/jenkinsci/pipeline-gitstatuswrapper-plugin?

Yes, and as you can see below the status such as `Jenkins - ${stage}` are green while the others are pending. After we merge this in, we can disable the other statuses on jenkins.

**Review by atamazov — APPROVED** [review]

**Comment by pfultz2** [comment]
@daniellowell Can this be merged?

**Comment by pfultz2** [comment]
I am going to remove the old status today from jenkins. Merge in this PR to get commit statuses.

**Pull request merged**
