### PR TITLE
[NFC] Move convolution solvers to solver/conv directory (part 1)

### PR DESCRIPTION
**Pull request by averinevg**
Move convolution solvers to `solver/conv` directory (part 1)

### CODE REVIEW

**Comment by averinevg** [comment]
@atamazov Please review

**Review by atamazov — APPROVED** [review]
🟢 LGTM!

Please rename PR -- remove "ASM, OpenCL and MLIR" from title.

**Review by junliume — APPROVED** [review]
Only concern is about conflicts with other WIP PRs, let me check before merging.

**Comment by averinevg** [comment]
@junliume I suggest first merging other pull requests that contain changes in solvers, after that I’ll just do a rebase. I could help with the review of those pull requests, just add me to the reviewers.

**Pull request merged**
