### PR TITLE
[HotFix] Fix DB install after #2347

### PR DESCRIPTION
**Pull request by junliume**
#2701

Reason for Draft: need to take care of embedded DB case

### CODE REVIEW

**Review by apwojcik — APPROVED** [review]
Thanks for catching this up and for the fix!

**Comment by junliume** [comment]
@apwojcik @JehandadKhan this is not completely fixed yet. If one issues: `make MIOpenDriver` then the DB targets will not be made automatically. They are made only when default `all` is made.

**Comment by JehandadKhan** [comment]
@apwojcik Can you please update this branch so that the db targets are added as dependencies to the `MIOpen` target.

**Comment by junliume** [comment]
@apwojcik there is another issue on `LFS_MISSING_FILES` from
https://github.com/ROCm/MIOpen/blob/06b2bd395f2629b1542d5b2a5d234195f9b41bb8/CMakeLists.txt#L515

This variable gets cleared from scratch every time the function `install_kdb` is called. I guess we need to make it a global variable somehow?

same issue has been discussed here: https://stackoverflow.com/questions/10031953/how-to-set-the-global-variable-in-a-function-for-cmake

**Comment by apwojcik** [comment]
> This variable gets cleared from scratch every time the function `install_kdb` is called. I guess we need to make it a global variable somehow?

@junliume Can you elaborate more on why it is an issue here? I would like to understand the context.

**Comment by apwojcik** [comment]
> @apwojcik @JehandadKhan this is not completely fixed yet. If one issues: `make MIOpenDriver` then the DB targets will not be made automatically. They are made only when default `all` is made.

@junliume @JehandadKhan It is done

**Comment by junliume** [comment]
> > This variable gets cleared from scratch every time the function `install_kdb` is called. I guess we need to make it a global variable somehow?
> 
> @junliume Can you elaborate more on why it is an issue here? I would like to understand the context.

@apwojcik the issue is described in more details here: https://github.com/ROCm/MIOpen/issues/2709

**Pull request merged**
