### PR TITLE
Solver keyed FDB

### PR DESCRIPTION
**Pull request by cderb**
Implementation of #1987 
FDB format
```
solver:sover,kernel_time,workspace_size,algorithm,network_config
```

### CODE REVIEW

**Comment by cderb** [comment]
Set as draft until find dbs are formatted.

**Comment by DrizztDoUrden** [comment]
I don't see any immediate issues if this does not make immediate mode inoperable. That has to be tested, but looks like it would either work or not, so should not be complicated.

**Comment by atamazov** [comment]
I am working on this.

**Comment by atamazov** [comment]
@cderb Now this can be closed.

**Comment by atamazov** [comment]
Let's close this.

**Pull request closed without merging**
