### PR TITLE
Deprecate `clang-ocl` and replace with `clang`

### PR DESCRIPTION
**Pull request by JehandadKhan**
On the HIP backend MIOpen uses `clang-ocl` which is being deprecated. This PR replaces the use of `clang-ocl` with `clang` to compile OpenCL kernels on the HIP backend.

### CODE REVIEW

**Comment by JehandadKhan** [comment]
FYI: @atamazov

**Comment by junliume** [comment]
@JehandadKhan could you attach the perf benchmark report to the JIRA ticket?

**Comment by junliume** [comment]
> @JehandadKhan could you attach the perf benchmark report to the JIRA ticket?

The point is either compiler should support clang-ocl, or there should be no performance regressions using clang instead. As we recall the later was not the case unfortunately. We need to keep track of that.

**Comment by atamazov** [comment]
@JehandadKhan It seems more important than #1626. I just want to prioritize my activities, please confirm, thanks!

**Comment by junliume** [comment]
> @JehandadKhan It seems more important than #1626. I just want to prioritize my activities, please confirm, thanks!

We are requesting staging tests on this branch to verify if this is a drop-in replacement. So far I doubt so since we've already seen some perf variations.

**Comment by junliume** [comment]
Convert to draft? @JehandadKhan

**Comment by JehandadKhan** [comment]
@junliume Done, can we decide what is our way forward ?

**Comment by junliume** [comment]
This change is needed when the base CI docker image is updated to ROCm 5.2.3

**Review by junliume — APPROVED** [review]

**Comment by atamazov** [comment]
@junliume @JehandadKhan 👍 This is very good as it resolves OpenCL offline build issues.

Right now I am testing if OpenCL kernels built via offline compiler are slower (or faster) vs COMGR-built ones (gfx906/60, FP32 and FP16 convolutions).

**Comment by JehandadKhan** [comment]
> @junliume @JehandadKhan 👍 This is very good as it resolves OpenCL offline build issues.
> 
> Right now I am testing if OpenCL kernels built via offline compiler are slower (or faster) vs COMGR-built ones (gfx906/60, FP32 and FP16 convolutions).

Thanks @atamazov. I suspect there are some issues, but I have not been able to confirm/deny them. If the args in MIOpen need to be changed, we can fix them in a subsequent PR.

**Comment by atamazov** [comment]
@junliume @JehandadKhan 🟡 Performance of FP32 OCL kernels built with offline compiler is within 5% in ~90% of configs. In other 10% (32 out of 279) of configs performance varies from 0.55 to 1.90 from original. On average, I see +2...4% performance gain (numbers vary depending on how you calculate the _average_).

🔴 With FP16 the results are similar, but worse. Regressions reach 0.15 (~6X drop) for several WrW configs, and overall performance diff on average is about of 5-20%, which requires investigation at least. The worst case:
```
./bin/MIOpenDriver convfp16 -x 10 -y 5 -W 341 -H 79 -c 32 -n 32 -k 32 -p 0 -q 0 -u 2 -v 2 -l 1 -j 1 -g 1 -F 4
```
Helper script to reproduce some of the regressed cases: [test-smoke-opencl-comgr-vs-offline-reproduce.sh.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/9569769/test-smoke-opencl-comgr-vs-offline-reproduce.sh.txt)

I am going to repeat testing with something never than 5.0. I would appreciate if someone would share the latest 5.x RC docker with me.

**Comment by junliume** [comment]
> @junliume @JehandadKhan 🟡 Performance of FP32 OCL kernels built with offline compiler is within 5% in ~90% of configs. In other 10% (32 out of 279) of configs performance varies from 0.55 to 1.90 from original. On average, I see +2...4% performance gain (numbers vary depending on how you calculate the _average_).
> 
> 🔴 With FP16 the results are similar, but worse. Regressions reach 0.15 (~6X drop) for several WrW configs, and overall performance diff on average is about of 5-20%, which requires investigation at least. The worst case:
> 
> ```
> ./bin/MIOpenDriver convfp16 -x 10 -y 5 -W 341 -H 79 -c 32 -n 32 -k 32 -p 0 -q 0 -u 2 -v 2 -l 1 -j 1 -g 1 -F 4
> ```
> 
> Helper script to reproduce some of the regressed cases: [test-smoke-opencl-comgr-vs-offline-reproduce.sh.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/9569769/test-smoke-opencl-comgr-vs-offline-reproduce.sh.txt)
> 
> I am going to repeat testing with something never than 5.0. I would appreciate if someone would share the latest 5.x RC docker with me.

./bin/MIOpenDriver convfp16 -x 10 -y 5 -W 341 -H 79 -c 32 -n 32 -k 32 -p 0 -q 0 -u 2 -v 2 -l 1 -j 1 -g 1 -F 0 -V 1 -s 0 -w 2 -t 1 -i 6 -C /home/atamazov/dockerx/miopen-verify2 -F 4
MIOpen(HIP): Info [FindConvBwdWeightsAlgorithm] BWrW Chosen Algorithm: ConvOclBwdWrW2<2> , 1638400, 41.2808
GPU Kernel Time Backward Weights Conv. Elapsed: 6.110705 ms (average)
GPU Kernel Time Backward Weights Conv. Elapsed: 41.274544 ms (average)  **<== clang is this much worse than clang-ocl??**

**Comment by atamazov** [comment]
@junliume Than COMGR. clang-ocl is not working with my ROCm 5.0, maybe I need to install some specific version of clang-ocl?

**Comment by atamazov** [comment]
@junliume @JehandadKhan 
FP32 OCL kernels with ROCm 5.3.022305-mainline-10659:
- 93% configs are on par
- 7% configs show perf diff from -80% to +30%
- overall perf regression is 0...9% on average

FP16 OCL kernels with ROCm 5.3.022305-mainline-10659:
- 95% configs are on par
- 5% configs show perf diff from -80% to +24%
- overall perf regression is 2...9% on average

I am going to find and, if possible, fix the root reason.

**Comment by atamazov** [comment]
@junliume @JehandadKhan 🔴 It seems like we have a bug in the compiler that I am unable to work around.

I am going to prepare a reproducible bug report for the compiler team. More info tomorrow...

**Pull request merged**
