### PR TITLE
[Solvers] Single performance config for all ConvBiasActivAsm1x1U methods

### PR DESCRIPTION
**Pull request by averinevg**
- `GetSolution()` uses `PerformanceConfigConvBiasActivAsm1x1U`
- Solver is inherited from `ConvSolver`

Fixes https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1432

### CODE REVIEW

**Comment by averinevg** [comment]
@atamazov Could you take a look at this PR please?

**Comment by averinevg** [comment]
@atamazov Could you take a look at this PR please?

**Review by DrizztDoUrden — APPROVED** [review]
LGTM

**Comment by averinevg** [comment]
@junliume @JehandadKhan Could you take a look at this PR? Thanks.

**Comment by JehandadKhan** [comment]
@averinevg Would this change result in changed tuning parameters ?

**Comment by DrizztDoUrden** [comment]
Neither solver id, nor serialization are changed, so it shouldn't.

**Review by junliume — APPROVED** [review]

**Review by atamazov — COMMENTED** [review]
LGTM

**Pull request merged**
