### PR TITLE
[issue 1902] Correct NCHWc solver config validation check restrictions.

### PR DESCRIPTION
**Pull request by aska-0096**
As reported in #1902 , some cases failed due to incorrect restrictions.
This PR fixed it.

cc. @atamazov

### CODE REVIEW

**Comment by atamazov** [comment]
@averinevg Please review this.

@junliume Recommended labels: https://github.com/ROCmSoftwarePlatform/MIOpen/labels/correctness, https://github.com/ROCmSoftwarePlatform/MIOpen/labels/bug, https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_blocker (due to correctness issues).

**Review by atamazov — APPROVED** [review]
Tested & confirmed that this PR resolves issue #1902. Thanks!

**Comment by atamazov** [comment]
@JehandadKhan Can you please approve & merge this? Please note that this PR https://github.com/ROCmSoftwarePlatform/MIOpen/labels/IMPACTS_PERFORMANCE_DB wrt the `ConvAsmImplicitGemmGTCDynamicFwdDlopsNCHWC` solver.

/cc @cderb

**Comment by aska-0096** [comment]
Hi @junliume , could you please approve and merge this PR : )

**Review by junliume — APPROVED** [review]

**Pull request merged**
