### PR TITLE
[Navi21][COMGR][OpenCL] Disabled wavefrontsize=64 for OCL on COMGR path. [Quality] Fixed build warnings with ROCm mainline. [CK][NFC] Some simplification.

### PR DESCRIPTION
**Pull request by atamazov**
Some useful by-products of HIPRTC work.

- [Navi21][COMGR][OpenCL] Fixed: Disabled enforcing of wavefrontsize=64 for OCL on COMGR path
- Fixes some host code inaccuracies and build warnings with ROCm mainline
  - Resolves https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1322#issuecomment-1030451028
- Fixes some kernel build warnings for DEV builds with ROCm mainline
- [NFC][composable_kernel] Rework: constexpr -> typedef as the former is not necessary
- Fixed initialization in test/gpu_nchw_nhwc_transpose.cpp, gen_rand_integer()

### CODE REVIEW

**Comment by atamazov** [comment]
@averinevg Please review this, thanks.

**Review by junliume — APPROVED** [review]

**Comment by junliume** [comment]
Ping @JehandadKhan  @carlushuang  @shurale-nkn @averinevg for review.

**Comment by atamazov** [comment]
@carlushuang Yes, we need your blessing for https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1407/commits/d03c4090b0c951468a328b5128c886b48ddc4e28 ;)

**Review by JehandadKhan — APPROVED** [review]

**Comment by junliume** [comment]
> @carlushuang Yes, we need your blessing for [d03c409](https://github.com/ROCmSoftwarePlatform/MIOpen/commit/d03c4090b0c951468a328b5128c886b48ddc4e28) ;)

Ping @carlushuang for review :)

**Review by carlushuang — APPROVED** [review]
the change related to naive conv, transpose kernel, seems reasonable.

**Pull request merged**
