### PR TITLE
[NHWC][asm igemm][GFX90a] add support for several NHWC bwd ssd config, when k=4x, 2x

### PR DESCRIPTION
**Pull request by carlushuang**
this is the same as https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1114, but for gfx90a kernels

SSD test result is [gfx90a-ssd-log.txt](https://amdcloud-my.sharepoint.com/:t:/g/personal/carhuang_amd_com/ESKK-MlHRmZFtCMKN-g51RkBfS1lWuit3X_3p-4c4XsY2g?e=ZuVzLS)

### CODE REVIEW

**Review by atamazov — APPROVED** [review]
I do not see anything bad.

**Review by atamazov — CHANGES_REQUESTED** [review]
Oops, we need tests.

**Comment by carlushuang** [comment]
> Oops, we need tests.

Hi @atamazov , test is also added in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1114, that would also apply for gfx90a

**Comment by atamazov** [comment]
@carlushuang 
> Hi @atamazov , test is also added in #1114, that would also apply for gfx90a

Hmm... But if #1114 includes tests for features implemented in  **_this PR_**, then #1114 will never pass CI, right?

**Comment by carlushuang** [comment]
@atamazov #1114 didn't enable gfx90a, so that PR it self will be OK. Again, gfx90a kernel and the related ctest is enabled in https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1035, and that PR it self will be OK. So I may think the tip develop will fail on this test cases, after above PR is merged but this PR is not merged.

**Review by junliume — APPROVED** [review]

**Comment by junliume** [comment]
> Oops, we need tests.

@atamazov  could you re-review with the responses? Thanks!

**Pull request merged**
