### PR TITLE
Revert #1818 [MLIR] Tuning Update

### PR DESCRIPTION
**Pull request by cderb**
for tunings added in #1818
fambench and int8 tunings are still present

### CODE REVIEW

**Comment by atamazov** [comment]
@cderb Could you add the number of the original PR (which adds MLIR tuning that is being reverted here) in the title or description? This would make it easier to track changes. Thanks!

**Comment by junliume** [comment]
@cderb preliminary tests shows this PR has recovered perf regressions caused by #1818

**Review by junliume — APPROVED** [review]

**Comment by atamazov** [comment]
@cderb @JehandadKhan Like #1841 and #1862, this PR contains some "outdated" find-db updates for MI100/MI200 related to ConvBinWinogradRxSf2x3g1 and ConvBinWinogradRxSf2x3. 

```bash
$ for f in src/kernels/*.fdb.txt; do ls -l ${f} ; grep -E ".*-[FBW]_g[0-9]+=.*ConvBinWinogradRxSf2x3g1," ${f} | wc -l ; done
--- all show 0 ---
$ for f in src/kernels/*.fdb.txt; do ls -l ${f} ; grep -E ".*-[W]=.*ConvBinWinogradRxSf2x3g1," ${f} | wc -l ; done
-rw-r--r-- 1 atamazov 197121 60263713 Nov  8 18:24 src/kernels/gfx90878.HIP.fdb.txt
7618
-rw-r--r-- 1 atamazov 197121 58208676 Nov  8 18:24 src/kernels/gfx90a68.HIP.fdb.txt
12079
-rw-r--r-- 1 atamazov 197121 58179416 Nov  8 18:24 src/kernels/gfx90a6e.HIP.fdb.txt
11961
$ for f in src/kernels/*.fdb.txt; do ls -l ${f} ; grep -E ".*-[FB]=.*ConvBinWinogradRxSf2x3," ${f} | wc -l ; done
-rw-r--r-- 1 atamazov 197121 60263713 Nov  8 18:24 src/kernels/gfx90878.HIP.fdb.txt
15063
-rw-r--r-- 1 atamazov 197121 58208676 Nov  8 18:24 src/kernels/gfx90a68.HIP.fdb.txt
1
-rw-r--r-- 1 atamazov 197121 58179416 Nov  8 18:24 src/kernels/gfx90a6e.HIP.fdb.txt
762
```
More info at https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1841#issuecomment-1307373707

I will provide the fix soon.

**Comment by JehandadKhan** [comment]
> I will provide the fix soon.

@atamazov  As I mentioned on your PR that such fixes made directly in Text files in MIOpen will be lost, therefore all changes to the Find Db in MIOpen need to come through Tuna so that they are permanent. Please coordinate with @cderb  on the rules for such changes so that a proper fix is made in our internal database.

**Comment by cderb** [comment]
@atamazov referring back to #1747.
This is the rename that needs to happen to regain performance? :

[find-db] Replaced ConvBinWinogradRxSf2x3 by ConvBinWinogradRxSf2x3g1 for non-group Fwd/Bwd (see https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1681)
[find-db] Replaced ConvBinWinogradRxSf2x3g1 by ConvBinWinogradRxSf2x3 for group WrW (see https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1735)

**Comment by atamazov** [comment]
@cderb 
### (1) Problem: Usage of ConvBinWinogradRxSf2x3 for non-group Fwd/Bwd

> [find-db] Replaced ConvBinWinogradRxSf2x3 by ConvBinWinogradRxSf2x3g1 for non-group Fwd/Bwd (see https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1681)

Yes, and I think this should happen automatically when regeneration of find-db is performed with MIOpen that includes #1747 (because after it ConvBinWinogradRxSf2x3 is not applicable for non-group Fwd/Bwd). Is my assumption correct?

If yes, then we need to understand why this happened with Tuna. I suspect the reason is that Tuna somehow uses data collected with the most recent MIOpen release, but this is only speculation.

For now, I will provide the hotfix.

### (2) Problem: Usage of ConvBinWinogradRxSf2x3g1 for group WrW

> [find-db] Replaced ConvBinWinogradRxSf2x3g1 by ConvBinWinogradRxSf2x3 for group WrW (see https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1735)

I do not see the above problem in the updated databases.

### (3) Problem: Usage of ConvBinWinogradRxSf2x3g1 for non-group WrW

This is low-priority, _questionable_ problem, and I see it in the updated find-dbs. The kernel developers are saying that tunable ConvBinWinogradRxSf2x3 should be more efficient than non-tunable "g1" solver for non-group WrW configs. Therefore ConvBinWinogradRxSf2x3g1 should not appear here.

The current understanding of the reason is that the system perf-db contains weird f2x3 tuning values for ConvBinWinogradRxSf2x3. Therefore its performance of the latter kernel is very low and "g1" kernel wins. It was confirmed by experiment with MI60. Quote from https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1747#issue-1370558240: 
> - Enabled ConvBinWinogradRxSf2x3g1 for WrW to avoid perf regressions due to weird f2x3 tuning values in the system perf-db (caught for MI60)
>   - Explanation and some discussion at https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1735/files#r968772575

I am not going to touch this. This problem should disappear after retuning the performance databases. Or maybe ConvBinWinogradRxSf2x3g1 is really more efficient than properly tuned ConvBinWinogradRxSf2x3 on some configs.

Hope this helps.

**Comment by atamazov** [comment]
@JehandadKhan 
> @atamazov As I mentioned on your PR that such fixes made directly in Text files in MIOpen will be lost, therefore all changes to the Find Db in MIOpen need to come through Tuna so that they are permanent.

This should not happen provided that my understanding of the tuning process matches the reality.

> Please coordinate with @cderb on the rules for such changes so that a proper fix is made in our internal database.

Of course. Note that I've asked to provide some more info about process some time ago (e.g. at https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1747#issuecomment-1246037559) but didn't get any feedback. No problem, but it seems it's time to clean up the situation ;)

**Pull request merged**
