### PR TITLE
[WIP] Enable vector load with padding > 1

### PR DESCRIPTION
**Pull request by zjing14**
- Enable vector load with padding > 1
- Support fp32 and fp16
- Improvement: `./bin/MIOpenDriver conv -F 1 -n 64 -c 64 -H 56 -W 56 -k 64 -y 7 -x 7 -p 3 -q 3 -u 1 -v 1 -l 1 -j 1 -g 1 -t 1` fp32 speedup: 1.16x; fp16 speedup: 1.09x

### CODE REVIEW

**Comment by TejashShah** [comment]
@zjing14 Since we don't have fp16 buffer load, would this experiment apply to fp16/bfp16?

**Comment by zjing14** [comment]
@TejashShah This relies on buffer_load, since buffer_load can set buffer range to avoid out-of-bound load.

**Comment by daniellowell** [comment]
@zjing14 add the string `[skip ci]` or `[ci skip]` to your commit comments so this WIP PR does not clutter our CI.

**Comment by zjing14** [comment]
@TejashShah I added explicit boundary check for fp16, improvement less than fp32 with buffer load.

**Pull request closed without merging**
