### PR TITLE
[tests] test_mdgraph: skip unsupported arch

### PR DESCRIPTION
**Pull request by zjing14**
- Add supported arch list for winograd and asm fusion algo, and skip unsupported arch

### CODE REVIEW

**Comment by zjing14** [comment]
@atamazov @JehandadKhan Please review the PR. It is urgent, needed by 03/29.

**Review by atamazov — COMMENTED** [review]
This looks good. But IIRC now we support Winograd on gfx10. I'll assign this to respective developer to add necessary changes.

**Comment by atamazov** [comment]
@Slimakanzer IIRC #809 enables 1x1 fused asm kernel for gfx90a. And #772 enables fused Winograd for gfx10. Please update tests as necessary and check locally. Thanks.

/cc @Kirpich30000

**Comment by atamazov** [comment]
#831 opened

**Review by atamazov — APPROVED** [review]
LGTM.

**Pull request merged**
