### PR TITLE
[Enhancement][Tests] GPU based verification for convolutions

### PR DESCRIPTION
**Pull request by JehandadKhan**
Prefer naive GPU kernels to verify convolution, fall back to CPU verification if the GPU kernel cannot be used.

cc @atamazov

### CODE REVIEW

**Comment by junliume** [comment]
@JehandadKhan  CI has some tidy issues. When I tried to test on a gfx908, I got the following error:
```
Consolidate compiler generated dependencies of target test_w_supertensor
[ 72%] Building CXX object test/CMakeFiles/test_w_supertensor.dir/w_supertensor.cpp.o
/root/MIOpen/test/w_supertensor.cpp:571:9: error: no matching member function for call to 'verify_equals'
        verify_equals(verify_w_tensor_set(rnnDesc,
        ^~~~~~~~~~~~~
/root/MIOpen/test/driver.hpp:881:10: note: candidate template ignored: substitution failure [with V = verify_w_tensor_set, Ts = <>]: no member named 'ref' in 'verify_w_tensor_set'
    auto verify_equals(V&& v, Ts&&... xs) -> decltype(std::make_pair(v.ref(xs...), v.gpu(xs...)))
         ^                                                             ~~~
/root/MIOpen/test/w_supertensor.cpp:582:9: error: no matching member function for call to 'verify_equals'
        verify_equals(verify_w_tensor_get(rnnDesc,
        ^~~~~~~~~~~~~
/root/MIOpen/test/driver.hpp:881:10: note: candidate template ignored: substitution failure [with V = verify_w_tensor_get, Ts = <>]: no member named 'ref' in 'verify_w_tensor_get'
    auto verify_equals(V&& v, Ts&&... xs) -> decltype(std::make_pair(v.ref(xs...), v.gpu(xs...)))
         ^

**Review by atamazov — APPROVED** [review]
This looks good!

**Comment by JehandadKhan** [comment]
@junliume CI passed once, in progress for the second time.

**Review by junliume — APPROVED** [review]

**Comment by atamazov** [comment]
> @junliume CI passed once, in progress for the second time.

Just curious, how big is the progress in CI testing time?

**Review by DrizztDoUrden — APPROVED** [review]
LGTM

**Comment by junliume** [comment]
> > @junliume CI passed once, in progress for the second time.
> 
> Just curious, how big is the progress in CI testing time?

It needs some time to accumulate quantifiable results, but I can surely see some stages got big improvements (now we only have 2 stages which last 1.5 hr but previously several last more than 2 hrs)

**Comment by JehandadKhan** [comment]
@junliume CI has passed

**Pull request merged**
