### PR TITLE
[HotFix] revert #2580 and re-enable smoke tests

### PR DESCRIPTION
**Pull request by junliume**
`Fp32 Hip Debug gfx908` and `Fp32 Hip Debug gfx90a` timeout after #2580

### CODE REVIEW

**Comment by junliume** [comment]
@atamazov FYI

**Review by shurale-nkn — APPROVED** [review]
LGTM

**Comment by junliume** [comment]
On hold and maybe replacable by #2599

**Comment by atamazov** [comment]
@junliume Good!

**Pull request merged**
