### PR TITLE
Feature jenkinsfile

### PR DESCRIPTION
**Pull request by okakarpa**
adding reboot functionality with [propagate: false] which would ignore the reboot error and move on to the next stage into the pipeline

### CODE REVIEW

**Comment by atamazov** [comment]
It seems like `reboot-slaves` is triggered even after successful builds. Is it expected?
image

**Comment by okakarpa** [comment]
> It seems like `reboot-slaves` is triggered even after successful builds. Is it expected?
> image

yes irrespective of the stage being a success or failed the reboot gets triggered

**Comment by daniellowell** [comment]
@atamazov Yes, reboot after any stage, regardless of success or failure.

**Comment by atamazov** [comment]
Okay.

**Comment by atamazov** [comment]
It passed CI tests. @daniellowell Please approve if it looks good to you.

**Review by atamazov — APPROVED** [review]

**Review by daniellowell — APPROVED** [review]

**Comment by atamazov** [comment]
I am terminating the CI job for this branch since it has been merged.

**Pull request merged**
