### PR TITLE
[CK] Fix Composable Kernel dependency building and Enable by default

### LINKED ISSUE #1733: [CK] Composable Kernel Integration Left-Over Issues
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/58d100984c807e425c6fe8e6d895d4bcc738196d/Dockerfile#L137

- **[Issue 1]**: *GoogleTest build to fail with ROCM 5.3 and latest HIP*

https://github.com/ROCmSoftwarePlatform/composable_kernel/blob/7589116121f80189f47cfd8692f300ee8c6377ad/cmake/googletest.cmake#L23
without this line CK build (actually GoogelTest) on most recent ROCm 5.3 will fail with:
```
MIOpen/build/composable_kernel-91d8b7d67ae9dbf8a6e691ea3e17c0b9705c6ba7/build/_deps/googletest-src/googletest/include/gtest/internal/gtest-internal.h:923:54: error: out-of-line definition of constexpr static data member is redundant in C++17 and is deprecated [-Werror,-Wdeprecated]
constexpr bool HasDebugStringAndShortDebugString<T>::value;
                                                     ^
1 error generated when compiling for gfx1030.
```
**Why are we pointing to this commit instead of others?**

- **[Issue 2]**: *How to build MIOpen without docker*
This is how I used to **install dependencies**
```
git clone -b develop https://github.com/ROCmSoftwarePlatform/MIOpen && cd MIOpen && \
mkdir -p install_dir && cmake -P install_deps.cmake --minimum --prefix /root/MIOpen/install_dir
```
 Now it is complaining about CK being missing:
```
[cmake] CMake Error at src/CMakeLists.txt:610 (add_library):
[cmake]   Target "MIOpen" links to target "composable_kernel::device_operations" but
[cmake]   the target was not found.  Perhaps a find_package() call is missing for an
[cmake]   IMPORTED target, or an ALIAS target is missing?
``` 
and I need to add:
 ```
wget -O ck.tar.gz https://www.github.com/rocmsoftwareplatform/composable_kernel/archive/91d8b7d67ae9dbf8a6e691ea3e17c0b9705c6ba7.tar.gz && \
    tar zxvf ck.tar.gz &&\
    cd composable_kernel-91d8b7d67ae9dbf8a6e691ea3e17c0b9705c6ba7 && \
    mkdir build && cd build && \
    CXX=/opt/rocm/bin/hipcc cmake -DCMAKE_CXX_COMPILER_LAUNCHER="${COMPILER_LAUNCHER}" -DCMAKE_PREFIX_PATH=/opt/rocm -D CMAKE_CXX_FLAGS=" --offload-arch=gfx900 --offload-arch=gfx906 --offload-arch=gfx908 --offload-arch=gfx90a --offload-arch=gfx1030 -O3 " .. && \
    make -j $(nproc) install
```
**Can we simply add another line to the following file?**
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/58d100984c807e425c6fe8e6d895d4bcc738196d/requirements.txt#L5

### PR DESCRIPTION
**Pull request by JehandadKhan**
Resolves #1733 (and #1706)

### CODE REVIEW

**Comment by atamazov** [comment]
@JehandadKhan Just in case -- am I correct that this PR resolves #1706 partially? 
- The 1st bullet: no fix for rbuild.ini
- The 3rd and the 4th bullets are not resolved.

**Review by atamazov — APPROVED** [review]
This looks good to me.

**Review by junliume — APPROVED** [review]

**Comment by atamazov** [comment]
@JehandadKhan Thanks, #1706 updated.

**Review by shurale-nkn — CHANGES_REQUESTED** [review]
cmake-data=3.15.1-0kitware1 should be deleted from dockerfile
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1692#discussion_r947292430

**Comment by JehandadKhan** [comment]
> cmake-data=3.15.1-0kitware1 should be deleted from dockerfile [#1692 (comment)](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1692#discussion_r947292430)

That changes does not relate to this PR

**Review by shurale-nkn — APPROVED** [review]
LGTM

**Review by junliume — APPROVED** [review]

**Pull request merged**
