### PR TITLE
gfx12 dev merge

### PR DESCRIPTION
**Pull request by cderb**

### CODE REVIEW

**Comment by averinevg** [comment]
@cderb Is this PR ready for review?

**Comment by cderb** [comment]
@averinevg PR is ready for review.

**Comment by junliume** [comment]
@cderb I think we should merge the public develop branch to NPI, and then try to merge back to public.
This PR contains a lot of changes which are unrelated to `gfx12`

**Review by averinevg — CHANGES_REQUESTED** [review]
@cderb Please remove all changes that are unrelated to gfx12

**Comment by cderb** [comment]
Removing additional changes from branch and opening in a separate PR.

**Pull request closed without merging**
