### PR TITLE
[tests] Add test for #1929

### PR DESCRIPTION
**Pull request by averinevg**
This PR adds test for #1929

### CODE REVIEW

**Comment by averinevg** [comment]
@atamazov Please review

**Comment by junliume** [comment]
@averinevg is this the test? picked from CI log, why is it still saying "NotImplemented" ? :)
```
224/300 Test #229: ConvStridedTensors.ConvStridedTensorsNotImplemented

**Comment by averinevg** [comment]
> @averinevg is this the test? picked from CI log, why is it still saying "NotImplemented" ? :)
> 
> ```
> 224/300 Test #229: ConvStridedTensors.ConvStridedTensorsNotImplemented
> ```

@junliume This test checks that the library returns an error for convolution with strided tensors since it's not implemented.

**Review by junliume — APPROVED** [review]

**Review by atamazov — APPROVED** [review]
LGTM!

**Pull request merged**
