### PR TITLE
[Test][CI] Fp32 Hip All Install gfx1030 to replace OCL

### PR DESCRIPTION
**Pull request by junliume**
Replace Fp32 OpenCL All gfx1030 stage in MIOpen CI with Fp32 Hip All Install gfx1030

### CODE REVIEW

**Comment by atamazov** [comment]
[hint]
@junliume Please look at https://github.com/ROCmSoftwarePlatform/MIOpen/wiki/How-to-manually-run-CI-job-with-parameters. This stuff was added exactly to avoid commenting blocks of code in the Jenkinsfile.

Please also note that multi-line C comments (`/* ... */`) should work in it.

**Comment by junliume** [comment]
> [hint]
> @junliume Please look at https://github.com/ROCmSoftwarePlatform/MIOpen/wiki/How-to-manually-run-CI-job-with-parameters. This stuff was added exactly to avoid commenting blocks of code in the Jenkinsfile.
> 
> Please also note that multi-line C comments (`/* ... */`) should work in it.

@atamazov Navi21 node has stability issues:
test_pooling2d (mainly), test_conv_3d, and test_soft_max:
http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/ci_gfx1030_ocl_to_hip/6/pipeline
and pipelines 1, 2, 4, 5, 6 of the same trial branch.

and here for another branch for Navi21:
http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/wa_1123_hotfix/1/pipeline 

I think we may need to investigate whether it is caused by HW (currently very limited resource).

BTW~ I am editing via VSCode, so that parallel stages closed by pair of brackets can show up as only three lines, and then "Ctr+ /" usually feels convenient. However, I realized now that it is hard to review in a diff-view, so that I will change to the page you have recommended or using (/* ... */) in the future :)

**Comment by junliume** [comment]
> Replace Fp32 OpenCL All gfx1030 stage in MIOpen CI with Fp32 Hip All Install gfx1030

@atamazov  @carlushuang This initiative is blocked by #1141

**Comment by junliume** [comment]
replaced by #1135

**Pull request closed without merging**
