### PR TITLE
[Solvers] ConvOclDirectFwdGen: split ConvolutionContext and ProblemDescription (stage 2)

### PR DESCRIPTION
**Pull request by averinevg**
PR splits ConvolutionContext and ProblemDescription inside ConvOclDirectFwdGen

### CODE REVIEW

**Comment by junliume** [comment]
@averinevg the [Solver] series of PRs have conflicts with recent FIN updates, let's work on resolving them first. Thanks!
CC:  @JehandadKhan  @cderb

**Comment by averinevg** [comment]
> @averinevg the [Solver] series of PRs have conflicts with recent FIN updates, let's work on resolving them first. Thanks! CC: @JehandadKhan @cderb

@junliume These PRs are still work in progress, and they must be merged into `development` branch after https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1694

**Comment by junliume** [comment]
> > @averinevg the [Solver] series of PRs have conflicts with recent FIN updates, let's work on resolving them first. Thanks! CC: @JehandadKhan @cderb
> 
> @junliume These PRs are still work in progress, and they must be merged into `development` branch after #1694

Thanks @averinevg ! Unfortunately, #1694  has to be reverted due to conflicts with #1669 , can we re-open #1694 after fixing the conflicts?

**Comment by averinevg** [comment]
> > > @averinevg the [Solver] series of PRs have conflicts with recent FIN updates, let's work on resolving them first. Thanks! CC: @JehandadKhan @cderb
> > 
> > 
> > @junliume These PRs are still work in progress, and they must be merged into `development` branch after #1694
> 
> Thanks @averinevg ! Unfortunately, #1694 has to be reverted due to conflicts with #1669 , can we re-open #1694 after fixing the conflicts?

@junliume Yes, sure

**Review by DrizztDoUrden — APPROVED** [review]
lgtm

**Review by junliume — APPROVED** [review]

**Pull request merged**
