### PR TITLE
[Tuning] rel-4.5 fdb update

### PR DESCRIPTION
**Pull request by cderb**

### CODE REVIEW

**Comment by junliume** [comment]
@cderb and @JehandadKhan:
Failure on this issue, restarted to check if it is run to run:

>FAILED: filesystem::recursive_directory_iterator increment error: No such file or directory

**Comment by atamazov** [comment]
> FAILED: filesystem::recursive_directory_iterator increment error: No such file or directory

Happened on ixt-sjc2-22 which is Navi21/36 during smoke testing with OCL backed. We do not supply fdb for it.

**Comment by junliume** [comment]
@cderb @JehandadKhan : would this "fix" this issue: https://ontrack-internal.amd.com/browse/SWDEV-305355?

**Comment by JehandadKhan** [comment]
> 
> 
> @cderb @JehandadKhan : would this "fix" this issue: https://ontrack-internal.amd.com/browse/SWDEV-305355?

Yes

**Review by atamazov — DISMISSED** [review]
Unfortunately, not good to go because #1196 has issues.

**Review by junliume — APPROVED** [review]

**Comment by atamazov** [comment]
Now in testing.

**Comment by atamazov** [comment]
## Perf testing results

:green_circle: Looks good. release/rocm-rel-4.5-staging, _prior vs after_ merging cderb/fdb_tuning_4.5, tested with gfx906/60 & ROCm 4.0. Performance gain, based on sum of all times/directions:

&nbsp; | &nbsp; | GPU time | Wall time | Aux Wall time
-- | -- | -- | -- | --
FP32/HIP | Default find mode | 1.14 | 1.08 | 1.45
&nbsp; | Immediate mode | 1.13 | 1.11 | 1.50
FP16/HIP | Default find mode | 1.00 | 0.90 | 0.74
&nbsp; | Immediate mode | 1.00 | 0.99 | 1.19
BF16/HIP | Default find mode | 1.00 | 0.95 | 1.09
&nbsp; | Immediate mode | 1.00 | 1.00 | 1.13
FP32/OpenCL | Default find mode | 0.99 | 1.02 | 0.99
&nbsp; | Immediate mode | 1.00 | 1.00 | 0.98

**Pull request merged**
