### PR TITLE
use official ZStd package from Facebook

### PR DESCRIPTION
**Pull request by apwojcik**
It is better to make ZStd a required dependency and use `Findzstd.cmake` from the official package.

### CODE REVIEW

**Review by DrizztDoUrden — APPROVED** [review]

**Comment by atamazov** [comment]
@apwojcik If ZStd is required and intended to replace Zlib, then I would expect removal of Zlib dependency, but I do not see it here. Why?

**Comment by atamazov** [comment]
@apwojcik 
> It is better to make ZStd a required dependency...

Can you please elaborate _why it is better_ (and maybe better than what)? Thanks!

**Comment by pfultz2** [comment]
> use Findzstd.cmake from the official package.

I think you mean the `zstd-config.cmake`.

**Comment by apwojcik** [comment]
> Can you please elaborate _why it is better_ (and maybe better than what)? Thanks!

When I wrote "better", I meant to use the module configuration scripts provided by the authors instead of us maintaining them.

**Comment by apwojcik** [comment]
> > use Findzstd.cmake from the official package.
> 
> I think you mean the `zstd-config.cmake`.

Yes, that is correct.

**Comment by apwojcik** [comment]
> @apwojcik If ZStd is required and intended to replace Zlib, then I would expect removal of Zlib dependency, but I do not see it here. Why?

As long as the Linux team does not plan to remove it, neither do we. ZStd is complementing existing compression algorithms. I still need to submit the PR utilizing ZStd. This PR is to prepare and introduce a small change, which is easy to back out if necessary.

**Comment by atamazov** [comment]
🟢 No objections!

**Review by junliume — APPROVED** [review]

**Pull request merged**
