### PR TITLE
add param to control CI stages

### PR DESCRIPTION
**Pull request by ce1adon**
This PR is prerequisite of PR #556 

I've investigated @pfultz2 's suggestion about using keyword in commits to control stage on/off. It requires setting changes on node side. I don't think we want to make any changes of the nodes' properties since this whole solution is adhoc for miopentensile. This strategy provides param control from stage level rather than step level. Open to requests of major revises.

### CODE REVIEW

**Comment by ce1adon** [comment]
Here is a sample of the skip process.
http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/skip-stages/2/pipeline
which is triggered by:
https://github.com/ROCmSoftwarePlatform/MIOpen/pull/837/commits/de6d97f80a22b16ed237dd5a6aa23baf501e53f1

**Comment by ce1adon** [comment]
Complete CI and ready for review

**Comment by ce1adon** [comment]
@pfultz2 @atamazov @JehandadKhan 
Any thoughts?

**Comment by atamazov** [comment]
I do not see any harm in this PR, basically it is NFC. But how you going to change value of `BUILD_CURRENT_STAGE`?

I am wondering if it would be easier to use `when` with `changelog` and `changeset`, combined by means of `anyOf` so MIOpenTensile stages will be triggered automatically when certain file changed (including dockerfile) or enforced when something like `[miopentensile]` reside in the commit message.

**Review by atamazov — APPROVED** [review]

**Review by JehandadKhan — CHANGES_REQUESTED** [review]
@ce1adon Shouldn't the default value be false? So that if someone wishes to explicitly run these tests they can do so, while in the default run, these stages are skipped ? Am I missing something here ?

**Comment by ce1adon** [comment]
> I do not see any harm in this PR, basically it is NFC. But how you going to change value of `BUILD_CURRENT_STAGE`?
> 
> I am wondering if it would be easier to use [`when` with `changelog` and `changeset`](https://www.jenkins.io/doc/book/pipeline/syntax/#when), combined by means of `anyOf` so MIOpenTensile stages will be triggered automatically when certain file changed (including dockerfile) or enforced when something like `[miopentensile]` reside in the commit message.

Thank you Artem! Using changelog and changeset is definitely a solution. The difficulty is that we cannot predict in future which branch(es) we are going to skip the tests, neither can we predict future branch name(s). With a simple bool value it will be easier to operate.

**Comment by ce1adon** [comment]
> @ce1adon Shouldn't the default value be false? So that if someone wishes to explicitly run these tests they can do so, while in the default run, these stages are skipped ? Am I missing something here ?

Thank you Jehandad! The default operation is to build current stage so it is set as true. By setting the value as false it will skip current stage.

**Comment by ce1adon** [comment]
@atamazov @JehandadKhan @pfultz2 
Any more comments?

**Review by JehandadKhan — APPROVED** [review]

**Pull request merged**
