### PR TITLE
[Bug Fix] Compilation fix for -DMIOPEN_USE_ROCBLAS=Off

### PR DESCRIPTION
**Pull request by cderb**

### CODE REVIEW

**Review by shurale-nkn — APPROVED** [review]
LGTM, but I want to know where this bug was found

**Comment by cderb** [comment]
> LGTM, but I want to know where this bug was found

Murali discovered it when he was attempting to build without rocblas.

**Review by muralinr — APPROVED** [review]
LGTM.

**Comment by muralinr** [comment]
Thank you @cderb for addressing this issue quickly.

**Review by junliume — APPROVED** [review]

**Pull request merged**
