### PR TITLE
Update fdb data to use solver keys [MI100][MI200]

### PR DESCRIPTION
**Pull request by cderb**
issue #1987 
MI100, MI210, and MI250: Update fdb to use solver idx, and save top 4 solvers. Update kdb to contain matching kernels.
Compressed fdb files.

### CODE REVIEW

**Comment by atamazov** [comment]
@cderb 
> ...save top 4 solvers. 

Can you please elaborate why only 4 solvers are saved? Thanks!

**Review by JehandadKhan — CHANGES_REQUESTED** [review]
Please see #2113

**Comment by cderb** [comment]
> Can you please elaborate why only 4 solvers are saved? Thanks!

@atamazov This was to attempt to keep the size of the fdb down, when allowing all solvers to be recorded, the size of the fdb bloated a bit. 4 was selected arbitrarily, as timing seemed to slow down significantly after that point from and eyed inspection. This limit could be extended if valuable.

**Comment by cderb** [comment]
Closing this in favor of #2151, to refresh the CI workspace.

**Pull request closed without merging**
