### PR TITLE
Remove outdated (and now wrong & harmful) workaround for apple

### PR DESCRIPTION
**Pull request by atamazov**
The reason of the issue: https://github.com/AMDComputeLibraries/MLOpen/pull/2400/files#r572106557. Unlike `AddProgram` and `AddKernel`, `HasProgram` does not use the `ProcessParams` trick, that adds a space to the compile args. That is why `HasProgram` fails to find existing program, if it has been added by `AddProgram` or `AddKernel`. Consequently, `PrecompileSolutions` rebuilds programs that already reside in the binary cache.

However we do not need `ProcessParams` at all, because currently -cl-std is appended to the end or params ([see comment in `ProcessParams`](https://github.com/AMDComputeLibraries/MLOpen/commit/2358609cfcc3d6d84245d89636b61b5b14d8d733#r46885082) that explains why it is required).

### CODE REVIEW

**Review by JehandadKhan — APPROVED** [review]
I agree with this change, once merged please let me know so I can revert the adjustment for this in Tuna

**Comment by atamazov** [comment]
Converted to draft to avoid spoiling docker image cache on CI. Please change this back to "normal" PR only after ending of CI moratorium (see mail). Then first merge from develop. Push the `[Ready for review]` button only after that. Thanks.

**Comment by atamazov** [comment]
@JehandadKhan 
> I agree with this change, once merged please let me know so I can revert the adjustment for this in Tuna

Is now the appropriate time to merge this and update Tuna?

**Comment by atamazov** [comment]
All tests passed.

**Pull request merged**
