### PR TITLE
[NFC] Remove -Wno-deprecated warning suppression

### PR DESCRIPTION
**Pull request by averinevg**
- Redundant `static constexpr` declarations have been removed. If a `static` data member is declared `constexpr`, it is implicitly `inline` and does not need to be redeclared at namespace scope (since C++17)
- `clCreateCommandQueue()` has been replaced with `clCreateCommandQueueWithProperties()` ( `clCreateCommandQueue()` is deprecated by OpenCL 2.0)

### CODE REVIEW

**Comment by junliume** [comment]
@averinevg could we also add tests to #1928 and #1929 to this PR?

**Comment by averinevg** [comment]
> @averinevg could we also add tests to #1928 and #1929 to this PR?

@junliume I'm working on test for https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1928, it is almost ready. Sure, we can, but I think it is better to add them in separated PRs

**Review by atamazov — APPROVED** [review]
LGTM

**Review by junliume — APPROVED** [review]
Always a great idea to remove global warning suppression :)

**Pull request merged**
