### PR TITLE
Port find-db updates from ROCm 4.2 Release

### PR DESCRIPTION
**Pull request by atamazov**

### CODE REVIEW

**Comment by atamazov** [comment]
@DrizztDoUrden This fixes some important performance issues in the rocm-4.2.x. But there is none GEMM Solvers in the rocm-4.2.x. Could you please apply your scripts and convert "gemm" to GEMM solver names?

**Comment by atamazov** [comment]
Performance testing in progress...

**Comment by atamazov** [comment]
@JehandadKhan @DrizztDoUrden Please review.

**Comment by atamazov** [comment]
Performance testing develop vs PR is done (93 FP32 configs):
- ROCm 4.0: Fwd 0%, Bwd -0%, WrW -20%
- ROCm 4.2 RC2: Fwd 0%, Bwd, -0%, WrW -0%

The performance drop with 4.0 is due to different compilers. In many cases, the best solver with 4.2 is HIP ImplicitGemm, but with 4.0 the same kernel is much slower.

**Comment by atamazov** [comment]
Reviewers, I need approval to merge this.

**Comment by JehandadKhan** [comment]
@atamazov  This diff would NOT have the WrW gemm solvers and therefore might break stuff. @DrizztDoUrden Can you share your script for transforming the db or update the DB to reflect those solvers.

**Comment by atamazov** [comment]
@JehandadKhan All necessary gemm solvers already fixed by https://github.com/ROCmSoftwarePlatform/MIOpen/pull/923/commits/73e4135f5ab7dfe0f4164df20fe59309743c9377.

**Review by DrizztDoUrden — APPROVED** [review]

**Pull request merged**
