### PR TITLE
[Workaround] bug in the llvm::msgpack when "n" and "y" are recognized as a boolean instead of a string. 

### PR DESCRIPTION
**Pull request by atamazov**
More fixes to resolve issue #1731 (why: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1816#issuecomment-1272733599)

@junliume Please attribute this with:
- Reviewers: @littlewu2508, @carlushuang @shaojiewang 
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/non-miopen-bug)https://github.com/ROCmSoftwarePlatform/MIOpen/labels/non-miopen-bug https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_high (borrowed from #1731)

### CODE REVIEW

**Comment by junliume** [comment]
Ping Reviewers: @littlewu2508, @carlushuang @shaojiewang

CI has passed

**Review by junliume — APPROVED** [review]
@atamazov although very simple ones, it is a change to ~4k files after all. Is there any other alternatives to this workaround?

**Review by shaojiewang — APPROVED** [review]
I don't have enough time to check every single file. But code looks good. It means that we should also change the codegen part of MISA.

**Comment by littlewu2508** [comment]
I'll go test this with upstream clang

**Comment by littlewu2508** [comment]
Tests passed for Gentoo miopen-5.1.3 package, compiled using clang-14, so I suppose this patch fixes https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1731

I'll test miopen-5.3.0 upon clang-15 in the future.

**Comment by atamazov** [comment]
@junliume 
> @atamazov although very simple ones, it is a change to ~4k files after all. Is there any other alternatives to this workaround?

No. And we also need to update the generator of igemm gtc kernels so it won't produce `N`, `Y`, `n`, `y` as names of kernel parameters (it is recommended to produce `N_`, `Y_`, `n_`, `y_` instead). That is why @shaojiewang and @carlushuang were invited here.

**Comment by atamazov** [comment]
@junliume Thanks!

**Pull request merged**
