### PR TITLE
[ROCm 5.3][gfx90a68] Tuning updates of fdb and kdb key configurations

### PR DESCRIPTION
**Pull request by iq136boy**
Rocm5.3 mi210 (104 cu) find db tuning for all configs (140k) to create fdb and kdb

### CODE REVIEW

**Comment by junliume** [comment]
@iq136boy draft? KDB still delivered via Ginger?

**Comment by iq136boy** [comment]
> @iq136boy draft? KDB still delivered via Ginger?
@junliume, both fdb and kdb are updated now. For KDB, as @JehandadKhan suggested, we now use git LFS to manage so that it can be push to git hub as a LFS file.

**Comment by junliume** [comment]
> > @iq136boy draft? KDB still delivered via Ginger?
> 
> @junliume, both fdb and kdb are updated now. For KDB, as @JehandadKhan suggested, we now use git LFS to manage so that it can be pushed to git hub as a LFS file.

Thank you! Could you also take a look at Artem's comments here: https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1681#issuecomment-1210523630

Are the invalid entries removed?

**Comment by iq136boy** [comment]
> Thank you! Could you also take a look at Artem's comments here: [#1681 (comment)](https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1681#issuecomment-1210523630)
> 
> Are the invalid entries removed?
> 
@JehandadKhan and @cderb, the invalid entries which caused regression on MI60 that Arthem mentioned have not been removed, right? I think we might need to update the find db for MI60 too. Please confirm.
>
> @iq136boy : also please help to confirm the regressions mentioned [here](https://ontrack-internal.amd.com/browse/SWDEV-345998?focusedCommentId=9308616&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-9308616) arefixed in this PR
>
@junliume Let me double check and get back to you.

**Comment by iq136boy** [comment]
> @iq136boy : also please help to confirm the regressions mentioned [here](https://ontrack-internal.amd.com/browse/SWDEV-345998?focusedCommentId=9308616&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-9308616) are fixed in this PR
@junliume Just double check with Chris, since we have tuning all the configs. The regressions should be fixed in these three models.

**Review by junliume — APPROVED** [review]

**Comment by junliume** [comment]
@iq136boy  let's prepare a cherry-pick into release branch then. (most release-targeted tuning updates needs to be in both `develop` and `rocm-*-rel` branches any way.

**Comment by atamazov** [comment]
@junliume 
> @iq136boy let's prepare a cherry-pick into release branch then.

IIRC normally we perform tuning **_for_** the release branches and **_using_** the library built from the release branches. Because the goal is optimal performance of the release. If we perform tuning using the library built from `develop`, and cherry-pick the results into release branch, then release might perform worse than it should.

@JehandadKhan Am I right? can you please confirm, thanks!

**Comment by JehandadKhan** [comment]
@atamazov You are indeed correct, that was the modus operandi before. However, moving forward we are trying to accomplish this process as early as possible.

**Pull request merged**
