### PR TITLE
[WORKAROUND] ConvAsm3x3U disabled

### PR DESCRIPTION
**Pull request by atamazov**
This is workaround for #609. Performance may be affected.

### CODE REVIEW

**Comment by Kirpich30000** [comment]
The ConvAsm3x3U is pretty old version. I don't expect noticible performance win over RxS variation.
If this is the case I vote for removing this solver all together.

**Comment by atamazov** [comment]
@Kirpich30000 Do you approve the workaround?

**Review by DrizztDoUrden — APPROVED** [review]

**Comment by atamazov** [comment]
Needs to investigate & discuss with @Kirpich30000

**Comment by atamazov** [comment]
Superseded by #643

**Pull request closed without merging**
