### PR TITLE
[MLIR] Removing MLIR dependency requirement until ROCm 5.1

### PR DESCRIPTION
**Pull request by jerryyin**
Clarified with @JehandadKhan and @junliume then realized that the existing develop is still in ROCm 5.0 timeline. Since ROCm release requires linear history, I come up with this PR shooting for 
 - merge pre-ROCm 5.0 branch as the last PR, such that ROCm 5.0 doesn't have MLIR dependency
 - revert once ROCm 5.0 forked, such that MLIR will be default dependency in ROCm 5.1

Or, this can be cherry-picked in ROCm 5.0 release branch so no change is necessary in the develop branch.

Call for feedbacks in the best way to deal with it.

### CODE REVIEW

**Comment by junliume** [comment]
[comments]
Building the MLIR dependency is really slow, now `cmake -P install_deps.cmake ` takes more than 40 mins on my local machine (build dependencies from scratch).

**Review by atamazov — APPROVED** [review]
This matches the "(4) Disable MLIR via CMake in amd-develop only" recently discussed in mail, except that this should be merged into `amd-develop` instead of `develop`

**Comment by atamazov** [comment]
Smoke tests passed, the rest of CI is in progress...

**Comment by atamazov** [comment]
Rebased as per #1306

**Comment by atamazov** [comment]
This should not be merged because 95b58f72f _"Removing MLIR dependency requirement until ROCm 5.1"_ was merged into `amd-develop` directly.

**Comment by atamazov** [comment]
Side effect: Dependency on MLIR library will persist in 5.0 in spite of that it is not really needed.

**Pull request closed without merging**
