### PR TITLE
Adding missing test vectors which caused failures (partial fix for SWDEV-291891)

### LINKED ISSUE #915: [OCL][BatchNorm] Verification failed
The following params of `bnorm` of `bnormfp16` will cause presicion verification failure.
```
MIOpenDriver bnorm -n 38 -c 128 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 128 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 256 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 32 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 512 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 64 -H 160 -W 160 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 38 -c 64 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 64 -c 256 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnormfp16 -n 64 -c 512 -H 20 -W 20 -m 1 --forw 0 -b 1 -r 1 -V 1
```

@atamazov UPDATE: More failing configs here: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/916#issuecomment-840199623

### PR DESCRIPTION
**Pull request by muralinr**
Finally resolves #915, see https://github.com/ROCmSoftwarePlatform/MIOpen/issues/915#issuecomment-839212864

### CODE REVIEW

**Comment by junliume** [comment]
@muralinr this PR is to add *selective* precision verification failures mentioned in #915 and #916?

**Review by ce1adon — DISMISSED** [review]

**Comment by muralinr** [comment]
> @muralinr this PR is to add _selective_ precision verification failures mentioned in #915 and #916?

Yes Jun.

**Comment by atamazov** [comment]
## It seems like the updated tests are still unable to detect the issue fixed by #916.

ROCm 4.0, gfx906/60, FP32 tests, develop without #916 but with this PR:
- Error: All BN tests PASS
- Expected behavior: ___At least one BN test should fail.___

```
16/67 Test  #2: test_bn_3d_peract_test ...........   Passed   60.23 sec
17/67 Test  #4: test_bn_aux ......................   Passed    0.26 sec
18/67 Test  #3: test_bn_3d_spatial_test ..........   Passed   66.41 sec
19/67 Test  #5: test_bn_peract_test ..............   Passed  204.24 sec
25/67 Test  #6: test_bn_spatial_test .............   Passed  275.15 sec
```
How to reproduce:
- git checkout 96d7086fa (develop just before #916)
- cherry-pick all commits from `batchnorm_add_testcase` on top of that (currently one commit, df23281f87a)
- configure with `-DMIOPEN_TEST_ALL=On`, like this (build for HIP backend):
```
CXX=/opt/rocm/llvm/bin/clang++ \
cmake \
-DBUILD_DEV=On \
-DMIOPEN_TEST_ALL=On \
-DCMAKE_BUILD_TYPE=release \
-DMIOPEN_TEST_FLAGS="--verbose --disable-verification-cache" ..
```
- Run tests: `MIOPEN_LOG_LEVEL=5 CTEST_PARALLEL_LEVEL=4 make check -j 16 2>&1 | tee <SOME LOG FILE>`

Note that the following driver command fails with that build:
```
$ ./bin/MIOpenDriver bnorm -n 38 -c 128 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1 -V 1
MIOpenDriver bnorm -n 38 -c 128 -H 80 -W 80 -m 1 --forw 0 -b 1 -r 1 -V 1
Backwards prop batch norm verification passed on dx.
Backwards prop batch norm verification failed on dscale: 0.872698
max difference in dscale: 0
Backwards prop batch norm verification passed on dbias.
```

FP16 tests reveal the same behavior (add `-DMIOPEN_TEST_HALF=On` to CMake command line).

**Review by atamazov — CHANGES_REQUESTED** [review]
Unfortunately, the updated tests do not function as expected, https://github.com/ROCmSoftwarePlatform/MIOpen/pull/974#issuecomment-858120030

**Comment by muralinr** [comment]
I do see these failed test cases are called with new code as I printed "test_bn_spatial_test" testcases.  We may need to adjust error thresholds to see them as failures.  
 
./bin/test_bn_spatial_test --float --input 38, 32, 160, 160
Iteration: 29
./bin/test_bn_spatial_test --float --input 38, 64, 80, 80
Iteration: 30
./bin/test_bn_spatial_test --float --input 38, 64, 160, 160
Iteration: 31
./bin/test_bn_spatial_test --float --input 38, 128, 80, 80
Iteration: 32
./bin/test_bn_spatial_test --float --input 38, 256, 20, 20
Iteration: 33
./bin/test_bn_spatial_test --float --input 38, 512, 20, 20

**Comment by atamazov** [comment]
@muralinr 
> I do see these failed test cases are called with new code as I printed "test_bn_spatial_test" testcases. We may need to adjust error thresholds to see them as failures...

Can you try to do this in this PR?

**Comment by muralinr** [comment]
> @muralinr
> 
> > I do see these failed test cases are called with new code as I printed "test_bn_spatial_test" testcases. We may need to adjust error thresholds to see them as failures...
> 
> Can you try to do this in this PR?

Changing thresholds will open up unforeseen issues from other test vectors and may break CI system.  We will investigate and change entire thresholds as part of long term planning..

**Comment by atamazov** [comment]
@muralinr 
> Changing thresholds will open up unforeseen issues from other test vectors and may break CI system. We will investigate and change entire thresholds as part of long term planning..

Please open a ticket for this and I will merge this PR. Thanks!

**Comment by muralinr** [comment]
> @muralinr
> 
> > Changing thresholds will open up unforeseen issues from other test vectors and may break CI system. We will investigate and change entire thresholds as part of long term planning..
> 
> Please open a ticket for this and I will merge this PR. Thanks!
Hi Artem,
Here is a JIRA ticket.
https://ontrack-internal.amd.com/browse/SWDEV-291891

**Comment by atamazov** [comment]
@muralinr Thanks!

[Notice] However this may be an overkill. I mean, opening Jira tickets. We can simply open tickets in this repo for things like this.

**Review by atamazov — APPROVED** [review]
LGTM

**Pull request merged**
