### PR TITLE
[NFC] Fix typo: workspce -> workspace.

### PR DESCRIPTION
**Pull request by whchung**
Upon adding a workspace parameter to MLIR solver I spotted this typo. Proposing to fix it in this PR.

### CODE REVIEW

**Review by atamazov — APPROVED** [review]
LGTM

**Comment by atamazov** [comment]
Thanks, @whchung !

**Review by junliume — APPROVED** [review]

**Comment by atamazov** [comment]
@whchung Formatting must be fixed. I can do it for you, if necessary.

**Comment by junliume** [comment]
> @atamazov I ran `git clang-format` locally but didn't find anything to be fixed. Could you help me on this? Thanks!

I am quite puzzled by the clang format complaints too:
http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/fix-workspce-typo/3/pipeline

**Comment by atamazov** [comment]
> I am quite puzzled by the clang format complaints too... 

Search for `>` of `---` in the log.

**Comment by atamazov** [comment]
@whchung 
> @atamazov I ran `git clang-format` locally but didn't find anything to be fixed. Could you help me on this? Thanks!

No problem, will do. For the future: https://github.com/ROCmSoftwarePlatform/MIOpen/wiki/How-to-format-code

**Review by atamazov — APPROVED** [review]
LGTM

**Review by junliume — APPROVED** [review]

**Pull request merged**
