### PR TITLE
Split miopen::ConvolutionContext and miopen::ProblemDescription (stage 1)

### PR DESCRIPTION
**Pull request by averinevg**
This PR makes miopen::ProblemDescription a member of miopen::ConvolutionContext. Other changes have been produced by clang-format. This is the first PR in a series.

### CODE REVIEW

**Comment by averinevg** [comment]
@atamazov Please, review

**Comment by junliume** [comment]
@atamazov @JehandadKhan @iq136boy @DrizztDoUrden 
CI has passed, please review

**Review by DrizztDoUrden — APPROVED** [review]
LGTM

**Review by JehandadKhan — APPROVED** [review]

**Comment by JehandadKhan** [comment]
FYI @junliume

**Review by junliume — APPROVED** [review]

**Comment by junliume** [comment]
@averinevg sorry that this PR has to be reverted due to conflicts:
http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/develop/775/pipeline

Could you merge the latest develop and re-open this one? Thanks!

**Pull request merged**
