### PR TITLE
Tuning MIOpen 2.4 and ROCm 3.5

### PR DESCRIPTION
**Pull request by alexandraBara**

### CODE REVIEW

**Comment by JehandadKhan** [comment]
[Link to Excel sheet](https://amdcloud-my.sharepoint.com/:x:/g/personal/jkhan_amd_com/ETPVltA_fiVIq8wV5b6S6V0BHaFJPlZmLkMeQ9kyQCwhQg?e=1KnEph)

Network | Batchsize | 2.3.0 | This PR |   | Speedup
-- | -- | -- | -- | -- | --
AlexNet | 512 | 2617.74 | 2824.54 |   | 107.90%
GoogLeNet | 128 | 948.89 | 963.63 |   | 101.55%
Inception3 | 128 | 159.7 | 215.04 |   | 134.65%
Inception4 | 64 | 70.22 | 89.05 |   | 126.82%
LeNet | 128 | 5426.63 | 5445.61 |   | 100.35%
ResNet101 | 64 | 218.17 | 228.82 |   | 104.88%
ResNet152 | 64 | 151.62 | 160.06 |   | 105.57%
ResNet50 | 128 | 387.27 | 437.6 |   | 113.00%
ResNet50v1.5 | 64 | 252.23 | 353.63 |   | 140.20%
Trivial | 128 | 5711.09 | 5688.51 |   | 99.60%
Vgg16 | 128 | 204.03 | 229.22 |   | 112.35%
VGG19 | 128 | 154.7 | 177.85 |   | 114.96%

**Comment by atamazov** [comment]
As far as I see from git log,
```
copied:     ../../src/kernels/gfx906_64.HIP.fdb.txt -> ../../src/kernels/gfx906_60.HIP.fdb.txt
```
NP, I do understand that we do not have sufficient resources to tune for all HW. However, can we expect tuning for this target and if yes, when? When we have new tuning infrastructure?

**Comment by atamazov** [comment]
Note that collecting fdb should be much faster than tuning, ~100 times or more.

**Comment by JehandadKhan** [comment]
@atamazov In theory yes, however, note that the current find db took four days to run. 

Furthermore, the new tuning infra is not a silver bullet either, it would still be bound by hardware resources, though hopefully less so than it is right now.

**Comment by atamazov** [comment]
@JehandadKhan 
> In theory yes, however, note that the current find db took four days to run.

Unfortunately yes. I made a rough assessment, and I got 5.3 days.

Now we cannot use parallelism at full. Dedicated GPU-less servers for building binary cache will be able to leverage parallelism more intensively. For example, you can run MIOpenDriver in a large number of parallel processes. I am currently busy with comgr, but if time permits, I can try to quickly make an environment variable (something like `MIOPEN_ONLY_BUILD_FOR_GFX`) that should enablie running the driver on a machine without a GPU. This would allow to begin the implementation of a new infrastructure. What do you think?

/cc @daniellowell

**Comment by JehandadKhan** [comment]
> @JehandadKhan
> 
> > In theory yes, however, note that the current find db took four days to run.
> 
> Unfortunately yes. I made a rough assessment, and I got 5.3 days.
> 
> Now we cannot use parallelism at full. Dedicated GPU-less servers for building binary cache will be able to leverage parallelism more intensively. For example, you can run MIOpenDriver in a large number of parallel processes. I am currently busy with comgr, but if time permits, I can try to quickly make an environment variable (something like `MIOPEN_ONLY_BUILD_FOR_GFX`) that should enablie running the driver on a machine without a GPU. This would allow to begin the implementation of a new infrastructure. What do you think?
> 
> /cc @daniellowell

That is indeed the plan, I would really appreciate it if you can spare some time to do it. Otherwise, it is on my todo list for this feature.

**Pull request merged**
