### PR TITLE
[COMgr] Prepare for COMgr 3.x

### LINKED ISSUE #3075: Remove deprecated Comgr actions
The AMD_COMGR_ACTION_COMPILE_SOURCE_TO_FATBIN and AMD_COMGR_ACTION_ADD_DEVICE_LIBRARIES actions have been deprecated, and will be removed with the upcoming Comgr 3.0 release.

We should be able to replace them with one of the following:

AMD_COMGR_ACTION_COMPILE_SOURCE_WITH_DEVICE_LIBS_TO_BC

or 

AMD_COMGR_ACTION_COMPILE_SOURCE_TO_RELOCATABLE
AMD_COMGR_ACTION_COMPILE_SOURCE_TO_EXECUTABLE
 
(Although not in the action name, the last two also add the device libraries)

### PR DESCRIPTION
**Pull request by atamazov**
This is intended to resolve #3075. By-products are some small fixes and removal of useless code (e.g HIP builds via COMgr; from now on online HIP builds are supported only via HIPRTC). Details:

- [comgr] Added support for AMD COMgr 3.0.
- By-products:
  - [comgr] Removed support for AMD COMgr older than 1.7.
  - [comgr] Removed `comgr::BuildHip()`.
    - Why: The compilation of HIP kernels via COMgr is broken for a long time. Fixing it requires a lot of efforts (because we must guarantee performance of kernels to be on par with kernels built via HIPRTC) but useless because HIPRTC exists on all systems where we have COMgr.
  - [cmake] Do not allow different values of MIOPEN_USE_COMGR and MIOPEN_USE_HIPRTC.
  - [comgr][NFC][quality] Removed support of unused enum members from to_string()
  - [wingorad fury] Fix precompiled binary cache miss for Winograd Fury. Resolves https://github.com/ROCm/MIOpen/pull/2778#discussion_r1670854903.
  - [cmake][NFC] Remove leftovers of support of ROCm older than 5.0.

## :cyclone: Performance testing results

Preconditions:
- Navi21 (gfx1030/36)
- ROCm 6.0.2 docker `miopen:ci_a9eebf`, Ubuntu 20.04.5 LTS
- BUILD_DEV=On, Release build
- branch amdcomgr-3 2f380632f vs. develop fea5579a3
- 93 known FP32 convolution configs
- 93 known FP16 convolution configs

Tested modes:
- (0) Immediate mode with default (system) find-db
- (1) Find Mode (DYNAMIC_HYBRID)
- (2) Find Mode (NORMAL)
- (3) Immediate mode with user find-db filled by step (2).

No performance or correctness regressions. Detailed logs & csv files are available upon request.

----
[Attribution] @junliume @JehandadKhan
- https://github.com/ROCm/MIOpen/labels/enhancement
- https://github.com/ROCm/MIOpen/labels/urgency_high
- https://github.com/ROCm/MIOpen/labels/value_high
- Proposed reviewers:
  - @JehandadKhan 
  - @junliume
  - @lamb-j
  - @averinevg

### CODE REVIEW

**Review by lamb-j — APPROVED** [review]

**Comment by lamb-j** [comment]
Left one comment, but otherwise Comgr changes LGTM, thanks!

If you're interested, there are some new actions, languages, and data types that have been added that aren't currently included the MIOpen Enums. See here:

https://github.com/ROCm/llvm-project/blob/amd-staging/amd/comgr/docs/ReleaseNotes.md

I assume they could also be added later, as-needed

**Comment by lamb-j** [comment]
Apparently I can't comment on unchanged lines, but for Line 370 of comgr.cpp:

We may also remove the AMD_COMGR_DATA_KIND_FATBIN language type for 3.0, as we've removed the associated FATBIN action.

It may be convenient to remove it here to avoid a separate patch

**Comment by atamazov** [comment]
@lamb-j Yep, so it seems that you will likely remove AMD_COMGR_DATA_KIND_FATBIN from amd_comgr_data_kind_t. Which means that we'll have a build error and therefore this data kind needs to be removed for COMgr 3.x. Thanks!

**Review by CAHEK7 — APPROVED** [review]

**Comment by atamazov** [comment]
@lamb-j Done in a5a76064e7d60bab7513510e6e11db8f5ef58b1a

**Comment by atamazov** [comment]
@junliume @CAHEK7 @lamb-j Ready for CI testing and another review round. Someone please launch the CI job, thanks!

**Review by averinevg — APPROVED** [review]

**Comment by averinevg** [comment]
CI job launched

**Comment by junliume** [comment]
@atamazov can you access the Windows build logs? We need to protect it from breaking too.
```
C:\home\jenkins\agent\workspace\UIF2_MIOpen_PR-3107\MIOpen\src\comgr.cpp:589:20: error: unused function 'IsWave64Enforced' [-Werror,-Wunused-function]
  | 14824 | 08:40:01 AM | 589 \| static inline bool IsWave64Enforced(const OptionList& opts)
  | 14825 | 08:40:01 AM | \|                    ^~~~~~~~~~~~~~~~

```

**Comment by atamazov** [comment]
@junliume 
> can you access the Windows build logs?

Unfortunately, no access

**Comment by atamazov** [comment]
@junliume @apwojcik 
> ```
> C:\home\jenkins\agent\workspace\UIF2_MIOpen_PR-3107\MIOpen\src\comgr.cpp:589:20: error: unused function 'IsWave64Enforced' [-Werror,-Wunused-function]
> ```

FYI this may happen only if HIP runtime does not support precompiled headers (PCH), which seems suspicious.

**Comment by atamazov** [comment]
@junliume https://github.com/ROCm/MIOpen/pull/3107#issuecomment-2223998283 is fixed in 9f73a5b2406dd05530c5f182b7cc385ba1472520

**Comment by shurale-nkn** [comment]
@atamazov please merge develop into this branch. Otherwise, it will not pass the CI

**Comment by atamazov** [comment]
@averinevg thanks for e711774!

**Review by junliume — APPROVED** [review]

**Comment by lamb-j** [comment]
@atamazov @junliume thanks for implementing and merging this!

What's the typical turnaround time for promotion to amd-master for MIOpen?

**Comment by atamazov** [comment]
@lamb-j 
> What's the typical turnaround time for promotion to amd-master for MIOpen?

It depends on many things. At https://github.com/ROCm/MIOpen/commits/amd-master I see that amd-master has been updated several times in the last month. But on the other hand, before that it remained unchanged for a month or so. I guess that @junliume maintains some mailing lists dedicated to MIOpen promotions, so you can ask him to add your email there.

**Pull request merged**
