### PR TITLE
[find-db] Fix invalid GemmBwd1x1 records. W/A for issue 1008

### LINKED ISSUE #1006: [find-db] Invalid GemmBwd1x1 records
The issue manifests during `test_conv_embed_db`. It fails on gfx906/64 (but passes on gfx906/60). The reason is corrupted find-db for gfx906/64/HIP. There are invalid solver names `GemmBwd1x1_0_1/2`. Valid names are `GemmBwd1x1_stride1/2`. How this happens (only tips):
- HYBRID_DYNAMIC Find mode
- Invalid solver id `GemmBwd1x1_0_1` 
- `Find()` falls down to NORMAL Find process
- `ConvBinWinogradRxSF3x2` is encountered for which we do not have perf-db records
  - @JehandadKhan This is different issue related to Tuning; this Solver is tunable
- The tests sees "perf db record not found" and fails

----
[Original comment] Both failures happened on ixt-rack-54. Let's just restart but keep an eye on that node.

_Originally posted by @atamazov in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1004#issuecomment-866836255_

### PR DESCRIPTION
**Pull request by atamazov**
- Resolves #1006
- Workaround for #1008

### CODE REVIEW

**Review by shurale-nkn — DISMISSED** [review]

**Comment by junliume** [comment]
@atamazov diff is too large (e.g. 13,554 additions, 13,554 deletions) probably due to (1) line end issue or (2) order automatically changed. How did you fix the issue so quickly? By commenting out corrupted entries (lines)?
P.S. if it is and for line end issue, and if there was no gitattributes file when the repo is first created, it might be a better idea that we do not add it. Last time I did such thing caused a lot of problems :(

**Comment by atamazov** [comment]
> How did you fix the issue so quickly?

Find-db files are text files. Find and replace used.

**Review by junliume — APPROVED** [review]

**Comment by atamazov** [comment]
> diff is too large (e.g. 13,554 additions, 13,554 deletions) probably due to (1) line end issue or (2) order automatically changed. 

No, the reason is that files are huge and there are many incorrect lines in each. Stats:
image


But you still can view diff for some of them -- try src/kernels/gfx900_64.OpenCL.fdb.txt.

**Review by shurale-nkn — APPROVED** [review]
better use this afther the add_custom_test call
`set_property(TEST test_conv_embed_db PROPERTY ENVIRONMENT MIOPEN_DEBUG_AMD_WINOGRAD_RXS_F3X2=0)`

**Comment by atamazov** [comment]
> better use this afther the add_custom_test call
> `set_property(TEST test_conv_embed_db PROPERTY ENVIRONMENT MIOPEN_DEBUG_AMD_WINOGRAD_RXS_F3X2=0)`

Thanks, I've forgotten that. Maybe next time ;)

**Pull request merged**
