### PR TITLE
[MIOpenTensile] Remove transpose flag

### PR DESCRIPTION
**Pull request by pfultz2**
The transpose flag will be removed in MIOpenTensile in this PR: https://github.com/ROCmSoftwarePlatform/MIOpenTensile/pull/19. This updates MIOpen to work with the correct API.

### CODE REVIEW

**Comment by pfultz2** [comment]
> We want to test both the latest release version and latest develop version. Please keep them.

Only one version works, as this is not a backwards compatible change.

**Comment by pfultz2** [comment]
Why are we testing two different version of tensile on every commit? If we want to test the a newer version of MIOpenTensile we should open a PR to update the version of tensile we test.

**Comment by ce1adon** [comment]
@atamazov @pfultz2 
The problem with this modification is not simply about whether to test 1 or 2 version of miopentensile. It removes an important indicator of "transpose of matrix" from tensile descriptor, which is already proved to be miss-leading in a previous jira ticket http://ontrack-internal.amd.com/browse/SWDEV-233998. **This is extremely harmful when dealing with low-precision packed datatype. However, this PR DOES NOT include any LOW PRECISION tensile tests, ESPECIALLY INT8. It's NOT PROPERLY TESTED IN CURRENT STATUS.**

**Comment by pfultz2** [comment]
> It removes an important indicator of "transpose of matrix" from tensile descriptor

The indication of transposition comes from the strides in tensile not a transpose flag, which is redundant and becomes ambiguous when user specifies strides one way and transpose flag another.

The API was originally setup without the transpose flag so it can closely match tensile's tensor contractions. 

> This is extremely harmful when dealing with low-precision packed datatype.

How is that harmful? Tensile only uses the strides for packed data types, and we should do the same in MIOpenTensile.

**Comment by ce1adon** [comment]
@atamazov Yes, PR #556 with low precision tests needs to go first.

**Comment by atamazov** [comment]
Let's put it on hold for now.

**Comment by pfultz2** [comment]
@ce1adon So this passes all the tensile tests. I will probably merge the change into miopentensile, and then this will need to be merged.

**Comment by atamazov** [comment]
@ce1adon Please ping me when this needs to be merged.

**Comment by junliume** [comment]
ping @ce1adon :) Has this PR been merged into miopentensile? If so we may need to process this PR here too.

Or if plans have changed, we can close this PR.

**Comment by ce1adon** [comment]
> ping @ce1adon :) Has this PR been merged into miopentensile? If so we may need to process this PR here too.
> 
> Or if plans have changed, we can close this PR.

We need to test this PR in CI with both tensile test stage on before any action.

**Comment by atamazov** [comment]
Merge conflicts.

> We need to test this PR in CI with both tensile test stage on before any action.

@ce1adon Please let me know you you need assistance with this.

**Comment by pfultz2** [comment]
This already was tested with the tensile stage on

**Comment by atamazov** [comment]
@pfultz2 There are two CI jobs with the same commit hash. Do we need both?
image

**Comment by atamazov** [comment]
CI tests passed, but review is not done yet. I am sorry guys, but I do not understand if this needs to be merged and when.

**Comment by ce1adon** [comment]
> CI tests passed, but review is not done yet. I am sorry guys, but I do not understand if this needs to be merged and when.

The two tensile related stages need to be tested.

**Comment by atamazov** [comment]
I understand, but this does not answer my question:

> if this needs to be merged and when?

**Comment by ce1adon** [comment]
> I understand, but this does not answer my question:
> 
> > if this needs to be merged and when?

No idea, either. Sorry!

**Comment by ce1adon** [comment]
MIOpentensile is a side project now due to other new coming requests. @atamazov

**Comment by junliume** [comment]
> > CI tests passed, but review is not done yet. I am sorry guys, but I do not understand if this needs to be merged and when.
> 
> The two tensile related stages need to be tested.

@ce1adon since https://github.com/ROCmSoftwarePlatform/MIOpenTensile/pull/19 is already merged I think we should have this PR merged as long as it will not break anything.
How do I or anyone else test these stages you've mentioned? If they passed can we just merge this one and work on other stuff? :)

**Comment by ce1adon** [comment]
> @ce1adon since [ROCmSoftwarePlatform/MIOpenTensile#19](https://github.com/ROCmSoftwarePlatform/MIOpenTensile/pull/19) is already merged I think we should have this PR merged as long as it will not break anything.
> How do I or anyone else test these stages you've mentioned? If they passed can we just merge this one and work on other stuff? :)

Sure. The params controling the tests are in Jenkinsfile. I just started the CI with the tensile tests.

**Comment by atamazov** [comment]
@ce1adon CI tests passed. Please approve and I will merge.

**Review by junliume — APPROVED** [review]

**Pull request merged**
