### PR TITLE
Fixed warning on insufficient workspace in find to be more clear on nullptr

### PR DESCRIPTION
**Pull request by DrizztDoUrden**

### CODE REVIEW

**Comment by daniellowell** [comment]
@DrizztDoUrden Formatting.

**Comment by TejashShah** [comment]
@DrizztDoUrden Does this PR fix the issue reported here #238 

If yes, could you please link this PR with that issue.

**Comment by atamazov** [comment]
>  Does this PR fix the issue reported here #238

No.

**Comment by DrizztDoUrden** [comment]
It just reports the error in a less weird way. (x < x)

**Pull request merged**
