### PR TITLE
ConvOclDirectFwdGen: Fixed out-of-bounds memory access

### PR DESCRIPTION
**Pull request by atamazov**
Resolves the following issues:
- "[PyTorch] Memory access fault in shufflenet microbenchmark", https://github.com/AMDComputeLibraries/MLOpen/issues/1681
- #2522

Changes:
- MIOpenCDFGen, MIOpenCDFGen4: Fixed memory access failures when reading weights.
- Removed W/A for https://github.com/AMDComputeLibraries/MLOpen/issues/1681
- Removed some non-formalized legacy workaround in ConvOclDirectFwdGen
- Byproducts:
  - [debugging] Disabled MIOPEN_DEBUG_FIND_ONLY_SOLVER during driver warm-up.
  - [NFC] Removed some dead code from OpenCL kernels
  - [NFC] Modern-style code reformat

### Navi21, ROCm 5.7 docker
- Correctness testing with test_conv2d
  - 2452 fp32 configs
    - Kernels benchmarked, no Memory Access Failures.
    - Kernels are chosen and validated for 1356 configs.
  - 2837 fp16 configs
    - Kernels benchmarked, no Memory Access Failures.
    - Kernels are chosen and validated for 680 configs.
  - 2879 bf16 configs
    - Kernels benchmarked, no Memory Access Failures.
    - Kernels are chosen and validated for 586 configs.
- Performance testing with MIOpenDriver
  - develop 8be2998d7 vs this banch 153d1c05f (all W/As enabled but kernels fixed)
  - MIOPEN_DEBUG_FIND_ONLY_SOLVER=ConvOclDirectFwdGen, MIOPEN_FIND_MODE=normal
  - 7 fp32 configs - no failures, less than 1% perf drop on average
  - 34 fp16 configs - no failures, no performance drops
  - 34 bf16 configs - no failures, no performance drops
  - Logs and scripts available upon request

### gfx906/60, ROCm 5.7.1 docker
- Correctness testing with test_conv2d
  - fp32
    - 2904 kernels benchmarked, no Memory Access Failures.
    - 529 kernels chosen and validated.
  - fp16
    - 3132 kernels benchmarked, no Memory Access Failures.
    - 104 kernels chosen and validated.
  - bf16
    - 3153 kernels benchmarked, no Memory Access Failures.
    - 52 kernels chosen and validated.
- Correctness testing with MIOpenDriver
  - 93 fp32 configs - Ok
  - 93 fp16 configs - Ok
  - 93 bf16 configs - Ok
  - Logs and scripts available upon request

### Example of testing with test_conv2d:
```bash
$ t=test_conv2d m=float \
f=./${t}.${m}.fix.log && \
MIOPEN_FIND_MODE=1 \
MIOPEN_DEBUG_CONV_DIRECT_OCL_FWDGEN=1 \
MIOPEN_DEBUG_FIND_ONLY_SOLVER="ConvOclDirectFwdGen;ConvDirectNaiveConvFwd" \
MIOPEN_LOG_LEVEL=5 \
./bin/${t} --${m} --all --limit 3 --disable-backward-data --disable-backward-weights --disable-verification-cache -v 2>&1 \
| tee ${f} | grep -E "(${t})|(Error)|(FAIL)" --line-buffered | nl ; grep FAIL ${f} ; grep FAIL ${f} | wc -l
$
$ grep "ConvOclDirectFwdGen:" ./test_conv2d.float.fix.log | grep -v Selected | nl > ./test_conv2d.float.fix.log.benchmarked
$ grep "FW Chosen Algorithm: ConvOclDirectFwdGen" ./test_conv2d.float.fix.log | nl > ./test_conv2d.float.fix.log.chosen
```

----
[Attribution] @junliume @JehandadKhan
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/bug
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_high
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/correctness
- Proposed reviewers:
  - @JehandadKhan
  - @junliume

### CODE REVIEW

**Comment by atamazov** [comment]
Hint for reviewers. This is the link that shows only substantial code changes: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2546/files/64f58dd5805bfb8beff2e6738921171e28be24e1

**Comment by atamazov** [comment]
It seems like I have better fix. Let me test it.

**Comment by atamazov** [comment]
@junliume @JehandadKhan PR is ready for review and CI testing.

**Comment by atamazov** [comment]
PR description updated with gfx906 testing results.

**Review by CAHEK7 — APPROVED** [review]

**Comment by junliume** [comment]
@atamazov @cderb @JehandadKhan This PR at a previous commit `25d5dc2` the CI is failing at DB sync stage due to applicability has changed for the solver:
```
[22] Solver is not applicable fdb-key:288-35-35-3x3-384-17-17-4-0x0-2x2-1x1-0-NCHW-BF16-F Solver: ConvOclDirectFwdGen
```

**Comment by junliume** [comment]
> @atamazov @cderb @JehandadKhan This PR at a previous commit `25d5dc2` the CI is failing at DB sync stage due to applicability has changed for the solver:
> 
> ```
> [22] Solver is not applicable fdb-key:288-35-35-3x3-384-17-17-4-0x0-2x2-1x1-0-NCHW-BF16-F Solver: ConvOclDirectFwdGen
> ```

After kicking off CI from the latest commit in this PR, this db unsync issue seems to be resolved already.

**Review by junliume — APPROVED** [review]

**Comment by atamazov** [comment]
@junliume 
> This PR at a previous commit 25d5dc2 the CI is failing at DB sync stage due to applicability has changed for the solver

That was a side effect of the W/A that narrows the applicability of the solver. Now the W/A is replaced with proper fix.

**Pull request merged**
