### PR TITLE
Find 2.0 problem fusing

### PR DESCRIPTION
**Pull request by DrizztDoUrden**
Adds `miopenFuseProblems` under `MIOPEN_BETA_API` since the produced problem does not implement `miopenFindSolutions` yet.

### CODE REVIEW

**Comment by DrizztDoUrden** [comment]
@atamazov

**Review by CAHEK7 — APPROVED** [review]

**Comment by DrizztDoUrden** [comment]
@JehandadKhan @averinevg @atamazov Ping

**Comment by atamazov** [comment]
@DrizztDoUrden Please be patient for a couple of days as I need to work on some other blocking issue

**Comment by DrizztDoUrden** [comment]
Sure

**Comment by DrizztDoUrden** [comment]
@JehandadKhan  @averinevg @atamazov ping

**Review by atamazov — APPROVED** [review]
🟢 LGTM!

**Review by JehandadKhan — APPROVED** [review]

**Review by junliume — APPROVED** [review]

**Pull request merged**
