### PR TITLE
[ROCm 4.3] perf-db update (SWDEV-255703, 257619, 270558)

### PR DESCRIPTION
**Pull request by cderb**
All of ConvHipImplicitGemmBwdDataV4R1Xdlops -- MI-100 only

900_56, 906_60, 908_120:
- http://ontrack-internal.amd.com/browse/SWDEV-255703
- http://ontrack-internal.amd.com/browse/SWDEV-257619
- http://ontrack-internal.amd.com/browse/SWDEV-270558
- http://ontrack-internal.amd.com/browse/SWDEV-256787 (partially; find-db update is still required to resolve)

navi: resnet50, ssd

### CODE REVIEW

**Comment by atamazov** [comment]
@cderb Does this PR resolves http://ontrack-internal.amd.com/browse/SWDEV-256787? I had an impression that it can be resolved by updating the find-db.

**Comment by cderb** [comment]
> @cderb Does this PR resolve http://ontrack-internal.amd.com/browse/SWDEV-256787? I had an impression that it can be resolved by updating the find-db.

I think that will require an update to the find-db as well. The associated algorithms from the configs defined by 256787 have been re-tuned in this PR as a pre-requisite for find-db.

**Comment by atamazov** [comment]
@cderb  Thanks. PR description and title updated.

**Comment by atamazov** [comment]
@cderb Our CI does not have gfx1030 nodes. I do not have gfx1030 nodes available either so I am unable to test it as well. Could you please outline (in the PR decsription) how this PR was tested with gfx1030? Thanks.

**Comment by atamazov** [comment]
I've tested performance of this on gfx906/60 with ROCm 4.0 (93 FP32 configs, 93 FP16 configs, 93 FP16 configs) and do not observe performance regressions.

**Review by atamazov — APPROVED** [review]
LGTM but I still need an answer for https://github.com/ROCmSoftwarePlatform/MIOpen/pull/907#issuecomment-833919698

**Comment by atamazov** [comment]
@JehandadKhan Please approve and then let's merge this, thanks.

**Pull request merged**
