### PR TITLE
Full blown fix for PR #1681 "Performance drops after PR 1634"

### PR DESCRIPTION
**Pull request by atamazov**
The effect of this PR is reduction of host-size overhead related to ConvBinWinogradRxSf2x3 and ConvBinWinogradRxSf2x3g1 for non-group Forward and Backward convolutions, which may improve the so-called Initial Iteration Time.

Achieved by making the (tunable) ConvBinWinogradRxSf2x3 non-applicable for the above configs. The "g1" solver can do the same job with the same performance, and it does not require tuning. Therefore the library does not need to access perf-db, and this saves some time.

## Details

- [find-db] Replaced ConvBinWinogradRxSf2x3 by ConvBinWinogradRxSf2x3g1 for non-group Fwd/Bwd (see #1681)
- [find-db] Replaced ConvBinWinogradRxSf2x3g1 by ConvBinWinogradRxSf2x3 for group WrW (see #1735)
  - ℹ️ Tunable f2x3 can be more efficient than non-tunable "g1" solver for all group convolutions and for non-group WrW.
- Enabled ConvBinWinogradRxSf2x3g1 for WrW to avoid perf regressions due to weird f2x3 tuning values in the system perf-db (caught for MI60)
  - Explanation and some discussion at https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1735/files#r968772575
- Disabled `WORKAROUND_ISSUE_1681`
  - ⚠️ W/A is not fully removed because it is possible that "incorrect" find-db records may get back in the future, after porting of tuning results from release branch to develop (see https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1681#issuecomment-1210524707). The release branch does not contain this PR, and that is why tuning results may get problematic records again. If this happens, the issue could be quickly camouflaged by enabling the W/A again. However I would prefer fixing find-db, which is very easy with regexp.

## 🌀 Local performance & correctness testing

- Radeon VII, ROCm 5.0
- _**Databases borrowed from MI60**_
- ___All solvers except ConvBinWinogradRxSf2x3 and ConvBinWinogradRxSf2x3g1 disabled.___
- 93 known FP32 convolution configs
- Default Find mode, Normal Find mode, Immediate mode, with and without re-tuning
- HIP backend
- Develop vs this PR

  | GPU time | Wall time | Aux wall time
-- | -- | -- | --
Find API, default databases | 0% | 0% | 480%
Find API, Normal mode (1), default   databases | 0% | 0% | 380%
Immediate mode API, default databases | 0% | 0% | 530%
Find API, Normal mode (1), after tuning | 0% | 0% | 46% *
Immediate mode API, after tuning | 0% | 0% | 0%

`*` Relatively smaller gain vs default databases is because of smaller size of user perf-db vs system perf-db.

⚠️ Please do not be fooled by high improvement of Aux Wall time -- this is so as long as _only Winograds_ are enabled. When/if _all solvers_ enabled, the gain is expected to become much smaller.

----
@junliume @JehandadKhan `urgency_normal`, `performance`, `value_unknown`

### CODE REVIEW

**Comment by atamazov** [comment]
@Slimakanzer Please review

**Comment by junliume** [comment]
@atamazov could you merge the latest `develop` into your branch? I will kick off the CI pipeline again.

**Comment by atamazov** [comment]
@junliume Done!

**Comment by atamazov** [comment]
@JehandadKhan @cderb 
> This PR changes the applicability of a solver which must be synced with Tuna.

Excuse me, but I am not fully aware of the _tuning process_ currently in use. Shall library developers explicitly inform Tuna team when applicability changed? 

> Please revert the Find DB changes so that these can be added from Tuna later.

These find-db changes prevent performance drop and must arrive into repo in the same commit (or we must declare moratorium on promoting develop to Staging until PR with new databases from Tuna are merged in). Otherwise we may encounter perf drops in Staging or in Master.

But there is nothing that prevents Tuna from updating databases again, later. IIRC the databases in develop are pretty old and refreshing them is definitely worth to do.

Or maybe you need something "cherry-pickable" for release branch (without merge conflicts with databases updated there)? Just let me know branch name and I will prepare dedicated PR for that, thanks.

**Comment by atamazov** [comment]
@junliume @JehandadKhan 🏓

**Comment by atamazov** [comment]
expected merge conflicts after #1760, wait a bit til I resolve...

**Comment by atamazov** [comment]
Merge conflicts resolved. Fixes from commits (01) and (02) reapplied to gfx1030_36.HIP.fdb.txt.

**Comment by atamazov** [comment]
@junliume @JehandadKhan 

> @atamazov could you remove changes made to `gfx908*`, `gfx90a*`, and `gfx10*`? 

NO, because merging this without these changes would lead to performance drop:

>> These find-db changes prevent performance drop and must arrive into repo in the same commit (or we must declare moratorium on promoting develop to Staging until PR with new databases from Tuna are merged in). Otherwise we may encounter perf drops in Staging or in Master.

_From https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1747#issuecomment-1246037559_

> These will be covered by the MITuna's tuning processes. Thanks!

I have to repeat that I am not fully aware of the tuning process currently in use. Especially for develop.

The tuning process should be performed with fixed version of MIOpen. This is a kind of chicken-egg problem, but the fixed databases from this PR resolve it.

**Comment by atamazov** [comment]
@junliume 
> @atamazov could you remove changes made to `gfx908*`, `gfx90a*`, and `gfx10*`? 

If you need something "cherry-pickable" for the release branch (without merge conflicts with databases updated there), then just let me know branch name and I will prepare dedicated PR for that, thanks.

**Comment by atamazov** [comment]
🏓 @junliume ping. Maybe it is worth to first merge databases from 5.3 release into develop. Then I will resolve conflicts (e.g. fix databases) in this branch once again; this is easy to do for me.

**Comment by junliume** [comment]
> 🏓 @junliume ping. Maybe it is worth to first merge databases from 5.3 release into develop. Then I will resolve conflicts (e.g. fix databases) in this branch once again; this is easy to do for me.

@JehandadKhan could MITuna provide more details on the plan?

**Comment by JehandadKhan** [comment]
@cderb  Can you please provide an estimate as to when you will be able to get this done ?

**Comment by junliume** [comment]
> @cderb Can you please provide an estimate as to when you will be able to get this done ?

Ping @cderb is this PR been replaced by #1810?

**Comment by atamazov** [comment]
#1810 does not contain find-db updates. It is unlikely that it came from 5.3 release.

**Comment by atamazov** [comment]
@junliume I see conflicts; will resolve & update PR today.

**Comment by atamazov** [comment]
Merge conflicts resolved. Fixes reapplied where necessary.

**Comment by atamazov** [comment]
Oops, wait, fixes NOT reapplied yet

**Comment by atamazov** [comment]
Done.

**Comment by atamazov** [comment]
Conflicts resolved again

**Comment by cderb** [comment]
Tuning update #1818 made changes to gfx90878, gfx90a68, gfx9086e databases. Will cause some merging difficulties.

**Comment by atamazov** [comment]
@cderb Thanks, resolved 5 hrs ago ;)

**Review by junliume — APPROVED** [review]

**Comment by atamazov** [comment]
@junliume 👍

**Pull request merged**
