### PR TITLE
[NFC] The third batchnorm solver

### PR DESCRIPTION
**Pull request by DrizztDoUrden**
This implements the third bnorm solver.

Also, I realized that I have accidentally reverted their names initially, but otherwise the code was still correct. This only affects logging, because BN does not use find-db and perf-db.

My tests passed, running ones provided by @muralinr currently. I will provide an update on their results today.

### CODE REVIEW

**Review by muralinr — COMMENTED** [review]
Code changes look good.  I am waiting for performance test results for sample network configs..

**Review by atamazov — APPROVED** [review]
Very good.

**Comment by DrizztDoUrden** [comment]
Damn, I have accidentally run your configs on spatial. Would get results before your tomorrow morning probably.

**Comment by muralinr** [comment]
> Damn, I have accidentally run your configs on spatial. Would get results before your tomorrow morning probably.

Sure. Thank you

**Comment by DrizztDoUrden** [comment]
> > Damn, I have accidentally run your configs on spatial. Would get results before your tomorrow morning probably.
> 
> Sure. Thank you

Passed.

**Comment by muralinr** [comment]
> > > Damn, I have accidentally run your configs on spatial. Would get results before your tomorrow morning probably.
> > 
> > 
> > Sure. Thank you
> 
> Passed.

Is there any performance impact?

**Comment by DrizztDoUrden** [comment]
> > > > Damn, I have accidentally run your configs on spatial. Would get results before your tomorrow morning probably.
> > > 
> > > 
> > > Sure. Thank you
> > 
> > 
> > Passed.
> 
> Is there any performance impact?

No non-marginal difference, as expected.

**Review by muralinr — APPROVED** [review]
I approve this PR as there are no functional and performance issues.

**Review by junliume — APPROVED** [review]

**Pull request merged**
