### PR TITLE
Argmin enhancement in case of inner dim reduce 

### PR DESCRIPTION
**Pull request by seungmanhan**
- Fix bfloat16 error in argmax
- Added argmin operation and kernel with solver
- Added driver test and gtest for argmin
- Compared to ROCm pytorch, there is a performance improvement when argmin is performed on the inner dim rather than the last dim

<details><summary>float16</summary>

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>

<body link="#467886" vlink="#96607D">

op_name | dtype | size | model | dim | direction | ROCm pytorch | MIOpen HIP | Improvement
-- | -- | -- | -- | -- | -- | -- | -- | --
Argmin | float16 | [16 21 513 513] | deeplabv3m | 1 | fwd | 835682 | 254739 | 3.28
Argmin | float16 | [24 21 513 513] | deeplabv3r | 1 | fwd | 1243250 | 378366 | 3.29
Argmin | float16 | [64 21 230 333] | fcn_resnet_lraspp | 1 | fwd | 1112466 | 291859 | 3.81
Argmin | float16 | [64 21 240 240] | fcn_resnet_lraspp | 1 | fwd | 843330 | 217423 | 3.88
Argmin | float16 | [64 21 176 174] | fcn_resnet_lraspp | 1 | fwd | 478241 | 124285 | 3.85
Argmin | float16 | [64 21 269 332] | fcn_resnet_lraspp | 1 | fwd | 1396003 | 342455 | 4.08
Argmin | float16 | [64 21 208 320] | fcn_resnet_lraspp | 1 | fwd | 968866 | 250027 | 3.88
Argmin | float16 | [64 21 213 273] | fcn_resnet_lraspp | 1 | fwd | 732369 | 226045 | 3.24
Argmin | float16 | [64 21 275 324] | fcn_resnet_lraspp | 1 | fwd | 1393987 | 341744 | 4.08
Argmin | float16 | [64 21 151 191] | fcn_resnet_lraspp | 1 | fwd | 377265 | 117992 | 3.20
Argmin | float16 | [64 21 281 255] | fcn_resnet_lraspp | 1 | fwd | 892626 | 273814 | 3.26
Argmin | float16 | [64 21 274 266] | fcn_resnet_lraspp | 1 | fwd | 1140066 | 269814 | 4.23
Argmin | float16 | [64 21 215 288] | fcn_resnet_lraspp | 1 | fwd | 954354 | 237459 | 4.02
Argmin | float16 | [1 21 366 500] | stdc | 1 | fwd | 49488 | 15804 | 3.13
Argmin | float16 | [1 21 335 500] | stdc | 1 | fwd | 47472 | 15626 | 3.04
Argmin | float16 | [1 21 333 500] | stdc | 1 | fwd | 47232 | 15786 | 2.99
Argmin | float16 | [1 21 375 500] | stdc | 1 | fwd | 51392 | 15857 | 3.24
Argmin | float16 | [1 21 500 334] | stdc | 1 | fwd | 47328 | 15893 | 2.98
Argmin | float16 | [1 21 332 500] | stdc | 1 | fwd | 47296 | 14808 | 3.19
Argmin | float16 | [32 21 256 256] | unet | 1 | fwd | 480369 | 126542 | 3.80
Argmin | float16 | [7 21 513 513] | deeplabv3r | 1 | fwd | 382241 | 114863 | 3.33
Argmin | float16 | [14 21 513 513] | deeplabv3r | 1 | fwd | 746849 | 222365 | 3.36
Argmin | float16 | [64 21 151 174] | fcn_resnet_lraspp | 1 | fwd | 385569 | 107503 | 3.59
Argmin | float16 | [64 21 200 224] | fcn_resnet_lraspp | 1 | fwd | 653905 | 172161 | 3.80
Argmin | float16 | [47 21 196 299] | fcn_resnet_lraspp | 1 | fwd | 675009 | 169192 | 3.99
Argmin | float16 | [54 21 196 299] | fcn_resnet_lraspp | 1 | fwd | 774513 | 192854 | 4.02
Argmin | float16 | [15 21 256 256] | unet | 1 | fwd | 232177 | 61280 | 3.79
Argmin | float16 | [22 21 256 256] | unet | 1 | fwd | 334976 | 89049 | 3.76
Argmin | float16 | [21 412 500] | unet | 0 | fwd | 52976 | 15680 | 3.38
Argmin | float16 | [21 230 500] | unet | 0 | fwd | 39472 | 15004 | 2.63
Argmin | float16 | [21 333 500] | unet | 0 | fwd | 46704 | 15697 | 2.98
Argmin | float16 | [21 332 500] | unet | 0 | fwd | 46480 | 15608 | 2.98
Argmin | float16 | [21 375 500] | unet | 0 | fwd | 49424 | 15804 | 3.13
Argmin | float16 | [21 370 500] | unet | 0 | fwd | 48928 | 15431 | 3.17
Argmin | float16 | [21 500 375] | unet | 0 | fwd | 49760 | 15893 | 3.13
Argmin | float16 | [21 500 486] | unet | 0 | fwd | 60160 | 22026 | 2.73
Argmin | float16 | [21 334 500] | unet | 0 | fwd | 46880 | 15911 | 2.95
Argmin | float16 | [21 281 500] | unet | 0 | fwd | 42336 | 15449 | 2.74
Argmin | float16 | [21 335 500] | unet | 0 | fwd | 46816 | 15271 | 3.07
Argmin | float16 | [21 336 500] | unet | 0 | fwd | 46288 | 15537 | 2.98
Argmin | float16 | [21 500 333] | unet | 0 | fwd | 46672 | 15840 | 2.95
Argmin | float16 | [21 331 500] | unet | 0 | fwd | 46672 | 15733 | 2.97
Argmin | float16 | [21 343 500] | unet | 0 | fwd | 47744 | 14844 | 3.22
Argmin | float16 | [21 500 334] | unet | 0 | fwd | 46464 | 16035 | 2.90
Argmin | float16 | [21 500 422] | unet | 0 | fwd | 54144 | 16391 | 3.30
Argmin | float16 | [21 366 500] | unet | 0 | fwd | 48496 | 14808 | 3.27

</body>

</html>

</details>
<details><summary>float32</summary>

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>

<body link="#467886" vlink="#96607D">

op_name | dtype | size | model | dim | direction | ROCm pytorch | MIOpen HIP | Improvement
-- | -- | -- | -- | -- | -- | -- | -- | --
Argmin | float32 | [16 21 513 513] | deeplabv3m | 1 | fwd | 1088290 | 361424 | 3.01
Argmin | float32 | [24 21 513 513] | deeplabv3r | 1 | fwd | 1614915 | 546793 | 2.95
Argmin | float32 | [64 21 230 333] | fcn_resnet_lraspp | 1 | fwd | 1369826 | 406313 | 3.37
Argmin | float32 | [64 21 240 240] | fcn_resnet_lraspp | 1 | fwd | 1084050 | 272854 | 3.97
Argmin | float32 | [64 21 176 174] | fcn_resnet_lraspp | 1 | fwd | 597409 | 163663 | 3.65
Argmin | float32 | [64 21 269 332] | fcn_resnet_lraspp | 1 | fwd | 1781539 | 480127 | 3.71
Argmin | float32 | [64 21 208 320] | fcn_resnet_lraspp | 1 | fwd | 1246050 | 315255 | 3.95
Argmin | float32 | [64 21 213 273] | fcn_resnet_lraspp | 1 | fwd | 942658 | 307326 | 3.07
Argmin | float32 | [64 21 275 324] | fcn_resnet_lraspp | 1 | fwd | 1775459 | 481477 | 3.69
Argmin | float32 | [64 21 151 191] | fcn_resnet_lraspp | 1 | fwd | 477089 | 156729 | 3.04
Argmin | float32 | [64 21 281 255] | fcn_resnet_lraspp | 1 | fwd | 1154818 | 381619 | 3.03
Argmin | float32 | [64 21 274 266] | fcn_resnet_lraspp | 1 | fwd | 1450947 | 393673 | 3.69
Argmin | float32 | [64 21 215 288] | fcn_resnet_lraspp | 1 | fwd | 1213506 | 324268 | 3.74
Argmin | float32 | [1 21 366 500] | stdc | 1 | fwd | 57632 | 17475 | 3.30
Argmin | float32 | [1 21 335 500] | stdc | 1 | fwd | 54032 | 17582 | 3.07
Argmin | float32 | [1 21 333 500] | stdc | 1 | fwd | 53920 | 17351 | 3.11
Argmin | float32 | [1 21 375 500] | stdc | 1 | fwd | 59280 | 17884 | 3.31
Argmin | float32 | [1 21 500 334] | stdc | 1 | fwd | 54064 | 16906 | 3.20
Argmin | float32 | [1 21 332 500] | stdc | 1 | fwd | 54384 | 16515 | 3.29
Argmin | float32 | [32 21 256 256] | unet | 1 | fwd | 608193 | 158116 | 3.85
Argmin | float32 | [7 21 513 513] | deeplabv3r | 1 | fwd | 507889 | 156161 | 3.25
Argmin | float32 | [14 21 513 513] | deeplabv3r | 1 | fwd | 972978 | 315308 | 3.09
Argmin | float32 | [64 21 151 174] | fcn_resnet_lraspp | 1 | fwd | 465601 | 141850 | 3.28
Argmin | float32 | [64 21 200 224] | fcn_resnet_lraspp | 1 | fwd | 837698 | 210187 | 3.99
Argmin | float32 | [47 21 196 299] | fcn_resnet_lraspp | 1 | fwd | 853682 | 227948 | 3.75
Argmin | float32 | [54 21 196 299] | fcn_resnet_lraspp | 1 | fwd | 979650 | 261494 | 3.75
Argmin | float32 | [15 21 256 256] | unet | 1 | fwd | 288161 | 74667 | 3.86
Argmin | float32 | [22 21 256 256] | unet | 1 | fwd | 419857 | 106152 | 3.96
Argmin | float32 | [21 412 500] | unet | 0 | fwd | 62928 | 18275 | 3.44
Argmin | float32 | [21 230 500] | unet | 0 | fwd | 43520 | 16249 | 2.68
Argmin | float32 | [21 333 500] | unet | 0 | fwd | 53392 | 17368 | 3.07
Argmin | float32 | [21 332 500] | unet | 0 | fwd | 53056 | 17137 | 3.10
Argmin | float32 | [21 375 500] | unet | 0 | fwd | 58192 | 17511 | 3.32
Argmin | float32 | [21 370 500] | unet | 0 | fwd | 57344 | 17173 | 3.34
Argmin | float32 | [21 500 375] | unet | 0 | fwd | 58400 | 17831 | 3.28
Argmin | float32 | [21 500 486] | unet | 0 | fwd | 75776 | 26133 | 2.90
Argmin | float32 | [21 334 500] | unet | 0 | fwd | 53504 | 17333 | 3.09
Argmin | float32 | [21 281 500] | unet | 0 | fwd | 46208 | 15964 | 2.89
Argmin | float32 | [21 335 500] | unet | 0 | fwd | 53680 | 17351 | 3.09
Argmin | float32 | [21 336 500] | unet | 0 | fwd | 51568 | 16071 | 3.21
Argmin | float32 | [21 500 333] | unet | 0 | fwd | 53440 | 16995 | 3.14
Argmin | float32 | [21 331 500] | unet | 0 | fwd | 53712 | 17582 | 3.05
Argmin | float32 | [21 343 500] | unet | 0 | fwd | 55680 | 17244 | 3.23
Argmin | float32 | [21 500 334] | unet | 0 | fwd | 53520 | 17280 | 3.10
Argmin | float32 | [21 500 422] | unet | 0 | fwd | 64976 | 18364 | 3.54
Argmin | float32 | [21 366 500] | unet | 0 | fwd | 56688 | 17582 | 3.22

</body>

</html>

</details>
<details><summary>bfloat16</summary>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>

<body link="#467886" vlink="#96607D">

op_name | dtype | size | model | dim | direction | ROCm pytorch | MIOpen HIP | Improvement
-- | -- | -- | -- | -- | -- | -- | -- | --
Argmin | bfloat16 | [16 21 513 513] | deeplabv3m | 1 | fwd | 837025 | 254419 | 3.29
Argmin | bfloat16 | [24 21 513 513] | deeplabv3r | 1 | fwd | 1246786 | 378722 | 3.29
Argmin | bfloat16 | [64 21 230 333] | fcn_resnet_lraspp | 1 | fwd | 1119810 | 291681 | 3.84
Argmin | bfloat16 | [64 21 240 240] | fcn_resnet_lraspp | 1 | fwd | 848722 | 217245 | 3.91
Argmin | bfloat16 | [64 21 176 174] | fcn_resnet_lraspp | 1 | fwd | 483729 | 124321 | 3.89
Argmin | bfloat16 | [64 21 269 332] | fcn_resnet_lraspp | 1 | fwd | 1406178 | 341921 | 4.11
Argmin | bfloat16 | [64 21 208 320] | fcn_resnet_lraspp | 1 | fwd | 974866 | 249885 | 3.90
Argmin | bfloat16 | [64 21 213 273] | fcn_resnet_lraspp | 1 | fwd | 741361 | 226010 | 3.28
Argmin | bfloat16 | [64 21 275 324] | fcn_resnet_lraspp | 1 | fwd | 1409682 | 341157 | 4.13
Argmin | bfloat16 | [64 21 151 191] | fcn_resnet_lraspp | 1 | fwd | 382176 | 117903 | 3.24
Argmin | bfloat16 | [64 21 281 255] | fcn_resnet_lraspp | 1 | fwd | 899634 | 273459 | 3.29
Argmin | bfloat16 | [64 21 274 266] | fcn_resnet_lraspp | 1 | fwd | 1151154 | 269903 | 4.27
Argmin | bfloat16 | [64 21 215 288] | fcn_resnet_lraspp | 1 | fwd | 961634 | 237761 | 4.04
Argmin | bfloat16 | [1 21 366 500] | stdc | 1 | fwd | 48736 | 15964 | 3.05
Argmin | bfloat16 | [1 21 335 500] | stdc | 1 | fwd | 47152 | 15591 | 3.02
Argmin | bfloat16 | [1 21 333 500] | stdc | 1 | fwd | 47056 | 14791 | 3.18
Argmin | bfloat16 | [1 21 375 500] | stdc | 1 | fwd | 50160 | 15982 | 3.14
Argmin | bfloat16 | [1 21 500 334] | stdc | 1 | fwd | 46832 | 15360 | 3.05
Argmin | bfloat16 | [1 21 332 500] | stdc | 1 | fwd | 47088 | 15502 | 3.04
Argmin | bfloat16 | [32 21 256 256] | unet | 1 | fwd | 484257 | 125795 | 3.85
Argmin | bfloat16 | [7 21 513 513] | deeplabv3r | 1 | fwd | 382481 | 114738 | 3.33
Argmin | bfloat16 | [14 21 513 513] | deeplabv3r | 1 | fwd | 750754 | 222472 | 3.37
Argmin | bfloat16 | [64 21 151 174] | fcn_resnet_lraspp | 1 | fwd | 389105 | 107360 | 3.62
Argmin | bfloat16 | [64 21 200 224] | fcn_resnet_lraspp | 1 | fwd | 661330 | 171983 | 3.85
Argmin | bfloat16 | [47 21 196 299] | fcn_resnet_lraspp | 1 | fwd | 683825 | 169032 | 4.05
Argmin | bfloat16 | [54 21 196 299] | fcn_resnet_lraspp | 1 | fwd | 783202 | 192427 | 4.07
Argmin | bfloat16 | [15 21 256 256] | unet | 1 | fwd | 232721 | 61582 | 3.78
Argmin | bfloat16 | [22 21 256 256] | unet | 1 | fwd | 338145 | 89173 | 3.79
Argmin | bfloat16 | [21 412 500] | unet | 0 | fwd | 53872 | 15840 | 3.40
Argmin | bfloat16 | [21 230 500] | unet | 0 | fwd | 39792 | 15129 | 2.63
Argmin | bfloat16 | [21 333 500] | unet | 0 | fwd | 46464 | 15751 | 2.95
Argmin | bfloat16 | [21 332 500] | unet | 0 | fwd | 46368 | 15946 | 2.91
Argmin | bfloat16 | [21 375 500] | unet | 0 | fwd | 49328 | 15964 | 3.09
Argmin | bfloat16 | [21 370 500] | unet | 0 | fwd | 48528 | 15982 | 3.04
Argmin | bfloat16 | [21 500 375] | unet | 0 | fwd | 49120 | 15964 | 3.08
Argmin | bfloat16 | [21 500 486] | unet | 0 | fwd | 60144 | 22080 | 2.72
Argmin | bfloat16 | [21 334 500] | unet | 0 | fwd | 46496 | 15644 | 2.97
Argmin | bfloat16 | [21 281 500] | unet | 0 | fwd | 42176 | 15875 | 2.66
Argmin | bfloat16 | [21 335 500] | unet | 0 | fwd | 47904 | 15413 | 3.11
Argmin | bfloat16 | [21 336 500] | unet | 0 | fwd | 46224 | 15840 | 2.92
Argmin | bfloat16 | [21 500 333] | unet | 0 | fwd | 47888 | 15733 | 3.04
Argmin | bfloat16 | [21 331 500] | unet | 0 | fwd | 47824 | 15751 | 3.04
Argmin | bfloat16 | [21 343 500] | unet | 0 | fwd | 46992 | 15715 | 2.99
Argmin | bfloat16 | [21 500 334] | unet | 0 | fwd | 46400 | 15697 | 2.96
Argmin | bfloat16 | [21 500 422] | unet | 0 | fwd | 53472 | 15840 | 3.38
Argmin | bfloat16 | [21 366 500] | unet | 0 | fwd | 48336 | 15715 | 3.08

</body>

</html>

</details>

- Average over all cases
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">

</head>

<body link="#467886" vlink="#96607D">

Type | average
-- | --
float16 | 3.36
float32 | 3.34
bfloat16 | 3.36

</body>

</html>

### CODE REVIEW

**Comment by CAHEK7** [comment]
We've already got argmax and the only difference is a comparison predicate, why it is a whole separated solver with dedicated kernel and so on? Should everything be identical except `min` and `max`?

**Comment by seungmanhan** [comment]
> We've already got argmax and the only difference is a comparison predicate, why it is a whole separated solver with dedicated kernel and so on? Should everything be identical except `min` and `max`?

First, I separated argmax and argmin because they are different operations in pytorch. Please give your opinion on whether it is better to integrate by adding options or to separate them. (As a result of the reference performance comparison, there was no performance difference between argmax and argmin as expected.)
In the case of max and min, which I am currently working on, there is not much difference from argmax, so I am wondering whether it would be a good idea to integrate them. Please give your opinion on this, too.

**Comment by CAHEK7** [comment]
From the API point of view, argmin and argmax are separated operation, but they have lots of identical code.
Kernel can be the same, with two `__global__` functions - one calls `__device__` with `less` operation and another with `greater`.
Most of the host code can be placed into a common header, unified and reused.
Driver and verification code can literally be the same.

**Comment by seungmanhan** [comment]
> From the API point of view, argmin and argmax are separated operation, but they have lots of identical code. Kernel can be the same, with two `__global__` functions - one calls `__device__` with `less` operation and another with `greater`. Most of the host code can be placed into a common header, unified and reused. Driver and verification code can literally be the same.

Are you talking about working in a way that the externally exposed API exists separately and the internal code is shared?
The plan is to proceed with integration work on the reduction ops after adding all the ops of moreh. (This was also discussed with AMD's PM.)
I may change the order of tasks if integration takes priority.

**Comment by CAHEK7** [comment]
@junliume @JehandadKhan could you prioritize of clarify?
I'm a bit unsure about lots if identical code in the repo. Even this PR shows that in case of any changes it has to be fixed twice.

**Comment by atamazov** [comment]
@seungmanhan https://github.com/ROCm/MIOpen/labels/value_high Superficial comment: If argmin and argmax are very similar, then existing argmax should be extended with "min" functionality. Thus we avoid duplication of code (which is actually an implicit dependence and therefore considered as a serious quality issue).

**Comment by atamazov** [comment]
@seungmanhan The above applies to the API layer as well.

**Comment by seungmanhan** [comment]
First, I will close this PR and upload a new PR incorporating argmax, argmin, max, and min.

**Comment by atamazov** [comment]
@seungmanhan Of course, this is up to you, but I don't see anything that could stop you from doing necessary changes right in this branch and reopening/updating this PR.

**Pull request closed without merging**
