### PR TITLE
[perf-db] Purge invalid entries for ConvHipImplicitGemmBwdDataV4R1Xdlops (SWDEV-281591, SWDEV-289743)

### PR DESCRIPTION
**Pull request by JehandadKhan**
This PR resolves
https://ontrack-internal.amd.com/browse/SWDEV-288976

### CODE REVIEW

**Comment by junliume** [comment]
@JehandadKhan DB updates into staging branch directly? Will merge down back to develop?

**Comment by atamazov** [comment]
This is fine, I will port this to develop later.

**Comment by atamazov** [comment]
@JehandadKhan please manually run this on CI (branches that begin with "release" are filtered out from Jenkins' discovery process).

**Comment by atamazov** [comment]
@JehandadKhan 
> This PR resolves https://ontrack-internal.amd.com/browse/SWDEV-288976

Yes, but this ticket is for 4.4. WRT 4.3, this PR should resolve https://ontrack-internal.amd.com/browse/SWDEV-281591 and https://ontrack-internal.amd.com/browse/SWDEV-289743, I guess.

**Comment by atamazov** [comment]
:cyclone: Smoke test for performance is running...

**Review by atamazov — APPROVED** [review]
Smoke perf test passed

**Pull request merged**
