### PR TITLE
[NFC][Quality] Rename MIOPEN_ENV back to ENV

### PR DESCRIPTION
**Pull request by atamazov**
Code quality only fix, No Functional Changes

- Resolves https://github.com/ROCm/MIOpen/pull/2961#pullrequestreview-2063334623
- Depends on c85aa7cc177fdc69ec5a7949fddad103d43cbcc6 from #2974

----
[Attribution] @junliume @JehandadKhan
- https://github.com/ROCm/MIOpen/labels/quality
- Proposed reviewers: @bghimireamd @junliume

### CODE REVIEW

**Comment by bghimireamd** [comment]
LGTM

**Comment by junliume** [comment]
@atamazov would not `MIOPEN_ENV` be safer than `ENV`?

**Comment by atamazov** [comment]
> @atamazov would not `MIOPEN_ENV` be safer than `ENV`?

Basically, yes, but only if other components (used by us) export inadequate entities (i.e. contains bugs in their public APIs). But in this specific case I would prefer to keep the name of the macro as short as possible, as is was designed initially.

**Review by junliume — APPROVED** [review]

**Comment by atamazov** [comment]
@junliume Merge conflicts resolved. Ready for the next CI testing round.

**Comment by averinevg** [comment]
CI restarted

**Review by averinevg — APPROVED** [review]
LGTM

**Pull request merged**
