### PR TITLE
Remove unused hip-config.cmake

### PR DESCRIPTION
**Pull request by averinevg**
This file was added just to provide workarounds for hip-clang for rocm 3.5. There has been fixes since this, so we should no longer need this.

[Source](https://github.com/ROCm/MIOpen/pull/2091#discussion_r1165858694)

### CODE REVIEW

**Review by CAHEK7 — APPROVED** [review]

**Review by junliume — APPROVED** [review]

**Comment by junliume** [comment]
@averinevg @CAHEK7 @BrianHarrisonAMD this might be problematic because:
https://github.com/ROCm/MIOpen/blob/35192f8699d34c0f3355497a7b054dbf9177e94c/cmake/hip-config.cmake#L82

Actually, the above line needs to be updated or else this warning will be emitted multiple times during build steps:
```
2024-09-16T21:54:04.732797101Z CMake Warning (dev) at /opt/rocm-6.3.0.1/lib/cmake/hip/hip-config-amd.cmake:86 (message):
2024-09-16T21:54:04.732828161Z    AMDGPU_TARGETS was not set, and system GPU detection was unsuccsesful.
2024-09-16T21:54:04.732837611Z    
2024-09-16T21:54:04.732845691Z    The amdgpu-arch tool failed:
2024-09-16T21:54:04.732853241Z    Error: 'Failed to get device count'
2024-09-16T21:54:04.732860532Z    Output: ''
2024-09-16T21:54:04.732867692Z    
2024-09-16T21:54:04.732874832Z    As a result, --offload-arch will not be set for subsuqent
2024-09-16T21:54:04.732882232Z    compilations, and the default architecture (gfx906) will be used
```

**Comment by BrianHarrisonAMD** [comment]
> @averinevg @CAHEK7 @BrianHarrisonAMD this might be problematic because:
> 
> https://github.com/ROCm/MIOpen/blob/35192f8699d34c0f3355497a7b054dbf9177e94c/cmake/hip-config.cmake#L82
> 
> Actually, the above line needs to be updated or else this warning will be emitted multiple times during build steps:
> 
> ```
> 2024-09-16T21:54:04.732797101Z CMake Warning (dev) at /opt/rocm-6.3.0.1/lib/cmake/hip/hip-config-amd.cmake:86 (message):
> 2024-09-16T21:54:04.732828161Z    AMDGPU_TARGETS was not set, and system GPU detection was unsuccsesful.
> 2024-09-16T21:54:04.732837611Z    
> 2024-09-16T21:54:04.732845691Z    The amdgpu-arch tool failed:
> 2024-09-16T21:54:04.732853241Z    Error: 'Failed to get device count'
> 2024-09-16T21:54:04.732860532Z    Output: ''
> 2024-09-16T21:54:04.732867692Z    
> 2024-09-16T21:54:04.732874832Z    As a result, --offload-arch will not be set for subsuqent
> 2024-09-16T21:54:04.732882232Z    compilations, and the default architecture (gfx906) will be used
> ```

I think it would make sense to add the following to the regular CMake to prevent the warning:

```
# Add universal GPU targets to prevent CMake warning
set(AMDGPU_TARGETS "gfx908;gfx90a;gfx940;gfx941;gfx942;gfx1030;gfx1100;gfx1101;gfx1102;gfx1200;gfx1201" CACHE STRING "AMD GPU targets to compile for")
set(GPU_TARGETS "${AMDGPU_TARGETS}" CACHE STRING "GPU targets to compile for")
```

And also remove this file as part of this PR.

**Comment by junliume** [comment]
@averinevg could you help to make the necessary change as suggested above if you also agree? Thanks!

**Comment by averinevg** [comment]
> @averinevg could you help to make the necessary change as suggested above if you also agree? Thanks!

@junliume @BrianHarrisonAMD I don't see the warning when I build the library on my test PC. I also can't find it in the CI logs. Could you please provide instructions on how I can reproduce it?

**Pull request merged**
