### PR TITLE
[Tuning][90a] Perf and Find Update

### PR DESCRIPTION
**Pull request by cderb**
using: rocm 4.5
perf db using miopen: '19defc31e' (develop 11/04)
find db using miopen: '0b3ea328a' (develop 11/08)

### CODE REVIEW

**Comment by junliume** [comment]
@cderb @JehandadKhan  would this PR have conflict with https://github.com/ROCmSoftwarePlatform/MIOpen-internal/issues/4 ? We intend to have them in develop together.

**Comment by cderb** [comment]
> @cderb @JehandadKhan would this PR have conflict with [ROCmSoftwarePlatform/MIOpen-internal#4](https://github.com/ROCmSoftwarePlatform/MIOpen-internal/issues/4) ? We intend to have them in develop together.

If there is a db update involved to disable the solver, then these could overlap.

**Review by atamazov — CHANGES_REQUESTED** [review]
We are going to disable ConvHipImplicitGemmForwardV4R4Xdlops for gfx90a. Let's substitute it with the next fastest iGemm Solver in the gfx90a's find-db.

AFAIU this can be done offline, using Tuna.

**Comment by atamazov** [comment]
@cderb 
> If there is a db update involved to disable the solver

Disabling the Solver does not require db updates. But find-db update may minimize possible perf drops for known configs.

**Comment by atamazov** [comment]
If this PR is targeted to updates related to `ConvAsmImplicitGemmGTCDynamic*XdlopsNHWC` then, strictly speaking, any comments related to `ConvHipImplicitGemmForwardV4R4Xdlops` are off-topic here.

**Comment by cderb** [comment]
They were filtered for in tuning, but it looks like other solvers were re-introduced with the merge. I'll need to prune those.

**Comment by cderb** [comment]
Finished doctoring fdb to use ConvAsmImplicitGemmGTCDynamic%XdlopsNHWC for fp16

**Comment by atamazov** [comment]
_On behalf of @sunway513:_ 

Cherry-picked the tuned perfDB, without setting FIND_MODE, I got massive number of the following warnings:
```
MIOpen(HIP): Warning [FindSolutionImpl] Invalid config loaded from Perf Db: ConvAsmImplicitGemmGTCDynamicBwdXdlopsNHWC: bwd,nhwc,fp32,0,1,128,128,16,32,32,4,1,1,2,2,1,0,4,1,0,1,1,8,1,1,16,1,16,1,1,8,1,1,16,1,16,152. Performance may degrade.
MIOpen(HIP): Warning [FindSolutionImpl] Invalid config loaded from Perf Db: ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC: wrw,nhwc,fp32,0,1,128,256,32,32,32,8,1,2,2,2,0,0,2,0,0,1,4,1,4,1,8,1,32,1,4,1,8,1,8,1,32,77. Performance may degrade.
MIOpen(HIP): Warning [FindSolutionImpl] Invalid config loaded from Perf Db: ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC: wrw,nhwc,fp32,0,1,128,256,32,32,32,8,1,2,2,2,0,0,2,0,0,1,4,1,4,1,8,1,32,1,4,1,8,1,8,1,32,77. Performance may degrade.
MIOpen(HIP): Warning [FindSolutionImpl] Invalid config loaded from Perf Db: ConvAsmImplicitGemmGTCDynamicBwdXdlopsNHWC: bwd,nhwc,fp32,0,1,128,128,16,32,32,4,1,1,2,2,1,0,4,1,0,1,1,8,1,1,16,1,16,1,1,8,1,1,16,1,16,152. Performance may degrade.
MIOpen(HIP): Warning [FindSolutionImpl] Invalid config loaded from Perf Db: ConvAsmImplicitGemmGTCDynamicBwdXdlopsNHWC: bwd,nhwc,fp32,0,1,128,128,16,32,32,4,1,1,2,2,1,0,4,1,0,1,1,8,1,1,16,1,16,1,1,8,1,1,16,1,16,152. Performance may degrade.
MIOpen(HIP): Warning [FindSolutionImpl] Invalid config loaded from Perf Db: ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC: wrw,nhwc,fp32,0,1,128,128,16,32,32,8,1,1,2,2,0,0,9,0,0,1,4,1,2,1,4,1,64,1,4,1,2,1,4,1,64,88. Performance may degrade.
MIOpen(HIP): Warning [FindSolutionImpl] Invalid config loaded from Perf Db: ConvAsmImplicitGemmGTCDynamicWrwXdlopsNHWC: wrw,nhwc,fp32,0,1,128,128,16,32,32,8,1,1,2,2,0,0,9,0,0,1,4,1,2,1,4,1,64,1,4,1,2,1,4,1,64,88. Performance may degrade.
```

**Comment by atamazov** [comment]
## Important

The name of the branch is `cderb/tuning_update_4.5.1`. This implies that it is targeted for 4.5.1. In this case, db updates must be done with MIOpen from `release/rocm-rel-4.5-staging`.

@cderb Am I correct and `release/rocm-rel-4.5-staging` was used for tuning?

Updates intended for the release branch may lead to numerous warnings when run with develop branch (like shown above).

**Comment by atamazov** [comment]
@cderb #1212 adds perf-db validation test, but it seems unable to catch gfx90a problems, like [this one](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1271#issuecomment-965086854). Can we fix this?

**Comment by sunway513** [comment]
It might be my "testing error", as our test base right now is ROCm4.3.1 (to get aligned with the previous environment). Let me move the test docker to ROCm4.5 and re-test.

**Comment by cderb** [comment]
> @cderb Am I correct and `release/rocm-rel-4.5-staging` was used for tuning?


Actually it was generated with develop hashes.

**Comment by cderb** [comment]
I'm examine the validation test and add some functionality there if necessary.

**Comment by atamazov** [comment]
> I'm examine the validation test and add some functionality there if necessary.

If you are going to test gfx90a database, then, perhaps you need to tell the library that the device is gfx90a. Otherwise some Solvers become non-applicable and something unusual may happen (like skipping perf-configs for non-applicable solvers, altogether with validation). Just an idea.

**Comment by atamazov** [comment]
@cderb 
> Actually it was generated with develop hashes.

So this is intended for merging into develop only, right?

**Comment by cderb** [comment]
I presume that it is only qualified for develop.

**Comment by cderb** [comment]
Added tuning patch for SSD configs.

**Comment by junliume** [comment]
@cderb @JehandadKhan The latest commit looks mostly incremental, I think we should not need another full round of CI, right?

**Comment by cderb** [comment]
Should pass ci, would benefit from performance test.

**Review by junliume — APPROVED** [review]
CI passed again with the latest updates

**Pull request merged**
