### PR TITLE
[Test][CI][gfx90a] Basic support for gfx90a: Jenkinsfile, dockerfile, unit tests

### PR DESCRIPTION
**Pull request by shaojiewang**

### CODE REVIEW

**Comment by shurale-nkn** [comment]
Jenkins log contains: Method Code Too Large Error
Here are some potential options to resolve this issue:

1. Limit the size of the Jenkinsfile code inside of the brackets by moving code out to shared libraries, or external scripts you call with a sh './myscript' command, as per Pipeline Best Practices
2. Move sections of the Jenkinsfile code out into their own separate methods by doing a groovy method declaration: def $METHOD_NAME(arguments...){}
3. Use the startup argument org.jenkinsci.plugins.pipeline.modeldefinition.parser.RuntimeASTTransformer.SCRIPT_SPLITTING_TRANSFORMATION=true as mentioned in JENKINS-56500

Option number 2 is not suitable for us, since we have already made the code into separate methods.
The simplest would be the 3-rd. But the changes will affect all projects on the Jenkins server

**Comment by junliume** [comment]
@shaojiewang this branch has been squashed and rebased, please **delete** your local branch, re-pull and start from there :) thanks!

**Comment by shaojiewang** [comment]
> @shaojiewang this branch has been squashed and rebased, please **delete** your local branch, re-pull and start from there :) thanks!

ok thanks.

**Comment by junliume** [comment]
@shaojiewang please let the reviewers know when this PR is ready for review. It is currently blocking enabling gfx90a in CI pipeline. Thanks!

**Comment by shaojiewang** [comment]
> @shaojiewang please let the reviewers know when this PR is ready for review. It is currently blocking enabling gfx90a in CI pipeline. Thanks!

 OK. working on it now.

**Comment by shaojiewang** [comment]
I merged develop branch in this PR. It always have a boost error in OpenCL tidy stage. @shurale-nkn could you please help?

**Comment by shaojiewang** [comment]
> Jenkins log contains: Method Code Too Large Error
> Here are some potential options to resolve this issue:
> 
> 1. Limit the size of the Jenkinsfile code inside of the brackets by moving code out to shared libraries, or external scripts you call with a sh './myscript' command, as per Pipeline Best Practices
> 2. Move sections of the Jenkinsfile code out into their own separate methods by doing a groovy method declaration: def $METHOD_NAME(arguments...){}
> 3. Use the startup argument org.jenkinsci.plugins.pipeline.modeldefinition.parser.RuntimeASTTransformer.SCRIPT_SPLITTING_TRANSFORMATION=true as mentioned in JENKINS-56500
> 
> Option number 2 is not suitable for us, since we have already made the code into separate methods.
> The simplest would be the 3-rd. But the changes will affect all projects on the Jenkins server

Thanks I understand. I removed gfx90a from some non-supported tests.

**Comment by shaojiewang** [comment]
I got a ci info like below:
```
There are no nodes with the label ‘rocmtest&&miopen&&gfx90a’
```
Does it means that we do not have a gfx90a node?

**Comment by junliume** [comment]
> I got a ci info like below:
> 
> ```
> There are no nodes with the label ‘rocmtest&&miopen&&gfx90a’
> ```
> 
> Does it means that we do not have a gfx90a node?

Hi @okakarpa, CI pipeline is queued because of the above message. Could you take a look?

**Comment by okakarpa** [comment]
> > > > I got a ci info like below:
> > > > ```
> > > > There are no nodes with the label ‘rocmtest&&miopen&&gfx90a’
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > Does it means that we do not have a gfx90a node?
> > > 
> > > 
> > > Hi @okakarpa, CI pipeline is queued because of the above message. Could you take a look?
> > 
> > 
> > Since we are in testing phase i named the MI200 node label as rocmtest-trial instead of rocmtest , but i changed the label now the job triggered
> > http://micimaster.amd.com/job/MLLibs/job/MIOpen/job/jenkins_and_docker_file_for_90a/7/console
> 
> Still observing: :(
> 
> "[2021-08-12T15:29:43.721Z] gpg: no valid OpenPGP data found."
> 
> http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/jenkins_and_docker_file_for_90a/8/pipeline/56

I made some changes to Docker-file we don't need to enable adding of gpg key if we are setting up rocm through private artifactory

The Docker image is built now and moving forword.

http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/jenkins_and_docker_file_for_90a/9/pipeline

**Comment by shaojiewang** [comment]
I think that rocm4-3 is this address:
```
sh -c 'echo deb [arch=amd64 trusted=yes] http://compute-artifactory.amd.com/artifactory/list/rocm-release-archive-deb/ 4.3 rel-34 > /etc/apt/sources.list.d/rocm.list'
```
has some issue with boost lib.

**Comment by shaojiewang** [comment]
All nodes of label ‘rocmtest-trial&&miopen&&nogpu’ are offline

**Comment by okakarpa** [comment]
> All nodes of label ‘rocmtest-trial&&miopen&&nogpu’ are offline

Use rocmtest-scm-trial label

**Comment by shaojiewang** [comment]
> > All nodes of label ‘rocmtest-trial&&miopen&&nogpu’ are offline
> 
> Use rocmtest-scm-trial label

@okakarpa Hi, should I use this label for all nodes or just for nogpu nodes?

**Comment by okakarpa** [comment]
> > > All nodes of label ‘rocmtest-trial&&miopen&&nogpu’ are offline
> > 
> > 
> > Use rocmtest-scm-trial label
> 
> @okakarpa Hi, should I use this label for all nodes or just for nogpu nodes?

It’s specific to mi200 nodes and branch want to make sure all stages in jenkinsfile should pass on all the nodes

**Comment by shaojiewang** [comment]
seems like ```http://repo.radeon.com/rocm/apt/.apt_4.3/ xenial main``` has boost version issue.

**Comment by junliume** [comment]
@shaojiewang it seems that ROCm 4.3 is required after all, in order to pass unit and future tests. I tried to make build work with ROCm 4.2 but it might not be the right direction :(

Please feel free to revert my changes. Tomorrow I will continue from your work to work on how to make it work with 4.3.

Thanks!

**Comment by shaojiewang** [comment]
> @shaojiewang it seems that ROCm 4.3 is required after all, in order to pass unit and future tests. I tried to make build work with ROCm 4.2 but it might not be the right direction :(

I agree. In this way, we could check whether the other parts of jenkinsfile and dockerfile are right.

> 
> Please feel free to revert my changes. Tomorrow I will continue from your work to work on how to make it work with 4.3.
> 

I agree with these changes.

Thanks a lot.

**Comment by shaojiewang** [comment]
There are no nodes with the label ‘rocmtest-scm-trial&&miopen&&gfx908’

**Comment by okakarpa** [comment]
> There are no nodes with the label ‘rocmtest-scm-trial&&miopen&&gfx908’

Do you need to test on gfx908 ?

**Comment by junliume** [comment]
selective (only gfx90a) tests have passed: http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/jenkins_and_docker_file_for_90a/55/pipeline

Now starting a full scale test ... if you have local branch of jenkins_and_docker_file_for_90a, please delete and re-pull.

**Comment by shaojiewang** [comment]
CI-test is re-started and now running.....
http://micimaster.amd.com/blue/organizations/jenkins/MLLibs%2FMIOpen/detail/jenkins_and_docker_file_for_90a/59/pipeline/59/

**Review by junliume — APPROVED** [review]
CI has passed.
@shurale-nkn @JehandadKhan @okakarpa please review.

**Pull request merged**
