### PR TITLE
[ROCm-cmake] Enable Origin header file dump option for wrapper

### PR DESCRIPTION
**Pull request by arvindcheru**
- Update ROCM-CMAKE Version
- Enable original file dump option for wrapper header to support backward compatibility

### CODE REVIEW

**Comment by junliume** [comment]
@arvindcheru I don't think any problems will be detected in MIOpen CI, but has it been tested against TF/PT builds?

**Comment by arvindcheru** [comment]
> @arvindcheru I don't think any problems will be detected in MIOpen CI, but has it been tested against TF/PT builds?

Thanks for the quick comments. Kindly give some more time and mark this as WIP for now. we are waiting for the rocm-cmake changes and dependencies to finalize

**Comment by arvindcheru** [comment]
> > @arvindcheru I don't think any problems will be detected in MIOpen CI, but has it been tested against TF/PT builds?
> 
> Thanks for the quick comments. Kindly give some more time and mark this as WIP for now. we are waiting for the rocm-cmake changes and dependencies to finalize
Was able to build successfully PT with latest rocm-cmake, miopen (with this change) package installed.

**Comment by junliume** [comment]
@arvindcheru please indicate the urgency level, does this change need to go into ROCm 5.2?

**Comment by arvindcheru** [comment]
> @arvindcheru please indicate the urgency level, does this change need to go into ROCm 5.2?

Yes, this is requested to include for 5.2 (I have tried to update the labels now, Kindly have a look) thanks

**Review by junliume — APPROVED** [review]

**Pull request merged**
