### PR TITLE
Change default find mode to Dynamic Hybrid

### PR DESCRIPTION
**Pull request by JehandadKhan**
This PR changes the default find mode to "DynamicHybrid" also known as Find Mode 5 which would result in reduced initial iteration time on novel networks.

Additional details can be found in Issue #398

### CODE REVIEW

**Comment by atamazov** [comment]
Good! But do we have any results of performance testing of Hybrid vs. DynamicHybrid?

**Comment by JehandadKhan** [comment]
> Good! But do we have any results of performance testing of Hybrid vs. DynamicHybrid?

I have created that PR for this purpose.

**Comment by atamazov** [comment]
@JehandadKhan 
> > Good! But do we have any results of performance testing of Hybrid vs. DynamicHybrid?
> 
> I have created that PR for this purpose.

So we do not have immediate goal to merge it?

Actually I thank that `export MIOPEN_FIND_MODE=DYNAMIC_HYBRID` should be easier to use because:
- you do not need to rebuild anything
- you can use any baseline for testing (develop, staging or mainline branch, any git hash)

Or this looks too complicated for our CQE team?

**Review by atamazov — APPROVED** [review]
LGTM

**Comment by JehandadKhan** [comment]
@atamazov @junliume This PR passes the CI and may be merged

**Review by junliume — APPROVED** [review]

**Comment by atamazov** [comment]
Let me try some manual perf testing first.

**Comment by JehandadKhan** [comment]
@atamazov @junliume This PR passes the CI and may be merged

**Comment by atamazov** [comment]
> Let me try some manual perf testing first.

**Pull request merged**
