### PR TITLE
[6.0.x] Fix for issue #2734: Detect if "-fno-offload-uniform-block" works in HIP compiler.

### PR DESCRIPTION
**Pull request by atamazov**
This PR is provided just in case the next patch version of 6.0 is released in the future.

- Resolves issue #2734.
- [Notice] Can be considered as an addition to PR #2307.
- By-product: Fixes build with -DMIOPEN_USE_COMPOSABLEKERNEL=off for 6.0 release

----
[Attribution] @junliume @JehandadKhan
- https://github.com/ROCm/MIOpen/labels/enhancement
- https://github.com/ROCm/MIOpen/labels/urgency_blocker (for Fedora Rawhide/F40 users only)
- Proposed reviewers: @JehandadKhan @pfultz2 @junliume

### CODE REVIEW

**Comment by junliume** [comment]
@atamazov could you update your branch with the latest `develop` from the main repo? Thanks!

**Comment by atamazov** [comment]
@junliume this PR is for 6.0 staging

**Comment by junliume** [comment]
> @junliume this PR is for 6.0 staging

Oh, okay, I see some issues with installing `half` in the CI

**Review by junliume — APPROVED** [review]

**Comment by atamazov** [comment]
@JehandadKhan @pfultz2 @junliume Ready for review, testing & merging.

**Pull request merged**
