### PR TITLE
Fix static depends argument

### PR DESCRIPTION
**Pull request by pfultz2**
This causes an incorrect `find_dependency` line.

### CODE REVIEW

**Comment by JehandadKhan** [comment]
While using this branch to build a client application, I get the following error

```
CMake Error at /usr/share/cmake-3.5/Modules/CMakeFindDependencyMacro.cmake:65 (find_package):
  find_package called with invalid argument "STATIC_DEPENDS"
Call Stack (most recent call first):
  /opt/rocm/lib/cmake/miopen/miopen-config.cmake:89 (find_dependency)
  CMakeLists.txt:48 (find_package)


CMake Warning at CMakeLists.txt:48 (find_package):
  Found package configuration file:

    /opt/rocm/lib/cmake/miopen/miopen-config.cmake

  but it set miopen_FOUND to FALSE so package "miopen" is considered to be
  NOT FOUND.  Reason given by package:

  miopen could not be found because dependency OpenCL could not be found.
```

Seems the package is found, but there is some other issue, is it related to this issue ?

**Comment by pfultz2** [comment]
> Seems the package is found, but there is some other issue, is it related to this issue ?

Are you using the latest rocm-cmake?

**Comment by daniellowell** [comment]
@JehandadKhan Please follow up.

**Comment by JehandadKhan** [comment]
@pfultz2 @daniellowell  Tried again with the following `rocm-cmake` installed

```
RadeonOpenCompute/rocm-cmake@8b0fb6c
```

Still get the same error when CMake does `find_package(miopen)`

**Pull request merged**
