### PR TITLE
[gfx1030_36] Tuning updates of fdb and kdb key configurations

### PR DESCRIPTION
**Pull request by iq136boy**
Navi21 tuning updates of fdb and kdb key configurations

### CODE REVIEW

**Comment by junliume** [comment]
@iq136boy could you try the following workload? *before* and *after* the tuning in latest mainline pytorch docker:
```
python3 micro_benchmarking_pytorch.py --network resnet50  --batch-size 256  --iterations 10 --dataparallel --device_ids 0 --fp16 1

**Comment by junliume** [comment]
> @iq136boy could you try the following workload? _before_ and _after_ the tuning in latest mainline pytorch docker:
> 
> ```
> python3 micro_benchmarking_pytorch.py --network resnet50  --batch-size 256  --iterations 10 --dataparallel --device_ids 0 --fp16 1
> ```
> 
> I ask since I have seen some issues on my local `gfx1030_40` node.

@cderb and @JehandadKhan @iq136boy I am seeing the following warning:
```
MIOpen(HIP): Warning [FindSolutionImpl] Invalid config loaded from Perf Db: ConvBinWinogradRxSf3x2: 71. Performance may degrade.

**Comment by atamazov** [comment]
@junliume 
> I have seen some issues on my local gfx1030_40 node.
> `Invalid config loaded from Perf Db: ConvBinWinogradRxSf3x2: 71`

AFAICS This is very strange issue. gfx1030_40 has 80 "hardware compute units" (GetMaxHardwareComputeUnits()), and config value is allowed to to have any value within `[1, 80]`. Please provide reproduce instructions (branch, git hash etc.) Are you sure the device is really gfx1030_40?

@Slimakanzer @Kirpich30000 Can you please have a look at this?

**Comment by Slimakanzer** [comment]
@junliume Are you sure it was Navi21 with 80CUs? May I ask you to give us a full log and docker container to reproduce this issue?

**Comment by junliume** [comment]
> @junliume Are you sure it was Navi21 with 80CUs? May I ask you to give us a full log and docker container to reproduce this issue?

@Slimakanzer  and @atamazov My bad it should be `gfx1030_30`. I am on a gfx1030 (W6800 Pro) where we have 60 CUs.

**Comment by junliume** [comment]
Sorry I am on `gfx1030_30` :) So this winograd kernel indeed is applicable for `gfx1030_36` but not `gfx1030_30`

**Review by junliume — APPROVED** [review]

**Comment by atamazov** [comment]
> Sorry I am on `gfx1030_30` :) So this winograd kernel indeed is applicable for `gfx1030_36` but not `gfx1030_30`

I believe you meant that the **_tuning value_** for the winograd kernel is not applicable for gfx1030_30. The kernel itself is applicable for any number of physical CUs less than 512 ;)

Note that on gfx1030_30, after this warning, the library resets the tuning value to the default, which the number of hardware CUs (60 in this specific case) and there should be almost no performance drop. FYI just in case.

**Pull request merged**
