### PR TITLE
[MI100]fix issue 980-fix kernel selection logic for k-padding cases

### PR DESCRIPTION
**Pull request by shaojiewang**
Fix issue #980

### CODE REVIEW

**Review by junliume — APPROVED** [review]
Looks like caught an error in logical branching, thanks for adding test case

**Comment by junliume** [comment]
@shaojiewang @atamazov @ce1adon could you take a look at the CI failures? We are still getting a few Memory access faults, and a few Device Not Found error too :(

**Comment by ce1adon** [comment]
> @shaojiewang @atamazov @ce1adon could you take a look at the CI failures? We are still getting a few Memory access faults, and a few Device Not Found error too :(

Could be node's issue. Restarted the tests.

**Comment by atamazov** [comment]
It was a SRAM ECC failure which I've seen on the same node (...rack-90) ~2 weeks ago.

/cc @okakarpa

**Comment by shaojiewang** [comment]
Thank you for catching CI error and restarting CI test.

**Pull request merged**
