### PR TITLE
AI based heuristic for Find

### PR DESCRIPTION
**Pull request by JehandadKhan**
This PR depends on #424 

Initial testing complete

### CODE REVIEW

**Comment by atamazov** [comment]
@JehandadKhan Recently I've merged fresh develop into `imm-fallback-improv` and resolved conflicts, then rebased `getwti-wino2111` on top of it. You may wish to rebase `jd_find_heur2` on top of updated `getwti-wino2111`.

**Comment by atamazov** [comment]
@JehandadKhan Oh wait, some new merge conflicts in the baseline.

**Comment by JehandadKhan** [comment]
@atamazov thanks for the heads up, lets wait for `imm-fallback-improv` to merge to reduce this back and forth.

**Comment by atamazov** [comment]
@JehandadKhan `imm-fallback-improv` and `getwti-wino2111` updated.

**Comment by atamazov** [comment]
@JehandadKhan Oops, some merge issue is found `imm-fallback-improv`. Please postpone rebasing to the latest `getwti-wino2111` until explicit notice.

**Comment by atamazov** [comment]
@JehandadKhan Merge issues in `imm-fallback-improv` and in `getwti-wino2111` fixed. Both branches updated (`getwti-wino2111` force pushed).

**Comment by JehandadKhan** [comment]
Superseded by #631

**Comment by atamazov** [comment]
@JehandadKhan Please let me know if you experience problems during rebasing your branch. I can try to help with this.

**Pull request closed without merging**
