### PR TITLE
[Tuning][NHWC SSD][Navi21][MI200] Tuning update

### PR DESCRIPTION
**Pull request by cderb**

### CODE REVIEW

**Comment by atamazov** [comment]
Please indicate urgency, thanks.

**Comment by junliume** [comment]
@atamazov @cderb  this is a post-implementation make up PR for [SWDEV-301397](https://ontrack-internal.amd.com/browse/SWDEV-301397), I would say the urgency level is high. :)

**Review by junliume — APPROVED** [review]

**Comment by atamazov** [comment]
SWDEV indicates P1 for 5.0

**Comment by atamazov** [comment]
@JehandadKhan Do you approve?

**Review by JehandadKhan — APPROVED** [review]

**Comment by atamazov** [comment]
It's a pity that we didn't append "(SWDEV-301397)" to commit description.

**Pull request merged**
