### PR TITLE
[tests] Remove W/A for issues #874 and #1008

### PR DESCRIPTION
**Pull request by atamazov**
After merging this, #874 and #1008 can be closed.

### CODE REVIEW

**Review by junliume — DISMISSED** [review]

**Comment by atamazov** [comment]
@junliume Thanks! But let me remove W/As fully ;)

**Comment by atamazov** [comment]
@junliume Ready for final testing/reviewing and merging.

**Review by junliume — APPROVED** [review]

**Comment by junliume** [comment]
@atamazov unfortunately the CI of develop is failing after merging this commit:
log attached
[Fp32 Hip Debug Embedded Vega.log](https://github.com/ROCmSoftwarePlatform/MIOpen/files/11702676/Fp32.Hip.Debug.Embedded.Vega.log)

**Comment by atamazov** [comment]
@junliume I am curious how this PR passed the CI. Can you please attach also the passing og from this PR? I suspect it was run on gfx906/64 while the develop fails on gfx906/60, but there could be some other reason. I really want to finish those two tickets and remove the W/As.

**Comment by junliume** [comment]
> @junliume I am curious how this PR passed the CI. Can you please attach also the passing og from this PR? I suspect it was run on gfx906/64 while the develop fails on gfx906/60, but there could be some other reason. I really want to finish those two tickets and remove the W/As.

Unfortunately the cached CI history for this PR does not exist any more :( This PR is reverted in develop branch, could we try again using another PR? Thanks!

**Pull request merged**
