### PR TITLE
[Tuning][MIGraphx] tuning update

### PR DESCRIPTION
**Pull request by cderb**

### CODE REVIEW

**Comment by kahmed10** [comment]
Hi, testing gfx 1030 is not showing any improvements from develop branch. Can you please show before and after on your GPU where the speedup is coming from? And gfx1030 fusions are even slower.

**Comment by cderb** [comment]
Will require merging with #1271

**Comment by cderb** [comment]
Closed due to outdated dbs.

**Comment by aserio** [comment]
@cderb were these changes included in a subsequent tuning?
cc: @causten

**Pull request closed without merging**
