### PR TITLE
Add filesystem utility functions

### PR DESCRIPTION
**Pull request by apwojcik**
The PR adds the following OS-agnostic filesystem utility function.
* `make_object_file_name()` - appends to a filename `.o` on Linux and `.obj` on Windows,
* `make_executable_name()` - appends to a filename `.exe` on Windows, nothing on Linux,
* `make_static_library_name()` - prepends a filename with a `lib` prefix and appends `.a` on Linux, appends `.lib` on Windows,
* `make_dynamic_library_name()` - prepends a filename with a `lib` prefix and appends `.so` on Linux. spprnfd `.dll` on Windows.

You don't need to separate the parent path from a filename; the functions will work correctly. For example, when you call `make_dynamic_library_name("<parent_path>/sample")`, the result on Linux is `<parent_path>/libsample.so` and on Windows is `<parent_path>\sample.dll`.

In addition, the PR implements two operator overloads for concatenating strings with `fs::path`, resulting in a string object. The call to `.string()` is unnecessary, e.g., when you want to report the path in the `MIOPEN_THROW` messages.

As for logging the PR changes from `+` to `<<`, which natively supports `fs::path`.

PS. You may still see some calls to `.string()` from `fs::path`. The upcoming PR, which changes `std::string` to `fs::path` to work on paths, will remove those (I need this PR to be merged first).

### CODE REVIEW

**Comment by junliume** [comment]
@apwojcik MIFin, which is a submodule of MIOpen, needs to be updated to accommodate this change simultaneously. Thanks!

**Review by CAHEK7 — APPROVED** [review]

**Review by DrizztDoUrden — APPROVED** [review]

**Comment by junliume** [comment]
@cderb could you help to fix FIN when @apwojcik is not available this week?

**Comment by junliume** [comment]
FIN is updated in https://github.com/ROCm/MIOpen/pull/2805, if that PR is fine and merge first, we can update this PR from develop

**Comment by junliume** [comment]
@apwojcik please resolve conflict by merging the latest develop branch.

**Pull request merged**
