### PR TITLE
[TESTS] Detect all failures of custom tests (issue #943)

### LINKED ISSUE #943: Incorrect Ctest settings
Ctest was incorrectly configured for "custom_tests", which caused it to pass tests with failed validation and other FAILED reasons, except cases with system interaption like segfault.

As example:
stage: Smoke FP32->FP32 Hip Debug gfx908 /opt/rocm
No fails in develop without fix.
Logs with fixed Ctest:
```
[2021-05-21T14:07:12.677Z] 56/58 Test #58: test_conv_igemm_dynamic_small ....***Failed  Error regular expression found in output. Regex=[FAILED] 33.56 sec
[2021-05-21T14:07:12.677Z] [  2%] Built target sqlite_memvfs
[2021-05-21T14:07:12.677Z] [  5%] Built target addkernels
[2021-05-21T14:07:12.677Z] [100%] Built target MIOpen
[2021-05-21T14:07:12.677Z] [100%] Built target test_conv2d
[2021-05-21T14:07:12.677Z] Scanning dependencies of target test_conv_igemm_dynamic_small
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [GetFindModeValueImpl] MIOPEN_FIND_MODE = HYBRID(3)
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [get_device_name] Raw device name: gfx908
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [Handle] stream: 0x426ac90, device_id: 0
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [HipCompilerVersionImpl] 3.7.20315
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [AmdRocmMetadataVersionDetect] ROCm MD version AMDHSA_COv3, MIOpen version 2.12.0.8655-0e031217
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [BackwardDataGetWorkSpaceSize] 
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [GetBackwardSolutions] 
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [Measure] Db::Prefetch time: 190.843 ms
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [GetEnvFindOnlySolverImpl] 62
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [ForwardGetWorkSpaceSize] 
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [GetForwardSolutions] 
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [BackwardWeightsGetWorkSpaceSize] 
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [GetWrwSolutions] 
[2021-05-21T14:07:12.677Z] /var/jenkins/workspace/Open_reshuffleAndReduceTestCases/build/bin/test_conv2d --float --cmode conv --pmode default --group-count 1 --disable-backward-data --disable-backward-weights --input 16 16 56 56 --weights 64 16 1 1 --batch_size 16 --input_channels 16 --output_channels 64 --spatial_dim_elements 56 56 --filter_dims 3 3 --pads_strides_dilations 0 0 1 1 1 1 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW 
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [ForwardGetWorkSpaceSize] 
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [GetForwardSolutions] 
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [FindConvFwdAlgorithm] requestAlgoCount = 1, workspace = 0
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [GetForwardSolutions] 
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [TryLoad] Find-db regenerating.
[2021-05-21T14:07:12.677Z] /var/jenkins/workspace/Open_reshuffleAndReduceTestCases/build/bin/test_conv2d --float --cmode conv --pmode default --group-count 1 --disable-backward-data --disable-backward-weights --input 16 16 56 56 --weights 64 16 1 1 --batch_size 16 --input_channels 16 --output_channels 64 --spatial_dim_elements 56 56 --filter_dims 3 3 --pads_strides_dilations 0 0 1 1 1 1 --trans_output_pads 0 0 --in_layout NCHW --fil_layout NCHW --out_layout NCHW 
[2021-05-21T14:07:12.677Z] FAILED: /var/jenkins/workspace/Open_reshuffleAndReduceTestCases/src/ocl/convolutionocl.cpp:524: Forward Convolution cannot be executed due to incorrect params
[2021-05-21T14:07:12.677Z] Forward convolution: 
[2021-05-21T14:07:12.677Z] Input tensor: 16, 16, 56, 56
[2021-05-21T14:07:12.677Z] Weights tensor: 64, 16, 1, 1
[2021-05-21T14:07:12.677Z] Output tensor: 16, 64, 56, 56
[2021-05-21T14:07:12.677Z] Filter: conv2d, miopenConvolution, miopenPaddingDefault, {0, 0}, {1, 1}, {1, 1}, 
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [GetFindModeValueImpl] MIOPEN_FIND_MODE = HYBRID(3)
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [get_device_name] Raw device name: gfx908
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [Handle] stream: 0x3485c80, device_id: 0
[2021-05-21T14:07:12.677Z] MIOpen(HIP): Info [HipCompilerVersionImpl] 3.7.20315
[2021-05-21T14:07:12.678Z] MIOpen(HIP): Info [AmdRocmMetadataVersionDetect] ROCm MD version AMDHSA_COv3, MIOpen version 2.12.0.8655-0e031217
[2021-05-21T14:07:12.678Z] MIOpen(HIP): Info [BackwardDataGetWorkSpaceSize] 
[2021-05-21T14:07:12.678Z] MIOpen(HIP): Info [GetBackwardSolutions] 
[2021-05-21T14:07:12.678Z] MIOpen(HIP): Info [Measure] Db::Prefetch time: 182.548 ms
[2021-05-21T14:07:12.678Z] MIOpen(HIP): Info [GetEnvFindOnlySolverImpl] 62
[2021-05-21T14:07:12.678Z] MIOpen(HIP): Info [ForwardGetWorkSpaceSize] 
[2021-05-21T14:07:12.678Z] MIOpen(HIP): Info [GetForwardSolutions] 
[2021-05-21T14:07:12.678Z] MIOpen(HIP): Info [BackwardWeightsGetWorkSpaceSize] 
[2021-05-21T14:07:12.678Z] MIOpen(HIP): Info [GetWrwSolutions] 
....

```

### PR DESCRIPTION
**Pull request by shurale-nkn**
- Fixes #943. 
- Fix: Skip test_conv_igemm_dynamic* (non-xdlops) for gfx908 and for non-FP32
- Fix: Skip test_conv_igemm_dynamic_xdlops* for non-gfx908
- W/A for #954

~Expected fail in CI~

### CODE REVIEW

**Comment by atamazov** [comment]
@shurale-nkn I've opened #946 and going to commit workaround for it right here.

**Comment by atamazov** [comment]
> @shurale-nkn I've opened #946 and going to commit workaround for it right here.

Oops, no, we need separate PR (it may be needed for cherry-picking into 4.3 release branch)

**Comment by atamazov** [comment]
@shurale-nkn I've created a new branch `custom_test_fix_atamazov_tmp`, which is basically your `custom_test_fix` + #945 + #947. Let's look at its testing results on CI...

**Comment by atamazov** [comment]
@shurale-nkn After looking into results of `custom_test_fix_atamazov_tmp`, I've found some issues that block #944. The following fixes are needed:
- Disable test that use DYNAMIC_IMPLICITGEMM_BWD_ENVS_XDLOPS
 - due to W/A added in [HOTFIX] Workaround for SWDEV-286774. Disable ConvAsmImplicitGemmGTCDynamicBwdXdlops. #945, this must be disabled: `add_custom_test(test_conv_igemm_dynamic_xdlops_bwd SKIP_UNLESS_ALL`
- Disable FP16 tests that use DYNAMIC_IMPLICITGEMM_WRW_ENVS_XDLOPS.
  - due to W/a added in [HOTFIX][WORKAROUND] Disable ConvAsmImplicitGemmGTCDynamicWrwXdlops for FP16 #947, HALF should be disallowed here: `add_custom_test(test_conv_igemm_dynamic_xdlops_wrw SKIP_UNLESS_ALL ALLOW_HALF`.
- `MIOPEN_DEBUG_FIND_ONLY_SOLVER` works only in NORMAL Find mode so I am going to enforce that in relevant places.
- [documentation] MIOPEN_DEBUG_FIND_ONLY_SOLVER doc should be updated: Add restriction that it reliably works only in NORMAL mode, remove mentions of GEMM/FFT.

I am going to implement the above fixes ASAP, so please work on some other problems, or let me know if you would like to fix these yourself.

**Comment by atamazov** [comment]
`custom_test_fix_atamazov_tmp` updated.

**Comment by junliume** [comment]
> @shurale-nkn After looking into results of `custom_test_fix_atamazov_tmp`, I've found some issues that block #944. The following fixes are needed:
> 
> * [x]  Not necessary due to #949 ~Disable test that use DYNAMIC_IMPLICITGEMM_BWD_ENVS_XDLOPS. Due to W/A added in _[HOTFIX] Workaround for SWDEV-286774. Disable ConvAsmImplicitGemmGTCDynamicBwdXdlops #945_, this must be disabled: `add_custom_test(test_conv_igemm_dynamic_xdlops_bwd SKIP_UNLESS_ALL`~
> * [ ]  Added right in #947: Disable FP16 tests that use DYNAMIC_IMPLICITGEMM_WRW_ENVS_XDLOPS. Due to W/a added in _[HOTFIX][WORKAROUND] Disable ConvAsmImplicitGemmGTCDynamicWrwXdlops for FP16 #947_, HALF should be disallowed here: `add_custom_test(test_conv_igemm_dynamic_xdlops_wrw SKIP_UNLESS_ALL ALLOW_HALF`.
> * [ ]  `MIOPEN_DEBUG_FIND_ONLY_SOLVER` works only in NORMAL Find mode so I am going to enforce that in relevant places.
>   
>   * [ ]  #949 In all test_conv_igemm_dynamic* tests
>   * [ ]  ...?
> * [ ]  [documentation] MIOPEN_DEBUG_FIND_ONLY_SOLVER doc should be updated: Add restriction that it reliably works only in NORMAL mode, remove mentions of GEMM/FFT.
> 
> I am working on this right now, so please work on some other problems

@atamazov Since #947 and #949 are merged, are we creating another issue for [doc] and proceed with this current PR?

**Comment by atamazov** [comment]
> Since #947 and #949 are merged, are we creating another issue for [doc]...

#940 updated.

> ... and proceed with this current PR?

We are working on this. There are some additional blockers, please expect PR(s) soon.

**Comment by atamazov** [comment]
Hopefully all issues resolved/"worked around".

**Review by atamazov — APPROVED** [review]
LG(tm)

**Pull request merged**
