### PR TITLE
Removed scgemm

### PR DESCRIPTION
**Pull request by DrizztDoUrden**

### CODE REVIEW

**Comment by atamazov** [comment]
"My shameful deletion" is a good name for a punk band ;)

**Comment by JehandadKhan** [comment]
> "My shameful deletion" is a good name for a punk band ;)

@atamazov You sing it and they would come :)

**Comment by atamazov** [comment]
@daniellowell Please take it ;)

**Comment by daniellowell** [comment]
@atamazov @JehandadKhan Any objections to merging? LGTM

**Pull request merged**
