### PR TITLE
Batchnorm backward changes for small filter sizes

### PR DESCRIPTION
**Pull request by muralinr**
Batchnorm backward changes for small filter sizes

### CODE REVIEW

**Comment by ekuznetsov139** [comment]
Does this actually fix anything or does it merely bypass the failing code for some configurations?

**Comment by muralinr** [comment]
> Does this actually fix anything or does it merely bypass the failing code for some configurations?
> 
> In other words, does backward norm work with n>768 and in_cstride>63?

yes Artem. It works with n>768 and in_cstride>63.  Earlier code was picking up with wrong variant and hence it fails.  This code changes fix that issue.

**Comment by ekuznetsov139** [comment]
Is there a unit test for n>768 and in_cstride>63?

**Comment by muralinr** [comment]
> Is there a unit test for n>768 and in_cstride>63?

I added both failed test case and new test case ( n>768 and in_cstride>63) in "network.hpp"

**Comment by daniellowell** [comment]
@muralinr Did you figure out where this test is coming in from?

**Comment by muralinr** [comment]
> @muralinr Did you figure out where this test is coming in from?

Hi Daniel, I don't find test vector in MIOpen/test/network_data.hpp file.  

> @muralinr Did you figure out where this test is coming in from?

yes Daniel. I updated test vector.

**Comment by daniellowell** [comment]
@muralinr Please post the performance number from a range of configs.

**Comment by muralinr** [comment]
> @muralinr Please post the performance number from a range of configs.

Sure Daniel.

**Comment by muralinr** [comment]
> @muralinr Please post the performance number from a range of configs.

Hello Daniel,
I attached performance numbers in the attached xls sheets for fp32 and fp16.
[BN_fp32_configs.xlsx](https://github.com/ROCmSoftwarePlatform/MIOpen/files/4815982/BN_fp32_configs.xlsx)
[BN_fp16_configs.xlsx](https://github.com/ROCmSoftwarePlatform/MIOpen/files/4815983/BN_fp16_configs.xlsx)

**Pull request merged**
