### PR TITLE
[Test][CI] Fix #1064 #1095 remove work arounds for test_dropout

### LINKED ISSUE #1064: [gfx908] test_dropout failed without info
test_dropout failed without 'FAILED' trigger word .

Disabled by default in develop.

```[2021-07-28T15:47:56.349Z]  7/78 Test #17: test_dropout ...............................***Failed  2756.43 sec```
Possible reason:
```[2021-07-28T15:47:56.355Z] Config requires 154619215872 Bytes to write all necessary tensors to GPU. GPU has 34342961152 Bytes of memory```

some test requires 154619215872 bytes / 1024 /1024 /1024 => 144Gb ... That seems like kind of a lot

Failed CI build:
http://micimaster.amd.com/blue/rest/organizations/jenkins/pipelines/MLLibs/pipelines/MIOpen/branches/tests_for_908/runs/6/nodes/1505/steps/1603/log/?start=0

### PR DESCRIPTION
**Pull request by junliume**
**Updated description:**
After merging #1129, issues #1064 and #1095 are no longer observed, so no workaround is needed for them.

Fix #1064 #1095 remove work arounds for test_dropout
test_dropout only runs one iterations now and should not be very long
will monitor CI for progress

### CODE REVIEW

**Review by shurale-nkn — DISMISSED** [review]
LGTM, but please resolve merge conflict

**Comment by atamazov** [comment]
@junliume 
> Fix #1064 #1095 remove work arounds for test_dropout
> test_dropout only runs one iterations now and should not be very long
> will monitor CI for progress

Alternative description of this PR: _After merging #1129, issues #1064 and #1095 are no longer observed, so no workaround is needed for them._

Is it correct?

**Comment by junliume** [comment]
> @junliume
> 
> > Fix #1064 #1095 remove work arounds for test_dropout
> > test_dropout only runs one iterations now and should not be very long
> > will monitor CI for progress
> 
> Alternative description of this PR: _After merging #1129, issues #1064 and #1095 are no longer observed, so no workaround is needed for them._
> 
> Is it correct?

Yes, description updated above too. Thanks!

**Comment by junliume** [comment]
Ping @atamazov @shurale-nkn @shaojiewang for review, should be a low complexity one. Thanks!

**Review by atamazov — APPROVED** [review]

**Pull request merged**
