### PR TITLE
Update Find Db for SWDEV-284848

### PR DESCRIPTION
**Pull request by JehandadKhan**

### CODE REVIEW

**Comment by junliume** [comment]
@JehandadKhan @sunway513 Standing by and let me know if you need the pull anytime. Thanks, Jehandad.

**Comment by atamazov** [comment]
Just in case -- merging into `rocm-4.2.x` directly is a bit out of the Process. Please do not forget to merge this into `rocm-4.2.x-staging` as well, thanks.

**Comment by junliume** [comment]
> Just in case -- merging into `rocm-4.2.x` directly is a bit out of the Process. Please do not forget to merge this into `rocm-4.2.x-staging` as well, thanks.

@JehandadKhan  could you create another PR to staging branch? Or we do the "backward" cherry picking after this one? I would recommend the first.

**Comment by atamazov** [comment]
@junliume PR is not required. Just cherry-pick or let me know and I'll do that.

**Comment by atamazov** [comment]
rocm-4.2.x-staging also updated. Now both branches are identical.

**Pull request merged**
