### PR TITLE
Change access modifiers offset

### PR DESCRIPTION
**Pull request by averinevg**
Changes access modifiers offset for better code readability.
Should be merged after https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1397.

### CODE REVIEW

**Review by atamazov — APPROVED** [review]
LGTM

**Comment by atamazov** [comment]
To reviewers: Let's reach consensus before merging. It means that we need blessings from all of you.

**Comment by junliume** [comment]
> To reviewers: Let's reach consensus before merging. It means that we need blessings from all of you.

Ping @DrizztDoUrden and @JehandadKhan

**Review by DrizztDoUrden — APPROVED** [review]
LGTM

**Comment by junliume** [comment]
Ping @JehandadKhan  since full board of consensus is requested :)

**Review by JehandadKhan — APPROVED** [review]

**Review by junliume — APPROVED** [review]

**Pull request merged**
