### PR TITLE
[Tuning]  rel-4.5 fdb update for develop

### PR DESCRIPTION
**Pull request by cderb**

### CODE REVIEW

**Comment by junliume** [comment]
> Is this from 4.5 tuning?

I think so, and the source branch name also double confirms ``cderb/fdb_tuning_dev-4.5`` so.

**Comment by atamazov** [comment]
In performance testing right now...

**Review by atamazov — DISMISSED** [review]
fdb duplicate IDs for gfx906/60

**Comment by atamazov** [comment]
```
MIOpen(HIP): Error [ParseContents] Duplicate ID (ignored): miopenConvolutionBwdDataAlgoDirect; key: 256-28-28-1x1-64-56-56-8-0x0-2x2-1x1-0-NCHW-BF16-B
MIOpen(HIP): Error [ParseContents] Duplicate ID (ignored): miopenConvolutionBwdDataAlgoDirect; key: 64-56-56-3x3-64-56-56-8-1x1-1x1-1x1-0-NCHW-BF16-B
MIOpen(HIP): Error [ParseContents] Duplicate ID (ignored): miopenConvolutionBwdDataAlgoWinograd; key: 128-6-60-3x3-64-6-60-16-1x1-1x1-1x1-0-NCHW-FP16-B
MIOpen(HIP): Error [ParseContents] Duplicate ID (ignored): miopenConvolutionBwdDataAlgoWinograd; key: 256-7-7-1x1-832-7-7-16-0x0-1x1-1x1-0-NCHW-FP32-B
MIOpen(HIP): Error [ParseContents] Duplicate ID (ignored): miopenConvolutionFwdAlgoDirect; key: 256-14-14-1x1-1024-7-7-8-0x0-2x2-1x1-0-NCHW-BF16-F
MIOpen(HIP): Error [ParseContents] Duplicate ID (ignored): miopenConvolutionFwdAlgoDirect; key: 256-14-14-1x1-256-14-14-8-0x0-1x1-1x1-0-NCHW-FP16-F
MIOpen(HIP): Error [ParseContents] Duplicate ID (ignored): miopenConvolutionFwdAlgoImplicitGEMM; key: 128-28-28-1x1-512-28-28-8-0x0-1x1-1x1-0-NCHW-FP32-F
MIOpen(HIP): Error [ParseContents] Duplicate ID (ignored): miopenConvolutionFwdAlgoImplicitGEMM; key: 512-28-28-1x1-1024-14-14-16-0x0-2x2-1x1-0-NCHW-FP32-F
MIOpen(HIP): Error [ParseContents] Duplicate ID (ignored): miopenConvolutionFwdAlgoWinograd; key: 512-7-7-3x3-512-7-7-8-1x1-1x1-1x1-0-NCHW-FP16-F
```

**Comment by atamazov** [comment]
It seems like the root reason of https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1133#issuecomment-922548630 is not yet fixed.

**Comment by atamazov** [comment]
### Examples of duplicates

256-28-28-1x1-64-56-56-8-0x0-2x2-1x1-0-NCHW-BF16-B=
```
miopenConvolutionBwdDataAlgoDirect:
    ConvOclDirectFwd1x1,0.10016,0,miopenConvolutionBwdDataAlgoDirect,256x28x28x1x1x64x56x56x8xNCHWxBF16x0x0x2x2x1x1x1xB;
miopenConvolutionBwdDataAlgoDirect:
    ConvOclDirectFwd1x1,0.10016,0,miopenConvolutionBwdDataAlgoDirect,256x28x28x1x1x64x56x56x8xNCHWxBF16x0x0x2x2x1x1x1xB;
miopenConvolutionBwdDataAlgoGEMM:
    GemmBwd1x1_stride2,1.48128,4014080,miopenConvolutionBwdDataAlgoGEMM,256x28x28x1x1x64x56x56x8xNCHWxBF16x0x0x2x2x1x1x1xB
```

128-28-28-1x1-512-28-28-8-0x0-1x1-1x1-0-NCHW-FP32-F=
```
miopenConvolutionFwdAlgoImplicitGEMM
    ConvHipImplicitGemmV4R4Fwd,0.09984,0,miopenConvolutionFwdAlgoImplicitGEMM,128x28x28x1x1x512x28x28x8xNCHWxFP32x0x0x1x1x1x1x1xF
miopenConvolutionFwdAlgoDirect
    ConvAsm1x1U,0.11744,0,miopenConvolutionFwdAlgoDirect,128x28x28x1x1x512x28x28x8xNCHWxFP32x0x0x1x1x1x1x1xF
miopenConvolutionFwdAlgoImplicitGEMM
    ConvHipImplicitGemmV4R4Fwd,0.13424,0,miopenConvolutionFwdAlgoImplicitGEMM,128x28x28x1x1x512x28x28x8xNCHWxFP32x0x0x1x1x1x1x1xF
miopenConvolutionFwdAlgoGEMM
    GemmFwd1x1_0_1,0.13424,0,miopenConvolutionFwdAlgoGEMM,128x28x28x1x1x512x28x28x8xNCHWxFP32x0x0x1x1x1x1x1xF
miopenConvolutionFwdAlgoWinograd
    ConvBinWinogradRxSf3x2,0.231841,0,miopenConvolutionFwdAlgoWinograd,128x28x28x1x1x512x28x28x8xNCHWxFP32x0x0x1x1x1x1x1xF
```

**Comment by atamazov** [comment]
## Missing fdb records for gfx906/60/HIP
[gfx906_60.HIP.missing.fp32.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/7259003/gfx906_60.HIP.missing.fp32.txt)
[gfx906_60.HIP.missing.fp16.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/7259004/gfx906_60.HIP.missing.fp16.txt)
[gfx906_60.HIP.missing.bf16.txt](https://github.com/ROCmSoftwarePlatform/MIOpen/files/7259006/gfx906_60.HIP.missing.bf16.txt)

**Comment by atamazov** [comment]
## Performance testing results

:green_circle: These are good!

ROCm 4.0, gfx906/60, Performance gain, based on sum of all times/directions:

&nbsp; | &nbsp; | GPU time | Wall time | Aux Wall time
-- | -- | -- | -- | --
FP32/HIP | Default find mode | 1.13 | 1.11 | 1.45
&nbsp; | Immediate mode | 1.13 | 1.10 | 1.49
FP16/HIP | Default find mode | 1.00 | 0.93 | 0.74
&nbsp; | Immediate mode | 1.00 | 0.98 | 1.17
BF16/HIP | Default find mode | 0.99 | 0.75 | 1.16
&nbsp; | Immediate mode | 0.99 | 0.99 | 1.12
FP32/OpenCL | Default find mode | 1.00 | 1.01 | 0.99
&nbsp; | Immediate mode | 1.00 | 1.00 | 1.00

**Comment by atamazov** [comment]
## Verdict

I tested this only on gfx906/60. Assuming other GPUs perform similarly, I think this can be merged provided that "Duplicate ID" issues are resolved.

**Comment by cderb** [comment]
Thanks Artem, I'll start looking into the source of the duplication.

**Comment by cderb** [comment]
fdb entries no longer contain duplicate algorithms.

**Comment by atamazov** [comment]
Testing on MI100 is ongoing.

**Comment by junliume** [comment]
@atamazov @JehandadKhan 
Would need #1196 and #1176 for next MIOpen staging promotion
#1192 is also nice to have

**Comment by atamazov** [comment]
## MI100 testing results (ROCm 4.3.1)

:yellow_circle: Looks acceptable. Develop vs cderb/fdb_tuning_dev-4.5, tested with MI100 & ROCm 4.3.1. Performance gain, based on sum of all times/directions:

&nbsp; | &nbsp; | GPU time | Wall time | Aux Wall time
-- | -- | -- | -- | --
FP32/HIP | Default find mode | 1.00 | 0.81 | 0.94
&nbsp; | Immediate mode | 1.00 | 0.96 | 1.14
FP16/HIP | Default find mode | 1.04 | 0.93 | 0.78
&nbsp; | Immediate mode | 1.03 | 0.90 | 0.97

**Review by atamazov — APPROVED** [review]
LGTM!

**Comment by junliume** [comment]
> @atamazov @JehandadKhan Would need #1196 and #1176 for next MIOpen staging promotion #1192 is also nice to have

Merged #1196 and initiated another round of develop staging, #1176 is functional update and can wait till next week's round.

**Pull request merged**
