### PR TITLE
Converting Cmake test to gtest for test_conv_for_implicit_gemm

### PR DESCRIPTION
**Pull request by ozturkosu**
It was successfully complied and run.

### CODE REVIEW

**Comment by ozturkosu** [comment]
Need to update this PR for Environment Variable Issue.

**Review by CAHEK7 — DISMISSED** [review]
The changes from #2599 and #2553 should be incorporated into this PR as well.
Gtest conversion is a king of tricky right now.

**Comment by junliume** [comment]
@ozturkosu @JehandadKhan can we safely say that we can close this PR because it is replaced by other PRs?

**Review by junliume — APPROVED** [review]

**Comment by junliume** [comment]
Ping @CAHEK7 @xinlipn @cderb @JehandadKhan for review

**Pull request merged**
