### PR TITLE
[ROCm3.7...4.0][MI100][HIP compiler] W/A for correctness problems in PerformanceImplicitGemmForwardV4R4Xdlops_Padded_Gemm due to compiler issue.

### PR DESCRIPTION
**Pull request by atamazov**
Please read comment in the code for description. Failing configs:
```
./bin/test_conv2d --float --cmode conv --group-count 1 --disable-backward-data --disable-backward-weights --input 1, 3, 227, 227 --weights 1, 3, 3, 3 --pads_strides_dilations 0 0 1 1 1 1 --trans_output_pads 0 0 \
--disable-backward-data --disable-backward-weights --disable-verification-cache -v ;\
./bin/test_conv2d --float --cmode conv --group-count 1 --disable-backward-data --disable-backward-weights --input 1, 3, 227, 227 --weights 1, 3, 3, 3 --pads_strides_dilations 0 0 2 2 1 1 --trans_output_pads 0 0 \
--disable-backward-data --disable-backward-weights --disable-verification-cache -v ;\
./bin/test_conv2d --float --cmode conv --group-count 1 --disable-backward-data --disable-backward-weights --input 1, 3, 227, 227 --weights 1, 3, 3, 3 --pads_strides_dilations 1 1 1 1 1 1 --trans_output_pads 0 0 \
--disable-backward-data --disable-backward-weights --disable-verification-cache -v ;\
./bin/test_conv2d --float --cmode conv --group-count 1 --disable-backward-data --disable-backward-weights --input 1, 3, 227, 227 --weights 1, 3, 3, 3 --pads_strides_dilations 1 1 2 2 1 1 --trans_output_pads 0 0 \
--disable-backward-data --disable-backward-weights --disable-verification-cache -v ;\
./bin/test_conv2d --float --cmode conv --group-count 1 --disable-backward-data --disable-backward-weights --input 1, 3, 227, 227 --weights 1, 3, 3, 3 --pads_strides_dilations 1 1 2 2 2 1 --trans_output_pads 0 0 \
--disable-backward-data --disable-backward-weights --disable-verification-cache -v ;\
./bin/test_conv2d --float --cmode conv --group-count 1 --disable-backward-data --disable-backward-weights --input 1, 3, 227, 227 --weights 1, 3, 3, 3 --pads_strides_dilations 2 2 1 1 1 1 --trans_output_pads 0 0 \
--disable-backward-data --disable-backward-weights --disable-verification-cache -v ;\
./bin/test_conv2d --float --cmode conv --group-count 1 --disable-backward-data --disable-backward-weights --input 1, 3, 227, 227 --weights 1, 3, 3, 3 --pads_strides_dilations 3 3 2 2 1 1 --trans_output_pads 0 0 \
--disable-backward-data --disable-backward-weights --disable-verification-cache -v ;\
./bin/test_conv2d --float --cmode conv --group-count 1 --disable-backward-data --disable-backward-weights --input 1, 3, 227, 227 --weights 1, 3, 3, 3 --pads_strides_dilations 3 3 2 2 4 4 --trans_output_pads 0 0 \
--disable-backward-data --disable-backward-weights --disable-verification-cache -v ;\
./bin/test_conv2d --float --cmode conv --group-count 1 --disable-backward-data --disable-backward-weights --input 1, 64, 112, 112 --weights 1, 64, 3, 3 --pads_strides_dilations 3 3 2 2 4 4 --trans_output_pads 0 0 \
--disable-backward-data --disable-backward-weights --disable-verification-cache -v
```
This is urgent or our CI will be red soon.

### CODE REVIEW

**Comment by atamazov** [comment]
This blocks merging of #833.

**Comment by asroy** [comment]
I test develop with ROCm4.0, which also have same issue.

**Comment by atamazov** [comment]
W/A extended up to 4.0.x.

**Comment by atamazov** [comment]
Please approve.

**Pull request merged**
