### PR TITLE
bg/LWMIOPEN-189 : use DataInvokeParams for non-fused solver - fix tuning of legacy OCL solvers

### PR DESCRIPTION
**Pull request by bghimireamd**
Address https://github.com/ROCmSoftwarePlatform/MIOpen/issues/2239

### CODE REVIEW

**Review by atamazov — APPROVED** [review]
LGTM

**Comment by atamazov** [comment]
I can confirm that this PR resolves #2239

**Comment by atamazov** [comment]
[R] @bghimireamd Maybe it is worth renaming this. Like in C++ comments, I recommend explaining why we are doing this, not what or how we are doing (because the latter should be clear from the diff). Proposal: "Fix tuning of legacy OCL solvers (resolves issue #2239)". Up to you.

**Comment by atamazov** [comment]
[Attribution] @junliume
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_blocker
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/bug
- Proposed reviewer: @DrizztDoUrden

**Review by junliume — APPROVED** [review]

**Pull request merged**
