### PR TITLE
[NFC] Moved DetectRocm calls to constructor of ExecutionContext

### PR DESCRIPTION
**Pull request by DrizztDoUrden**
Implements #2289

### CODE REVIEW

**Review by averinevg — DISMISSED** [review]
LGTM

**Comment by junliume** [comment]
Hi @DrizztDoUrden this is triggering some strange issues in CI:
```
[2023-08-02T21:03:43.755Z] /var/jenkins/workspace/s_MIOpen_ddu_private-detect-rocm/fin/src/include/tensor.hpp:30:5: warning: 'HIP_PACKAGE_VERSION_FLAT' is not defined, evaluates to 0 [-Wundef]

[2023-08-02T21:03:43.755Z] #if HIP_PACKAGE_VERSION_FLAT >= 5006000000ULL

[2023-08-02T21:03:43.755Z]     ^

[2023-08-02T21:03:47.689Z] In file included from /var/jenkins/workspace/s_MIOpen_ddu_private-detect-rocm/fin/src/main.cpp:29:

[2023-08-02T21:03:47.689Z] /var/jenkins/workspace/s_MIOpen_ddu_private-detect-rocm/fin/src/include/conv_fin.hpp:211:9: error: 'DetectRocm' is a private member of 'miopen::ExecutionContext'

[2023-08-02T21:03:47.689Z]     ctx.DetectRocm();

[2023-08-02T21:03:47.689Z]         ^
```

If `HIP_PACKAGE_VERSION_FLAT` is not defined in the scope, why it passed previous CI runs?

**Comment by atamazov** [comment]
@junliume 
> If HIP_PACKAGE_VERSION_FLAT is not defined in the scope, why it passed previous CI runs?

Because this is just a warning.

Note that this happens during _fin_ build. IIRC we do not use _fin_ in our tidy checks; _fin_ has its own Jenkinsfile (and its own tidy check). Why it does not catch the problem like this is another story. `<config.h>` must be included before using HIP_PACKAGE_VERSION_FLAT in fin/src/include/tensor.hpp. I highly recommend fixing both issues in _fin_. @cderb @JehandadKhan

**Comment by cderb** [comment]
I'm looking into resolving the warning from HIP_PACKAGE_VERSION_FLAT.
It looks like moving DetectRocm caused some breakages in fin as well. It appears that the solution is to simply remove these lines?

**Comment by atamazov** [comment]
@cderb Exactly. What is the process of updating both _fin_ and _MIOpen_? It seems like we can't commit changes in _fin_ without prior changes in _MIOpen_ and vice versa 🤔

**Comment by cderb** [comment]
@atamazov this time lets change the fin branch here, then we can redirect it back to develop once the repos are aligned.
If you use this fin branch for the submodule, I believe we can pass the CI: cerb/detect_rocm_private

**Comment by atamazov** [comment]
@DrizztDoUrden FYI 👆

**Review by atamazov — APPROVED** [review]
LGTM!

**Review by junliume — APPROVED** [review]

**Pull request merged**
