### PR TITLE
Remove dummy_memset for rocblas timing

### PR DESCRIPTION
**Pull request by asroy**
For issue #418, remove dummy_memset

### CODE REVIEW

**Comment by daniellowell** [comment]
What is the side effect of this change?

**Comment by shurale-nkn** [comment]
The value of elapsed time returned from find may change for gemm.

**Comment by daniellowell** [comment]
> The value of elapsed time returned from find may change for gemm.

That can have significant implications for performance. I suggest this PR proceeds with caution.

**Comment by asroy** [comment]
@shurale-nkn @atamazov 

When user want to do CallGEMMXXXX (CallGemm, CallGemmStridedBatched, callGemmStridedBatchedSequential) and do timing, he will call CallGemmTimeMeasure, which will do a 1st call of  CallGEMMXXXX for warm-up, and then a 2nd call of CallGEMMXXXX for timing.

dummy_memset is not necessary because we are already enqueuing a warn-up call,

**Comment by atamazov** [comment]
@shurale-nkn @asroy Oops, merge conflicts. If this PR is still needed, then please resolve these. I can test how it affects performance, if necessary.

**Comment by daniellowell** [comment]
@asroy This looks abandoned. Is it still needed?

**Comment by atamazov** [comment]
@shurale-nkn Please review (don't mind conflicts)

**Comment by atamazov** [comment]
@asroy @shurale-nkn AFAICS this can resolve two important issues, #416 and #723. Let's finish it.

**Review by shurale-nkn — APPROVED** [review]

**Comment by atamazov** [comment]
@asroy Could you please resolve merge conflicts? Then I will be able to run performance testing on this and compare with develop etc.

**Comment by asroy** [comment]
@atamazov Merge conflict resolved

**Comment by atamazov** [comment]
Oops, Hip Tidy error.

**Comment by atamazov** [comment]
Indeed, this resolves #723

**Review by atamazov — APPROVED** [review]
Testing done, none perf regressions in GEMM algorithm. LGTM!

**Comment by atamazov** [comment]
Converted to draft to avoid spoiling docker image cache on CI. You can continue work as usual. But please change this back to "normal" PR only after ending of CI moratorium (see mail). Then first merge from develop. Push the `[Ready for review]` button only after that. Thanks.

**Comment by atamazov** [comment]
All tests passed.

**Pull request merged**
