### PR TITLE
Wip rocmtest trial mi200

### PR DESCRIPTION
**Pull request by nyamodil**
merge changes in develop branch to wip-rocmtest-trial-mi200

### CODE REVIEW

**Comment by junliume** [comment]
We generally do not need to open a PR to merge into the trial branch :)

**Comment by junliume** [comment]
The merge direction of this PR is not correct

**Comment by atamazov** [comment]
# 🥲

**Comment by atamazov** [comment]
@junliume I can update trial branches if you wish (but I need to open PRs because I can't update branches in this repo)

**Comment by atamazov** [comment]
[TIP] 💡 
```bash
git fetch origin develop &&\
git checkout develop &&\
git pull origin develop &&\
git fetch origin wip-rocmtest-trial-mi200 &&\
git checkout wip-rocmtest-trial-mi200 &&\
git pull origin wip-rocmtest-trial-mi200 &&\
git merge --no-commit develop
```
Then observe changes, resolve merge conflicts (if any), commit and push. Basically merges should be trivial; beware if this is not the case.

Maybe it is worth opening PRs for this for a while and assign me as a reviewer, for a while at least.

**Comment by atamazov** [comment]
@nyamodil See previous comment.

**Comment by nyamodil** [comment]
@atamazov will do so, on any trial branch merges intended. thank you.

**Pull request closed without merging**
