### PR TITLE
Prevent UB in all ASM & OCL kernels that do not anticipate asymmetric padding

### PR DESCRIPTION
**Pull request by atamazov**
Resolves ASM & OCL leftovers of #142.

Disables configs that have asymmetric padding in all Solvers that do not anticipate it. See https://github.com/ROCmSoftwarePlatform/MIOpen/issues/142#issuecomment-625941366 for details. 

Note that currently asymmetric padding is possible only for even filter sizes. However this PR affects Solvers that support odd filters as well. This is done in order to avoid adding new implicit dependencies (on how we define “asymmetric padding”).

### CODE REVIEW

**Comment by daniellowell** [comment]
This sound like a bug.

**Comment by atamazov** [comment]
Formally speaking, the bug is a reason of an issue. However I do not have specific issues on hand (and would like to avoid spending time for finding these). So this is not a bug fix, technically.

**Comment by TejashShah** [comment]
@atamazov LGTM.

**Comment by atamazov** [comment]
> @atamazov What about igemm solvers?

Out of scope of this PR

**Comment by atamazov** [comment]
#142 updated with Q for @asroy

**Comment by TejashShah** [comment]
LGTM to be merged.

**Comment by atamazov** [comment]
All tests passed, ready for merge.

**Pull request merged**
