### PR TITLE
[CI][Tests] remove workaround for test_conv_for_implicit_gemm from #240 (#1167)

### PR DESCRIPTION
**Pull request by junliume**
ref: #1167 
re-enabling it seems to be stable in the tip of develop

This PR is a housekeeping mini-maintenance suggested by Artem

### CODE REVIEW

**Comment by junliume** [comment]
@atamazov please review. a very small step towards your goal of resolving the W/As :)

**Comment by atamazov** [comment]
@junliume Thanks! unfortunately there is `WORKAROUND_ISSUE_936` which seems terribly excessive and may mask possibly uncovered problems:
https://github.com/ROCmSoftwarePlatform/MIOpen/blob/030a3695d5f899afbd484338558fbb70a4b204d1/test/CMakeLists.txt#L693

Let's rework that workaround first (I am working on it with @shurale-nkn)

**Comment by junliume** [comment]
> @junliume Thanks! unfortunately there is `WORKAROUND_ISSUE_936` which seems terribly excessive and may mask Fwd/Bwd FP16 issues (possibly uncovered by this PR):
> https://github.com/ROCmSoftwarePlatform/MIOpen/blob/030a3695d5f899afbd484338558fbb70a4b204d1/test/CMakeLists.txt#L693
> 
> Let's rework that workaround first (I am working on it with @shurale-nkn)

Thanks! Let's keep this PR **On Hold** then.

**Comment by junliume** [comment]
> I recommend holding this off until my work with `wa-936-cleanup` (no PR yet) is done. Unfortunately I am totally busy with hiprtc right now...

Sure! That's why it is still in draft phase, I am reverting a few of these W/As and use quiet time of CI systems to observe if there are any issues. :)

**Pull request closed without merging**
