### PR TITLE
[tests] Remove duplicated CTests i.e. line 770, 772

### PR DESCRIPTION
**Pull request by xinlipn**
Removed line 770, which is a dup of line 772 in this file: test/CMakeLists.txt

@atamazov , could you help review the change?

### CODE REVIEW

**Review by atamazov — APPROVED** [review]
LGTM!

**Comment by atamazov** [comment]
@xinlipn but my review has lost the magical power to allow the merging...

**Comment by xinlipn** [comment]
> @xinlipn but my review has lost the magical power to allow the merging...

@atamazov no worries. I'll figure it out. Thanks

**Review by JehandadKhan — DISMISSED** [review]
Good Catch

**Comment by JehandadKhan** [comment]
@junliume Please merge this when convenient

**Review by junliume — DISMISSED** [review]

**Review by junliume — APPROVED** [review]

**Pull request merged**
