### PR TITLE
[Navi21] Fix for Winograd. [All targets] Winograd `v21_1_2` -> `v21_2_3` update.

### PR DESCRIPTION
**Pull request by Slimakanzer**
This PR updates Winograd kernels to `v21_1_3` version.
Winograd changes compared to #626:
- Bug fix for Navi1x

## Local verification
- gfx906, rocm 4.0.0
- gfx90a, rocm 4.3.1

### CODE REVIEW

**Review by atamazov — APPROVED** [review]
Host code changes are Ok!

**Comment by atamazov** [comment]
@Slimakanzer Any known Jira or GitHub ticket related to Navi21? (it's Ok if none known)

How urgent is this, what do you think? E.g. would you like to cherry-pick this into current release branches, e.g. 4.5, or the users will not run into this issue most likely?

**Review by Kirpich30000 — APPROVED** [review]
lgtm

**Comment by Kirpich30000** [comment]
@atamazov no tickets that I'm aware of. IMHO it is unlikely that the users will run into this issue with 4.5.

**Comment by atamazov** [comment]
> @atamazov no tickets that I'm aware of. IMHO it is unlikely that the users will run into this issue with 4.5.

Good!

**Pull request merged**
