### PR TITLE
rename EuristicInit to HeuristicInit

### LINKED ISSUE #804: really, can we fix the typo of `EuristicInit`?
really, can we fix the typo of `EuristicInit`?

_Originally posted by @whchung in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/803#issuecomment-800523354_

### PR DESCRIPTION
**Pull request by xuhuisheng**
Right now, just rename EuristicInit to HeuristicInit, and no compile error, tensorflow and pytorch mnist samples run properly. Resolves #804

Do I need to keep EuristicInit() and add deprecated annotation?

### CODE REVIEW

**Comment by atamazov** [comment]
@xuhuisheng 
> Do I need to keep EuristicInit() and add deprecated annotation?

No. These methods are strictly internal to MIOpen Solvers. Just rename. Thanks!

**Review by atamazov — DISMISSED** [review]
LGTM!

**Comment by atamazov** [comment]
@xuhuisheng Formatting issues, see https://github.com/ROCmSoftwarePlatform/MIOpen/wiki/How-to-format-code

**Comment by xuhuisheng** [comment]
@atamazov 
I try reformat script and find it reformat too many codes `Showing with 2,425 additions and 2,610 deletions. `
https://github.com/xuhuisheng/MIOpen/commit/314d797f3be420aa5098f7cb12c4dcf96f8b9190

I am afraid of clang-format process the source codes that I havn't modified.

**Comment by atamazov** [comment]
@xuhuisheng 
> I am afraid of clang-format process the source codes that I havn't modified.

Wow... You're right... There was a typo in the wiki, fixed now. Please re-run this script from the root of MIOpen tree (where [.clang-format](https://github.com/ROCmSoftwarePlatform/MIOpen/blob/5ee21784e3671c1edda336e75c540e69b6c4c36a/.clang-format) resides).

**Comment by xuhuisheng** [comment]
@atamazov 
Run clang-form on root again. And affected files are even more.
`Showing 238 changed files with 3,375 additions and 3,572 deletions. `
https://hub.fastgit.org/xuhuisheng/MIOpen/commit/885c92b8513aa13b4e5e39b06b83059996626fa4

I used /opt/rocm/llvm/bin/clang-format which is llvm12 from ROCm-4.1.1.
I try `apt install clang-format` which is clang-format10.
Should I go to find clang-format3.8 to do reformating work?

**Comment by carlushuang** [comment]
@xuhuisheng 
yes you need clang-format-3.8 to do the formatting. If you use ubuntu, you can use following steps to install clang-format-3.8
```
sh -c "echo deb http://mirrors.kernel.org/ubuntu xenial main universe | tee -a /etc/apt/sources.list"
apt-get update
apt-get install clang-format-3.8
```

**Comment by xuhuisheng** [comment]
@carlushuang
Thank you, have reformatted. Checks had passed.
@atamazov 
Please review.

**Review by atamazov — APPROVED** [review]

**Comment by atamazov** [comment]
CI testing launched.

**Comment by xuhuisheng** [comment]
@atamazov 
It said that There are two job failed. I have no right to see the detail.
Please tell me if there is anything I can do.
Thanks

**Comment by atamazov** [comment]
@xuhuisheng I'll take care about this PR.

**Comment by atamazov** [comment]
@xuhuisheng To resolve CI issues, please merge latest `develop` into your branch. Thanks.

**Comment by xuhuisheng** [comment]
@xuhuisheng 
Done, Please review.

**Comment by atamazov** [comment]
@xuhuisheng Thanks! :tada:

**Pull request merged**
