### PR TITLE
update winograd convolution WTI computation (the second attempt)

### PR DESCRIPTION
**Pull request by CAHEK7**
Detailed description is in #2215
The PR is needed just to fix some CI-detected issues.

### CODE REVIEW

**Review by Kirpich30000 — DISMISSED** [review]
LGTM

**Comment by junliume** [comment]
Thank you! @CAHEK7 actually you can open PR within the repo instead of doing it over the folk, but it's up to your preference.

**Comment by atamazov** [comment]
@CAHEK7 ⚠️ **_Please do not force-push_**. This is NOT recommended due to several reasons. For example, this makes previous code reviews invisible on the "Code changes" tab (due to overwritten commit hashes). Force-pushing can only be used more or less safely if the branch has NOT yet been published for review.

**Comment by CAHEK7** [comment]
I agree and usually I'm trying to avoid it. That was a hide and seek game with clang-tidy and where it wants to see that cast.
Sorry for the inconvenience.

**Comment by atamazov** [comment]
@CAHEK7 Good!

**Review by Kirpich30000 — APPROVED** [review]
LGTM

**Review by junliume — APPROVED** [review]

**Pull request merged**
