### PR TITLE
[RNN] multi-stream as default solution

### PR DESCRIPTION
**Pull request by shurale-nkn**
added multi-stream as default solution at fp16

### CODE REVIEW

**Review by CAHEK7 — APPROVED** [review]

**Comment by junliume** [comment]
@shurale-nkn `test_rnn_seq_api` is failing with these changes, could you take a look? and also please resolve the conflicts. Thanks!

**Comment by JehandadKhan** [comment]
@shurale-nkn  Did we loose the env variable which enabled switching the implementation ?

**Comment by shurale-nkn** [comment]
> @shurale-nkn `test_rnn_seq_api` is failing with these changes, could you take a look? and also please resolve the conflicts. Thanks!

working on it



> @shurale-nkn Did we loose the env variable which enabled switching the implementation ?

No, MIOPEN_RNNFWD_exp always been there. Now we will choose MS as default solver without this env var.

**Comment by shurale-nkn** [comment]
> @shurale-nkn `test_rnn_seq_api` is failing with these changes, could you take a look? and also please resolve the conflicts. Thanks!

additional testing has shown that this happens only on the mi90a. It is most likely due to the small values in some distributions. Added WA.

**Pull request merged**
