### PR TITLE
[SWDEV-358495] Exclude GTest from install

### PR DESCRIPTION
**Pull request by JehandadKhan**
This PR  removes GTest from installing itself with the MIOpen install Target
We have also removed the redundant `hello_gtest` test.
[Addresses SWDEV-358495](https://ontrack-internal.amd.com/browse/SWDEV-358495)

### CODE REVIEW

**Review by junliume — APPROVED** [review]

**Comment by pramenku** [comment]
I see that PR has only gtest. What about gmock? gmock too is 3rd party.

Can we create new PR for removal.  rocm components, 3rd party packaging is not good idea. As such, no components does under /opt/rocm

**Comment by junliume** [comment]
Gtest includes both Gtest and GMock. The team has verified that no headers/libs are installed.

**Comment by pramenku** [comment]
> Gtest includes both Gtest and GMock. The team has verified that no headers/libs are installed.

Thanks for clarification @junliume

**Comment by pramenku** [comment]
@junliume 

if staging will take time, can we fast forward on this PR to amd-master branch.

Since sanity passed as commented in PR. So, removal will anyway not impact anything as it's just kind of revert of the change.

[[SWDEV-358495] Exclude GTest from install by JehandadKhan · Pull Request #1789 · ROCmSoftwarePlatform/MIOpen (github.com)](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1789)

**Comment by junliume** [comment]
> @junliume
> 
> if staging will take time, can we fast forward on this PR to amd-master branch.
> 
> Since sanity passed as commented in PR. So, removal will anyway not impact anything as it's just kind of revert of the change.
> 
> [[SWDEV-358495] Exclude GTest from install by JehandadKhan · Pull Request #1789 · ROCmSoftwarePlatform/MIOpen (github.com)](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1789)

@pramenku usually we do not cherry pick on mainline :( The current stage should be completed within the week. Is this issue blocking?

**Comment by pramenku** [comment]
> > @junliume
> > if staging will take time, can we fast forward on this PR to amd-master branch.
> > Since sanity passed as commented in PR. So, removal will anyway not impact anything as it's just kind of revert of the change.
> > [[SWDEV-358495] Exclude GTest from install by JehandadKhan · Pull Request #1789 · ROCmSoftwarePlatform/MIOpen (github.com)](https://github.com/ROCmSoftwarePlatform/MIOpen/pull/1789)
> 
> @pramenku usually we do not cherry pick on mainline :( The current stage should be completed within the week. Is this issue blocking?

Yes, @junliume  blocking onnx rt based all tests so I was requesting. Docker is failed to create due to this issue.
I was expecting merge sooner so not talked on this option before. :)

**Comment by pramenku** [comment]
This is not fixing the issue, [SWDEV-358495](https://ontrack-internal.amd.com/browse/SWDEV-358495)

**Pull request merged**
