### PR TITLE
Fix for issue #2734: Detect if "-fno-offload-uniform-block" works in HIP compiler.

### LINKED ISSUE #2734: error: unknown argument: -fno-offload-uniform-block
The handling of WORKAROUND_SWDEV_413293 assumes a compile and does not check if passing -fno-offload-uniform-block is valid
[ adding without checking in CMakeLists.txt
](https://github.com/ROCm/MIOpen/blob/develop/CMakeLists.txt#L263)

On Fedora Rawhide/F40, this is clang 17
clang version 17.0.6 (Fedora 17.0.6-6.fc40)
The latest release of clang.

The option -fno-offload-uniform-block is in the to be released clang 18.
It would be better to use check_cxx_compiler_flag() here.

### PR DESCRIPTION
**Pull request by atamazov**
- Resolves #2734.
- [Notice] Can be considered as an addition to PR #2307.
- By-product: Removes W/A from PR #2719 as it is no longer needed.

----
[Attribution] @junliume @JehandadKhan
- https://github.com/ROCm/MIOpen/labels/enhancement
- https://github.com/ROCm/MIOpen/labels/urgency_blocker (for Fedora Rawhide/F40 users only)
- Proposed reviewers:
  - @JehandadKhan 
  - @junliume 
  - @apwojcik 
  - @trixirt

### CODE REVIEW

**Comment by atamazov** [comment]
@junliume I'll update this one from develop ;)

**Comment by atamazov** [comment]
@junliume Updated from develop.

**Review by junliume — APPROVED** [review]

**Review by apwojcik — APPROVED** [review]
Verified on Windows. I confirm that the compilation is successful, and 100% of the tests passed on Navi21 and Navi31.

**Comment by atamazov** [comment]
@apwojcik Thanks!

**Comment by atamazov** [comment]
@JehandadKhan @junliume @apwojcik @trixirt Ready for review, testing & merging.

**Review by junliume — APPROVED** [review]

**Pull request merged**
