### PR TITLE
[FP32] [miopengemm][Workaround] Disabled GemmBwd1x1_stride1

### PR DESCRIPTION
**Pull request by DrizztDoUrden**
Workaround for https://github.com/ROCmSoftwarePlatform/MIOpenGEMM/issues/59.
As in title, disables on backward gemm solver for MIOpenGEMM, which failes on CI.
This blocks #1503

### CODE REVIEW

**Review by junliume — APPROVED** [review]

**Comment by DrizztDoUrden** [comment]
Wait, i have accidentally pushed some unrelated changes

**Comment by DrizztDoUrden** [comment]
Removed unrelated changes

**Comment by DrizztDoUrden** [comment]
@junliume something's very wrong, I've got like 4 gpu detection failure and stuff in a row on the CI

**Comment by junliume** [comment]
> @junliume something's very wrong, I've got like 4 gpu detection failure and stuff in a row on the CI

Yes I have invited you to the CI Teams thread, and temporarily disabled a few nodes manually.

**Review by junliume — APPROVED** [review]

**Pull request merged**
