### PR TITLE
Restructure find-db to match Find2.0 requirements

### PR DESCRIPTION
**Pull request by atamazov**
- Implements https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1987#issuecomment-1475425835.
  - `WORKAROUND_ISSUE_1987` provides compatibility with old format (for reading existing system find-db files, A/B testing etc). Let's keep it until system find-db files regenerated in the new format.
- [performance][Immediate mode] Optimize out unnecessary IsApplicable calls.
  - ⚠️ It is especially important to avoid IsApplicable of MLIR solvers
- [tests] `test_find_db` fixed to avoid false failures. Logging improved to ease triaging.
- [quality] Removes unused code (`FindDbKCacheKey` etc), improves logging etc.

### The most important changes
- e7f3ee839bf7b24f9fcfd9ccd79b87349e740c2e Change find-db key from algorithm to solver_id. Write all solvers' results info find-db. In Find API calls, emulate 1.0 results.
- e83ffbf85750442c9cdaa9ed517b9f7015f54c8b WORKAROUND_ISSUE_1987: Maintain backward compatibility with 1.0 find-db format.
- **_By-product:_** ee4365e483e5ca16dbffef40b138faa386424407 [Immediate mode] Optimize out unnecessary IsApplicable calls.

### Less important things
- 1682c7da1cb047bd0b08ecd15fb43af011a961f0 Dismiss FindDbKCacheKey::network_config and related stuff
- 85b1f9abfed16526a2c7f644394d9f6dc7dfec14 Dismiss the whole FindDbKCacheKey
- 10b69f63ab751baedfec79968522d13a1254e0b9 Removed CheckInvokerSupport (we have invokers for all conv solvers)
- ab4e60263e7c387aa4492d3d3c585425c167e244 LogFindDbItem(): remove dead code and improve.
- 34f724ebf1f9d6862cc09dd0f0b0929c47fccb23 [test_find_db] Fix to really use find-db and avoid false failures.
- 42ec951c641ec822cf85b8e4463569276673ca5d Improve error handling in conv_algo_name.cpp to avoid abortions with unclear error messages like "MIOpen Error: _Map_base::at".
- fcf4b9a035ef2aebf0a52903bb5328fbeb5a6408 [test_find_db] Log elapsed time - useful for triaging failures.

### NFC changes (no need to review, basically)
- 681ff10b11d89ccc789c42c92ea7fc06b7102500 Removed unused header
- e1a5680268372704cd612d1154701adfabf8db19 Improved clarity
- 03a3f212f39f28ab206b3c7c12b60f32659d7f15 [debug] Always log (at Info2 level) kernel names being run

----
[Attribution] @junliume @johnny-keker 
- https://github.com/ROCmSoftwarePlatform/MIOpen/labels/enhancement https://github.com/ROCmSoftwarePlatform/MIOpen/labels/urgency_blocker https://github.com/ROCmSoftwarePlatform/MIOpen/labels/quality https://github.com/ROCmSoftwarePlatform/MIOpen/labels/IMPACTS_FIND_DB
- Milestone: **_ROCm 5.6_**
- Reviewers: @DrizztDoUrden @cderb @JehandadKhan

### CODE REVIEW

**Comment by atamazov** [comment]
## 🌀 Performance & correctness testing

- FP32 conv, Radeon VII, ROCm 5.3
- FP16 conv, Radeon VII, ROCm 5.3
- FP32 conv, Navi 21, CI docker (ROCm 5.3 + libMLIR for 5.5)
- FP16 conv, Navi 21, CI docker (ROCm 5.3 + libMLIR for 5.5)

🟢 No correctness or performance regressions.

**Comment by atamazov** [comment]
@junliume @johnny-keker Performance & correctness testing done, ready for review & CI testing. Please set attributes on this PR.

**Review by cderb — DISMISSED** [review]

**Comment by atamazov** [comment]
## 🌀 Performance & correctness testing

- FP32 conv, Radeon VII, ROCm 5.3
- FP16 conv, Radeon VII, ROCm 5.3
- FP32 conv, Navi 21, CI docker (ROCm 5.3 + libMLIR for 5.5)
- FP16 conv, Navi 21, CI docker (ROCm 5.3 + libMLIR for 5.5)

🟢 No correctness or performance regressions.

**Comment by atamazov** [comment]
@jerryyin Please have a look at commit https://github.com/ROCmSoftwarePlatform/MIOpen/pull/2033/commits/ee4365e483e5ca16dbffef40b138faa386424407 _[Immediate mode] Optimize out unnecessary IsApplicable calls._

**Comment by atamazov** [comment]
@DrizztDoUrden @JehandadKhan @johnny-keker Ready for review & CI testing.

**Comment by junliume** [comment]
@atamazov  could you merge the latest develop which unblocked our CI? I will kick off another round of CI on it.

**Comment by atamazov** [comment]
@junliume @DrizztDoUrden @JehandadKhan @johnny-keker Merged. Ready for review & CI testing.

**Review by DrizztDoUrden — APPROVED** [review]
LGTM

**Review by jerryyin — APPROVED** [review]
ee4365e LGTM

**Comment by atamazov** [comment]
@junliume @JehandadKhan Anything that prevents this from merging?

**Review by junliume — APPROVED** [review]

**Comment by junliume** [comment]
@atamazov  I have to revert this change since neither #2060 nor #2061 were enough to unblock the TIP of `develop`.

FIN needs to be updated with the problem-context splitting, we are getting CI issues like:
```
[2023-03-31T20:03:18.212Z] /var/jenkins/workspace/MLLibs_MIOpen_fix_conflict_2033/fin/src/include/conv_fin.hpp:198:16: error: no matching constructor for initialization of 'miopen::ConvolutionContext'

[2023-03-31T20:03:18.212Z]     auto ctx = miopen::ConvolutionContext{problem};

[2023-03-31T20:03:18.212Z]                ^     
```

Here is how to reproduce:
```
git submodule init
git submodule sync
git submodule update fin
mkdir build; cd build
CXX=/opt/rocm/llvm/bin/clang++ cmake -DCMAKE_PREFIX_PATH=/var/jenkins/workspace/MLLibs_MIOpen_fix_conflict_2033/install -DCMAKE_INSTALL_PREFIX= -DCMAKE_BUILD_TYPE=release ..
make -j32 all
```

**Comment by atamazov** [comment]
@junliume 
> ```
> [2023-03-31T20:03:18.212Z] /var/jenkins/workspace/MLLibs_MIOpen_fix_conflict_2033/fin/src/include/conv_fin.hpp:198:16: error: no matching constructor for initialization of 'miopen::ConvolutionContext'
> 
> [2023-03-31T20:03:18.212Z]     auto ctx = miopen::ConvolutionContext{problem};
> 
> [2023-03-31T20:03:18.212Z]                ^     
> ```

The actual source code line at https://github.com/ROCmSoftwarePlatform/MIFin/tree/6fb932e58535f9c8e98da702a9dd96e97ff82ae9 is:

image

Something is wrong with the test.

**Comment by atamazov** [comment]
@junliume Oops, I see now. Somehow this PR contains incorrect fin changes. Let me fix the issue and create a new PR

**Pull request merged**
