### PR TITLE
[NHWC][asm igemm] add support for several NHWC bwd ssd config, when k=4x, 2x

### PR DESCRIPTION
**Pull request by carlushuang**
```
convfp16 -n 120 -c 256 -H 1 -W 1 -k 340 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC
convfp16 -n 120 -c 256 -H 3 -W 3 -k 340 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC
convfp16 -n 120 -c 256 -H 5 -W 5 -k 510 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC
convfp16 -n 120 -c 512 -H 10 -W 10 -k 510 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC
convfp16 -n 120 -c 512 -H 19 -W 19 -k 510 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC
convfp16 -n 120 -c 256 -H 38 -W 38 -k 340 -y 3 -x 3 -p 1 -q 1 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 2 -t 1 --in_layout NHWC --fil_layout NHWC --out_layout NHWC
```

SSD configs of above are currently not supported in MIOpen. This PR add support for these configs by adding several new kernels which support padded gemm k.

~~This PR has only 1 `.cpp` file and 1 `.txt` file changed, other is asm files. Need feedback of #1113 first then consider if continue integrate asm file as plain text or in other form like .tar.bz2~~ keep current process as discussed in https://github.com/ROCmSoftwarePlatform/MIOpen/issues/1113#issuecomment-907304877

perf data : [ssd-perf](https://amdcloud-my.sharepoint.com/:x:/g/personal/carhuang_amd_com/EXfsD0pCcOpPi-TyduEgChYB2QT2PV0adIKTZMHZMnOkyQ?e=hriwbY), please check tab PR1114

### CODE REVIEW

**Review by junliume — APPROVED** [review]

**Review by shaojiewang — APPROVED** [review]
LGTM
Just please push a performance data for the aimed cases.

**Comment by carlushuang** [comment]
@shaojiewang OK, updated in description.

**Comment by atamazov** [comment]
@carlushuang Does it require retuning? Which solvers? What may happen until retuning?

/cc @JehandadKhan

**Comment by carlushuang** [comment]
@atamazov sorry for missing information here. Yes, this PR may affect `ConvAsmImplicitGemmGTCDynamicBwdXdlopsNHWC`, but in performance. Before this PR, this solver just not support the config where k=4x or 2x. After this PR, now it can support. The real convolution configs affected is listed in description of this PR, the SSD configs.

**Pull request merged**
