### PR TITLE
Updating the kernel installation script as per new package name

### PR DESCRIPTION
**Pull request by pruthvistony**

### CODE REVIEW

**Comment by pruthvistony** [comment]
MIOpen kernels package name update PR - https://github.com/ROCmSoftwarePlatform/MIOpenKernels/pull/10

**Comment by daniellowell** [comment]
@pruthvistony Please describe why this is needed, what changes are made, and the priority level. Thanks!

**Comment by pruthvistony** [comment]
> @pruthvistony Please describe why this is needed, what changes are made, and the priority level. Thanks!

Apologies, missed to give the explanation. 
Currently the MIOpen kernel package names ends with numbers(the package name seen the header of the package), this is not desirable and causes confusion for multi version ROCm installation. So the change is done to append "pkg" to the package name.

**Review by JehandadKhan — APPROVED** [review]

**Comment by pruthvistony** [comment]
@daniellowell,
Can you please help on getting this code merged.

**Pull request merged**
