### PR TITLE
ConvolutionDescription:DirConvFindCore non-static 

### PR DESCRIPTION
**Pull request by alexandraBara**
For Fin/Tuna we need this function non-static.
Moved to ConvDescription for ease of use.

### CODE REVIEW

**Comment by atamazov** [comment]
How urgent is this?

I think you can use `ConvolutionDescriptor::FindConvFwdAlgorithm()`, right?

WRT `DirConvFindCore()` -- basically, this function should be eliminated (its contents moved into `ConvolutionDescriptor::FindConvFwdAlgorithm()`)

**Comment by alexandraBara** [comment]
> How urgent is this?
> 
> I think you can use `ConvolutionDescriptor::FindConvFwdAlgorithm()`, right?
--> i will look into this function
> 
> WRT `DirConvFindCore()` -- basically, this function should be eliminated (its contents moved into `ConvolutionDescriptor::FindConvFwdAlgorithm()`)
--> we need this as soon as possible so we can progress with our tool.

**Comment by atamazov** [comment]
> we need this as soon as possible so we can progress with our tool.

What do you plan to do with backward convolutions? There is no functions like `DirConvFindCore()` for Bwd and WrW.

Shall we start from the beginning, perhaps. Could you please explain what functionality you need?

**Comment by atamazov** [comment]
Maybe this topic deserves a separate ticket for discussion etc.

**Comment by alexandraBara** [comment]
> Maybe this topic deserves a separate ticket for discussion etc.

I see, so far we were only looking at forward conv. I will discuss this with @JehandadKhan  and then start a discussion thread. We definitely want the other directions covered as well.

**Comment by JehandadKhan** [comment]
@atamazov Thanks for the suggestions, lets re-evaluate what needs to be done and come up with a better solution. @alexandraBara will convert this to a draft until we flush the design completely.

**Comment by atamazov** [comment]
@JehandadKhan If I knew your needs better, I might be able to try to suggest something.

**Pull request closed without merging**
