### PR TITLE
Rename hipcompiler igemm flag

### PR DESCRIPTION
**Pull request by TejashShah**
Addresses #225

### CODE REVIEW

**Comment by atamazov** [comment]
@TejashShah Could you please remind the purpose of this macro? To distinguish OCL from HIP compilation in our common headers? Is some other "kind" of compilation possible (i.e. nor OCL neither HIP)?

**Comment by TejashShah** [comment]
> 
> 
> The definition has changed, but I do not see changes in places where the macro is _used_. If we do not use this macro, then we do not need its definition.

Added missing files. I forgot to add while i was switching from rocm-framework7 to miopen908-1 machine.

**Comment by TejashShah** [comment]
> 
> 
> @TejashShah Could you please remind the purpose of this macro? To distinguish OCL from HIP compilation in our common headers? Is some other "kind" of compilation possible (i.e. nor OCL neither HIP)?

Yes, to distinguish OCL from HIP. I treat HIP-clang and HIP-HCC as the same as HIP-clang hasn't created any issue yet.

**Comment by daniellowell** [comment]
@TejashShah  Jenkins is showing a bunch of name collisions, and errors.

**Comment by TejashShah** [comment]
> 
> 
> This PR is showing major compiler errors.

Looking into it.

**Comment by TejashShah** [comment]
> 
> 
> This PR is showing major compiler errors.

Didn't test on Vega20 kernel so couldn't detect locally. Now, I fixed it.

**Comment by TejashShah** [comment]
> 
> 
> I recommend removing definitions of `HIP_PLATFORM` in Solvers and reverting kernel sources back. AFAICS `__HIP_PLATFORM_HCC__` is always defined when HIP sources are being built.
> 
> Nevertheless this is OK to merge.

What is driving this change of mind? - I was of opinion that let's not change the flag (perhaps not persuasive) 

>Tejash: I wouldn't want to change anything if I have option to do. I will try to remove the following >code from all igemm solvers and check if it runs fine in hipclang and rocm3.3 and rocm3.5. if it >works, implies that the compiler is setting this variable correctly (no need to set workaround), I > >would remove the following line.
>std::string(" -D__HIP_PLATFORM_HCC__=1") +
>
>If I can't run the kernel correctly w/o the above line of code, I will introduce HIP_PLATFORM_HCC >such as
>std::string(" -DHIP_PLATFORM_HCC=1") +

>Artem: I like conservatism ;) Please be aware that Jenkins uses something older than ROCm3.3. > >Good luck
https://github.com/ROCmSoftwarePlatform/MIOpen/issues/225#issuecomment-636228188

Would you be fine if I just change this PR to remove this line?
>std::string(" -D__HIP_PLATFORM_HCC__=1") +
Or are you concerned that releases prior to rocm3.3 where __HIP_PLATFORM_HCC__ was not defined things won't work?

**Comment by atamazov** [comment]
> Would you be fine if I just change this PR to remove this line?
> ```
> std::string(" -D__HIP_PLATFORM_HCC__=1") +
> ```

Yes, I think this should work for us.

If some old HIP compiler has issue, we can provide formal workaround as soon as bug report arrives.

> What is driving this change of mind?

Less changes. Less code. Removal of code that is actually workaround for not marked/formalized as a workaround.

**Pull request merged**
