### PR TITLE
[HOTFIX][Navi21][SWDEV-292187] Use WAVE64 mode for all OpenCL kernels. Add FP16 test. Narrow W/A for #1148.

### PR DESCRIPTION
**Pull request by atamazov**
Many OpenCL kernels are written in assumption that wavesize is 64, but for Navi21 the compiler produces ISA for wavesize 32 by default. This results in UB which manifests in random errors, the reason of those is almost impossible to clearly identify.

The PR is expected to improve stability of OCL kernels on Navi21 (and may partially resolve SWDEV-292187).

* Enabled WAVE64 && CU mode for all OpenCL kernels ("-mwavefrontsize64 -mcumode").
  - Added `MIOPEN_DEBUG_OPENCL_WAVE64_NOWGP` env var to disable (for triaging/debugging only)
* [Jenkinsfile] Added 'Fp16 Hip All gfx1030' test stage
* [tests] Refactored & narrowed W/A for #1148:
  - Removed `test_soft_max`, `test_conv_group`, `test_conv_extra`, `test_conv_for_implicit_gemm` from its scope.
* [test] Added W/A for #1334.

### CODE REVIEW

**Comment by junliume** [comment]
@atamazov latest updates from Gowtham:
"
254f5f5117ffd948b45e6857f185e1710a864ecc is the commit..  **(the second to the last)**
i am observing NAN with this, and NAN came at around 20,000 steps it self 
"

**Comment by atamazov** [comment]
Please review.

**Comment by junliume** [comment]
@atamazov ooops accidentally merged dev again almost at the same time ...

**Comment by atamazov** [comment]
@junliume NP, resolved ;))

**Comment by atamazov** [comment]
@junliume Just in case - I've intentionally launched two CI jobs in parallel (16 and 17); please let'em go.

**Comment by junliume** [comment]
@atamazov waiting for the CI run #18 to pass, it seems that this is the last piece before initiating the next round of staging? Just to confirm. Thanks!

**Comment by atamazov** [comment]
@junliume Yes!

**Review by junliume — APPROVED** [review]

**Comment by junliume** [comment]
@atamazov  some issues were reported, please check your mail. Thanks!

**Comment by atamazov** [comment]
> @atamazov some issues were reported, please check your mail. Thanks!

MIOPEN_DEBUG_OPENCL_WAVE64_NOWGP=0 switches wave64 mode off.

**Pull request merged**
