### PR TITLE
Tuning results for 2.6

### PR DESCRIPTION
**Pull request by alexandraBara**
Solvers/networks tuned --> https://github.com/ROCmSoftwarePlatform/MIOpen/issues/270

### CODE REVIEW

**Comment by atamazov** [comment]
Hmm... I do not think that anyone is really expects that I am able to review this 300k+ lines patch. What should I do?

**Comment by alexandraBara** [comment]
@atamazov  @JehandadKhan since we didn't tune OCL this round, I removed these solvers ('ConvHipImplicitGemmV4R4Xdlops_1x1', 'ConvHipImplicitGemmV4R4FwdXdlops', 'ConvHipImplicitGemmV4_1x1', 'ConvHipImplicitGemmV4Fwd', 'ConvHipImplicitGemmV4WrW', 'ConvHipImplicitGemmV4R4WrWXdlops') manually with find and replace.

Im no expert at sed but I did a lot of testing and vimdiffs  to make sure i didn't remove extra characters or leave out any un-removed solvers. Please review this last commit diligently :)

**Comment by alexandraBara** [comment]
> Hmm... I do not think that anyone really expects that I am able to review this 300k+ lines patch. What should I do?

wait til u see my last commit :D

**Comment by JehandadKhan** [comment]
> Im no expert at sed but I did a lot of testing and vimdiffs to make sure i didn't remove extra characters or leave out any un-removed solvers. Please review this last commit diligently :)

Its not realistic to verify this by reading the code. I will run the benchmarks to verify this works. I have the results for HIP / gfx906/60 which I would run again with the updated PR.

**Comment by daniellowell** [comment]
@alexandraBara @JehandadKhan Status update.

**Comment by JehandadKhan** [comment]
[Here is a link](https://amdcloud-my.sharepoint.com/:x:/g/personal/jkhan_amd_com/Ed4ZHFxebb9HneftfTws2RYBy9CdsPc8G60N4wr_VQ2TJA?e=3N37UR) to the comparative analysis for this PR

**Pull request merged**
