### PR TITLE
For CK solvers change PerfConfigBase to PerfConfigBaseCK

### PR DESCRIPTION
**Pull request by Dmantri98**
To allow for correct serialization of kernel_id CK solver's should use the PerfConfigBaseCK struct.

### CODE REVIEW

**Review by cderb — APPROVED** [review]

**Review by CAHEK7 — APPROVED** [review]

**Comment by bghimireamd** [comment]
Remove [`Visit`](https://github.com/ROCm/MIOpen/blob/develop/src/include/miopen/solver.hpp#L4660) from the `PerformanceConfigHipImplicitGemm3DGroupWrwXdlops` since it now derives from `PerfConfigBaseCK`.  Ref : https://github.com/ROCm/MIOpen/pull/2354#discussion_r1321885787

**Review by iq136boy — APPROVED** [review]

**Comment by Dmantri98** [comment]
> Remove [`Visit`](https://github.com/ROCm/MIOpen/blob/develop/src/include/miopen/solver.hpp#L4660) from the `PerformanceConfigHipImplicitGemm3DGroupWrwXdlops` since it now derives from `PerfConfigBaseCK`. Ref : [#2354 (comment)](https://github.com/ROCm/MIOpen/pull/2354#discussion_r132188578

**Comment by Dmantri98** [comment]
> Remove [`Visit`](https://github.com/ROCm/MIOpen/blob/develop/src/include/miopen/solver.hpp#L4660) from the `PerformanceConfigHipImplicitGemm3DGroupWrwXdlops` since it now derives from `PerfConfigBaseCK`. Ref : [#2354 (comment)](https://github.com/ROCm/MIOpen/pull/2354#discussion_r1321885787)

Removed the Visit (I mistakenly wrote Find in the commit message) function from all structs that derive from PerfConfigBaseCK.

**Review by amberhassaan — APPROVED** [review]
Looks good.

**Review by bghimireamd — APPROVED** [review]

**Review by junliume — APPROVED** [review]

**Pull request merged**
