### PR TITLE
Disable solver that does not have Invoker yet - ConvHipImplicitGemmV4R4GenXdlopsWrWFp32

### PR DESCRIPTION
**Pull request by atamazov**
Resolves this: https://github.com/ROCmSoftwarePlatform/MIOpen/pull/152#pullrequestreview-413990855

Expected to fix the GPU memory access fault on gfx908 with
```
./bin/test_conv2d --float --cmode conv --pmode default --group-count 1 --input 4, 64, 14, 14 --weights 24, 64, 5, 5 --pads_strides_dilations 2 2 1 1 1 1 --trans_output_pads 0 0
```

### CODE REVIEW

**Comment by daniellowell** [comment]
Why would this cause a GPU memory access fault? Bad pointers?

**Comment by atamazov** [comment]
I've discussed this case with Vasya. Basically, when Invoker is missing, the library should fail with a run-time error, under the control of the library. So this is not an UB. I am lowering the priority.

**Comment by atamazov** [comment]
Good news. We do not have requirement that iGemm WrW Solver must have Invokers. This PR is not needed.

[off-topic] Bad news. We must implement support for iGemm WrW Invokers ASAP. @DrizztDoUrden is switching to this.

**Comment by atamazov** [comment]
@zjing14 I think this is still good advice that I recommend considering:
```C++
    /// \todo Please use:
    /// if(solver::ConvHipImplicitGemmV4R4GenXdlopsWrWFp32{}.IsApplicable(ctx))
    /// instead of:
    /// if(ctx.IsFp32() && ctx.group_counts == 1)
```
The rest is not needed.

**Pull request closed without merging**
