### PR TITLE
[hipRTC] Fix conflicting workaround with updated hipRTC

### PR DESCRIPTION
**Pull request by junliume**

### CODE REVIEW

**Comment by junliume** [comment]
@atamazov FYI

CI still fails with `Fp32 Hip AnyGPU`
```
[2023-12-18T09:51:31.104Z]   40/1760 Test   #42: test_reduce_test ........................................................................................................................................................................................................................................................................................................................................................................................................***Failed  Error regular expression found in output. Regex=[FAILED]  1.89 sec
[2023-12-18T09:51:31.104Z] PRNG seed: 12345678
[2023-12-18T09:51:31.104Z] MIOpen(HIP): Error [Compile] 'hiprtcCompileProgram(prog.get(), c_options.size(), c_options.data())' gridwise_generic_reduction_first_call_threadwise_reduce_partial_dims.cpp: HIPRTC_ERROR_COMPILATION (6)
[2023-12-18T09:51:31.105Z] MIOpen(HIP): Error [BuildHip] HIPRTC status = HIPRTC_ERROR_COMPILATION (6), source file: gridwise_generic_reduction_first_call_threadwise_reduce_partial_dims.cpp
[2023-12-18T09:51:31.105Z] MIOpen(HIP): Warning [BuildHip] In file included from /tmp/comgr-c9c33f/input/gridwise_generic_reduction_first_call_threadwise_reduce_partial_dims.cpp:28:
[2023-12-18T09:51:31.105Z] In file included from /tmp/comgr-c9c33f/include/sequence.hpp:5:
[2023-12-18T09:51:31.105Z] /tmp/comgr-c9c33f/include/type.hpp:101:42: error: no type named 'remove_reference' in namespace 'std'
[2023-12-18T09:51:31.105Z] using remove_reference_t = typename std::remove_reference<T>::type;
[2023-12-18T09:51:31.105Z]                            ~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~
```

**Comment by atamazov** [comment]
@junliume What is the issue this PR is intended to fix?

**Comment by atamazov** [comment]
@junliume No need to answer, I see, thanks.

**Comment by junliume** [comment]
replaced by #2637

**Pull request closed without merging**
