### PR TITLE
Make UserDb optional 

### PR DESCRIPTION
**Pull request by JehandadKhan**
Intercepts the UserDb creation at the MultiFileDb level and disables it.

### CODE REVIEW

**Comment by JehandadKhan** [comment]
@daniellowell  This PR is ready for review

**Comment by atamazov** [comment]
@JehandadKhan Why we need this?

**Comment by daniellowell** [comment]
Static check failed

**Comment by JehandadKhan** [comment]
> Static check failed

They are for some iGEMM solvers, I am not sure why it was triggered. I have fixed the errors however.

**Pull request merged**
