### PR TITLE
[HotFix]Add split_k to 2d wrw ck solver

### PR DESCRIPTION
**Pull request by iq136boy**
The PR is a HotFix to add split_k as tuning parameter to 2d wrw solver to handle the CVT conv cases performance regression compared to the H100. 

The code may still need to be refactored for elegance. this will be addressed later in a separate following PR.

### CODE REVIEW

**Comment by iq136boy** [comment]
@junliume @JehandadKhan I think this PR can be merged.

**Review by amberhassaan — CHANGES_REQUESTED** [review]
`wrw_implicitgemm_ck_util.h` is a duplicate of `implicitgemm_ck_util.h`. Why can't we find a way to make minimal changes in the code instead of duplicating a large file.

**Comment by iq136boy** [comment]
> `wrw_implicitgemm_ck_util.h` is a duplicate of `implicitgemm_ck_util.h`. Why can't we find a way to make minimal changes in the code instead of duplicating a large file.

@amberhassaan As I mentioned, this PR is a Hotfix for the urgent required by CVT model. In fact, I am currently working on the refactoring of the code to find a way to combine the two files together. But it might take some time considering the tests and CI run through. That is why I just simply add another header file to handle the wrw cases for the urgent requirement. At the same time, I am working on the refactoring stuff to make the code neat and clean in the following PR.

**Comment by amberhassaan** [comment]
> > `wrw_implicitgemm_ck_util.h` is a duplicate of `implicitgemm_ck_util.h`. Why can't we find a way to make minimal changes in the code instead of duplicating a large file.
> 
> @amberhassaan As I mentioned, this PR is a Hotfix for the urgent required by CVT model. In fact, I am currently working on the refactoring of the code to find a way to combine the two files together. But it might take some time considering the tests and CI run through. That is why I just simply add another header file to handle the wrw cases for the urgent requirement. At the same time, I am working on the refactoring stuff to make the code neat and clean in the following PR.

I'd like to impose some minimal quality criteria on `hot fixes`. `hot fixes` shouldn't mean anything goes.

**Comment by iq136boy** [comment]
> `wrw_implicitgemm_ck_util.h` is a duplicate of `implicitgemm_ck_util.h`. Why can't we find a way to make minimal changes in the code instead of duplicating a large file.

@amberhassaan  working on combining the two files to avoid duplicate.

**Comment by iq136boy** [comment]
Close this PR. Issue was solved in [PR#3091](https://github.com/ROCm/MIOpen/pull/3091)

**Pull request closed without merging**
