### PR TITLE
Gru redundant copy

### PR DESCRIPTION
**Pull request by zpwenjh**
Resolves issue #880 
This pr remove the redundant copy in gru computation.

### CODE REVIEW

**Comment by shaojiewang** [comment]
CI failed in test_gru.

**Comment by atamazov** [comment]
@zpwenjh The following error
image
happened during the "Fp32 OpenCL" stage (see ./Jenkinsfile)

**Comment by ce1adon** [comment]
@atamazov 
Please find my comments here https://github.com/ROCmSoftwarePlatform/MIOpen/issues/880#issuecomment-825328183

**Comment by ce1adon** [comment]
@atamazov @shaojiewang @zpwenjh The logic of this PR is incorrect. Please revert.

**Pull request closed without merging**
