### PR TITLE
resolve Nan issue when using tf - SWDEV-285232

### PR DESCRIPTION
**Pull request by shaojiewang**
Regarding https://ontrack-internal.amd.com/browse/SWDEV-285232. resolve Nan issue. 
With this branch, nan issue is gone.
1. remove aggressive padding method for weights' loading.
2. add condition to check in solver.

### CODE REVIEW

**Comment by atamazov** [comment]
Shall we run it on CI?

**Comment by shaojiewang** [comment]
Self test done, ready for review.

**Review by carlushuang — APPROVED** [review]
LGTM. This fix all the fwd kernels by setting the proper range check in sgpr[2:3] of buffer load instruction

**Review by atamazov — APPROVED** [review]
I do not see anything bad))

**Comment by atamazov** [comment]
@shaojiewang Can you please add regression tests for this issue?

**Comment by shaojiewang** [comment]
> @shaojiewang Can you please add regression tests for this issue?

The test is done with tensorflow as described in [SWDEV-285232]( https://ontrack-internal.amd.com/browse/SWDEV-285232). But I do not observe problem when running only MIOpenDriver. Do you mean to add tensorflow test to CI?

**Comment by junliume** [comment]
@atamazov CI passed, large number of file while actual changes are small and have benign looks. As @shaojiewang commented "tested for about 1 day. No nan issue is observed." Ready to merge?

**Comment by atamazov** [comment]
Yes. But we need to think about regression tests -- I mean the ones that ran on our CI and ensure that the same bug will not appear in the future.

**Pull request merged**
