### PR TITLE
use find_package() for Eigen and frugally-deep

### PR DESCRIPTION
**Pull request by apwojcik**
Both libraries provide CMake configuration files, so it is much better to use `find_package()` instead of manually maintaining the header files' discovery.

### CODE REVIEW

**Review by junliume — APPROVED** [review]

**Review by DrizztDoUrden — APPROVED** [review]

**Comment by arvindcheru** [comment]
Basic Query - Are we expecting the dependencies frugally-deep, Eigen3 packages to pre-installed for this change?  Are we expecting any additional changes to optimize the search path if we are expecting these dependent packages are searched from the deps directory?

**Comment by atamazov** [comment]
@arvindcheru 
> Are we expecting the dependencies frugally-deep, Eigen3 packages to pre-installed for this change?

Yes, these a listed in requirements.txt

**Comment by atamazov** [comment]
@junliume @JehandadKhan @apwojcik 🔴 This breaks compatibility with ROCm 5.7.0.

The build in my 5.7.0 docker (rocm/miopen:ci_429410) fails with the following:
```bash
CMake Error at src/CMakeLists.txt:736 (find_package):
  Found package configuration file:

    /usr/local/lib/cmake/frugally-deep/frugally-deepConfig.cmake

  but it set frugally-deep_FOUND to FALSE so package "frugally-deep" is
  considered to be NOT FOUND.

-- Configuring incomplete, errors occurred!
```
I had to `-DMIOPEN_ENABLE_AI_KERNEL_TUNING=Off -DMIOPEN_ENABLE_AI_IMMED_MODE_FALLBACK=Off` to W/A this.

With 6.0 RC (rocm/miopen:ci_fbea27) and 5.7.1 (rocm/miopen:ci_3eb168) dockers, everything is fine.

**Comment by junliume** [comment]
> @junliume @JehandadKhan @apwojcik 🔴 This breaks compatibility with ROCm 5.7.0.
> 
> The build in my 5.7.0 docker (rocm/miopen:ci_429410) fails with the following:
> 
> ```shell
> CMake Error at src/CMakeLists.txt:736 (find_package):
>   Found package configuration file:
> 
>     /usr/local/lib/cmake/frugally-deep/frugally-deepConfig.cmake
> 
>   but it set frugally-deep_FOUND to FALSE so package "frugally-deep" is
>   considered to be NOT FOUND.
> 
> -- Configuring incomplete, errors occurred!
> ```
> 
> I had to `-DMIOPEN_ENABLE_AI_KERNEL_TUNING=Off -DMIOPEN_ENABLE_AI_IMMED_MODE_FALLBACK=Off` to W/A this.
> 
> With 6.0 RC (rocm/miopen:ci_fbea27) and 5.7.1 (rocm/miopen:ci_3eb168) dockers, everything is fine.

I guess this issue was not found because our CI docker is ROCm 5.7.1 based. Let me check if there is a quick workaround for backward compatibility.

**Update**: reproduced the issue locally, and we may need a quick fix or back this merge out

**Comment by atamazov** [comment]
@junliume #2610 resolves this.

**Pull request merged**
