### PR TITLE
MI300 TunaNet Update: CK FWD and WRW Solvers Updated

### PR DESCRIPTION
**Pull request by msaudulhassan**
- Updated TunaNet for MI300 to incorporate updates in the CK Fwd and CK Wrw grouped solvers
- Documented heuristics code

### CODE REVIEW

**Comment by msaudulhassan** [comment]
This PR is affected by [Issue#3129](https://github.com/ROCm/MIOpen/issues/3129). However, the issue is not with TunaNet itself by rather the `conv::ProblemDescription` object that TunaNet uses to parse the convolution problem into the model's input vector. This PR can therefore go ahead

**Comment by junliume** [comment]
@msaudulhassan could you help to align with @bartekxk on this change? We reverted the change in CK first, if this PR conflicts again with the revert we need to issue two PRs (one in CK one in MIOpen) in a planned way. Thanks!

**Review by cderb — APPROVED** [review]

**Review by iq136boy — APPROVED** [review]

**Comment by junliume** [comment]
@msaudulhassan any updates on this PR? Should it work together with necessary changes from CK?

**Comment by msaudulhassan** [comment]
> @msaudulhassan any updates on this PR? Should it work together with necessary changes from CK?

This PR is good to be merged

**Review by junliume — APPROVED** [review]

**Pull request merged**
